### PR TITLE
Tidy up of the unit test printing code

### PR DESCRIPTION
**Pull request by johnelse**

### CODE REVIEW

**Comment by euanh** [comment]
Looks like Travis ran into the new Async blocking-function checks.

**Comment by johnelse** [comment]
Yep, xen-api-client is failing in the same way. I'll try and fix it...

**Comment by johnelse** [comment]
I believe I've fixed xen-api-client now. Travis is not letting me restart the xen-api build though...

**Comment by johnelse** [comment]
Travis is happy now.

**Pull request merged**
