### PR TITLE
Filter out link local address when getting host IPv6

### PR DESCRIPTION
**Pull request by benjamreis**
The link local addresses can't be used

### CODE REVIEW

**Review by lindig — CHANGES_REQUESTED** [review]
I think this filter should be factored out into one of the helper modules and not repeated.

**Comment by benjamreis** [comment]
So if I mutualize and use this lib: https://opam.ocaml.org/packages/ipaddr/

Would that be okay?
We can then extend bit by bit the use of the lib in other cases.

**Comment by lindig** [comment]
Yes, using such a library to encapsulate the address would be a good step. I don't know how feasible that is, though.

**Comment by psafont** [comment]
I believe this won't be merged as-is. It's better to open a new one once the ipaddr library is used. Note that the ipaddr version used has bugs with certain ranges of IPv6 addresses. I'm working to include a fixed version.

**Comment by benjamreis** [comment]
New version using the `Ipaddr` lib as asked here: https://github.com/xapi-project/xen-api/pull/5463

**Pull request closed without merging**
