### PR TITLE
CP-12243: Use libpci bindings instead of lspci and Pci_db

### PR DESCRIPTION
**Pull request by simonjbeaumont**
Until now we have relied on forking `lspci` to determine the PCI devices on the host and parsed the result. We have also resorted to a hand-rolled library for parsing the `pci.ids` database to lookup the names of PCI class, vendor and device identifiers.

This patch makes use of `libpci` to address these problems as provided by the wrapper library `ocaml-pci`.

I have dev-tested this patch on a host that supports vGPU and I cannot see any functional regressions.

We do however depend on NVIDIA putting their supplementary `pci.ids` file that is shipped as part of their `NVIDIA-GRID-vGPU-XenServer` in `/usr/share/hwdata/pci.ids.d/` so that `libpci` name lookups will work on devices that are not in the upstream `pci.ids` database. I have tested that this will be adequate by creating a symlink after installing the RPM:

    # ls -lF /usr/share/hwdata/pci.ids.d/nvidia-vgx.ids
    lrwxrwxrwx 1 root root 25 May 14 14:21 /usr/share/hwdata/pci.ids.d/nvidia-vgx.ids -> /usr/share/nvidia/pci.ids

Without this, some of the vGPU types have names like "Device 113b" instead of "NVIDIA GRID 160Q". With the symlink the correct names are restored.

We have a ticket with NVIDIA to track this packaging change which they have agreed to.

### CODE REVIEW

**Comment by simonjbeaumont** [comment]
:warning: Not OK to merge until we have added the symlink workaround to XenRT in lieu of NVIDIA's packaging fix.

**Comment by johnelse** [comment]
Looks good - ready to go in once travis is happy.

**Comment by simonjbeaumont** [comment]
This should pass on travis now because https://github.com/ocaml/opam-repository/pull/4124 has been merged.

**Comment by simonjbeaumont** [comment]
Blocked on a XenRT work around for the NVIDIA packaging issue.

**Comment by simonjbeaumont** [comment]
Added a patch to create the symlink in lieu of the NVIDIA packaging fix. Also created a CP ticket to remove it (CP-12483)

**Pull request merged**
