### PR TITLE
README: add build, coverage, LoC badges

### PR DESCRIPTION
**Pull request by gaborigloi**
Feel free to add or remove badges from this PR.

### CODE REVIEW

**Comment by gaborigloi** [comment]
It seems there is some random noise in the coverage results ⤴. Probably our tests are a bit random?

**Comment by gaborigloi** [comment]
If this random noise keeps happening in our PRs, I will adjust the "Coverage Decrease Threshold for failure" in Coveralls accordingly, to filter out this noise.

**Comment by mseri** [comment]
Yes, there are a few test employing random generation of data. Maybe we should get some reasonably big threshold there to avoid these failures. I don't know how much, but I guess 0.5% or 1% is much more than enough

**Comment by gaborigloi** [comment]
I've set it to 0.02%, as the other PR consistently had a 0.01% decrease, and we can increase it later if it's too low. 1% seems to be too much, as 1% of 100K is 1000 untested lines of code (although [this count](https://github.com/gaborigloi/xen-api/tree/add_badges) includes non-ocaml code as well)

**Comment by mseri** [comment]
I have a PR introducing `pylint` for our codebase as well... however it is far from being ready

**Pull request merged**
