### PR TITLE
CA-248381 Bump datamodel version to 5.110 

### PR DESCRIPTION
**Pull request by lindig**
We had missed bumping the version of the datamodel earlier after introducing new fields to the data model - the last one occurring at https://github.com/xapi-project/xen-api/commit/d2cc298f882c51329f661bc55e9970097282fd39. This commit bumps the version from 5.109 to 5.110.

For the Falcon release a version of 5.112 is defined. We will have to bump to that version before release or modify this PR to reach 5.112 already.

For me the current Oasis files did not work and so I re-generated them for a separate commit.

### CODE REVIEW

**Comment by mseri** [comment]
I don't know the policy. I don't expect changes in the datamodel but one never knows. Also, I imagine that the Falcon release version can be changed if needed. I would leave it as you did, but maybe @jonludlam should have a say before merging.

Also, we need to remember to cherry pick these changes into the falcon branch

**Comment by lindig** [comment]
I was taking about this definition for Falcon: https://github.com/xapi-project/xen-api/blob/master/ocaml/idl/datamodel.ml#L87-L88

**Comment by kc284** [comment]
I admit to have bumped ```falcon_release_schema_minor_vsn``` instead of the ```schema_minor_vsn``` the last time I changed the datamodel. The policy is defined at http://xapi-project.github.io/devguide/howtos/add-field.html. So according to this document, is there a need to pre-define ```falcon_release_schema_minor_vsn```? (Which is where my confusion stemmed from). Shouldn't we only define it when the release is ready and set it to whatever ```schema_minor_vsn``` is at the time?

**Comment by robhoes** [comment]
The value `schema_minor_vsn` is what counts. The other ones (`*_release_schema_minor_vsn`) are essentially there just for documentation purposes, and we tend to define them _after_ the release.

**Comment by robhoes** [comment]
I see `let ely_release_schema_minor_vsn = 100` while `let schema_minor_vsn = 109`, which is wrong!

**Comment by robhoes** [comment]
Ely, on v1.14.7, actually has this (https://github.com/xapi-project/xen-api/blob/v1.14.7/ocaml/idl/datamodel.ml#L21):

  let schema_minor_vsn = 109

**Comment by robhoes** [comment]
So let's use this PR to update `ely_release_schema_minor_vsn` to `108`, and set `schema_minor_vsn` and `falcon_release_schema_vsn` to `120` (leave a gap between the releases, in case we need a bump for an Ely fix).

**Comment by lindig** [comment]
I suggest:

* We set `ely_release_schema_minor_vsn = 108`
* We remove the definition for the Falcon version for now
* We keep the new version 5.110 for the schema

**Comment by robhoes** [comment]
I don't expect any new fields in falcon anymore, so we could leave that definition in there.

**Comment by lindig** [comment]
I'll update the PR as you suggested.

**Comment by robhoes** [comment]
Looks like we don't need to add the oasis output (the spec file is meant to call `oasis setup`).

**Comment by lindig** [comment]
But then we should remove it and not have broken output in the repository.

**Comment by lindig** [comment]
What about these lines? Should this point to Falcon as well?  
```
(* the schema vsn of the last release: used to determine whether we can upgrade or not.. *)
let last_release_schema_major_vsn = ely_release_schema_major_vsn
let last_release_schema_minor_vsn = ely_release_schema_minor_vsn
```
https://github.com/xapi-project/xen-api/blob/master/ocaml/idl/datamodel.ml#L91-L92

**Comment by robhoes** [comment]
> But then we should remove it and not have broken output in the repository.

Is it really in the repository?

> What about these lines? Should this point to Falcon as well?

Yes, let's update those as well. I don't think those are actually used at all anymore, however. We can check, and probably remove this later.

**Pull request merged**
