### PR TITLE
Bumped API version to 2.7.

### PR DESCRIPTION
**Pull request by kc284**
Signed-off-by: Konstantina Chremmou <konstantina.chremmou@citrix.com>

### CODE REVIEW

**Comment by thomassa** [comment]
The travis build failure says
```
File "storage_impl.ml", line 909, characters 19-24:
Error: This expression has type string but an expression was expected of type
         (string * string) list
```

**Comment by mseri** [comment]
No, the travis build uses the latest rpms, so whatever changed signature will make the build fail. We should find a way to have reliable builds on the various branches

**Comment by kc284** [comment]
This can be merged once https://github.com/xenserver/xenadmin/pull/1530 goes in.

**Comment by kc284** [comment]
https://github.com/xenserver/xenadmin/pull/1530 has been merged.

**Pull request merged**
