### PR TITLE
CP-18710 - Eliminate spurious stack traces from log files

### PR DESCRIPTION
**Pull request by mseri**
Update openvswitch configuration only after the `xenbr*` bridges are configured, avoiding many backtraces.

Use `xe` filtering capabilities to avoid an innocuous backtrace in the logs.

### CODE REVIEW

**Comment by lindig** [comment]
Looks good to me but I'd like a domain expert's opinion, too.

**Comment by robhoes** [comment]
Some minor comments:

- The first patches changes the "creating networks" line for no reason.
- Please add "Signed-off-by" lines to the commit messages of both patches.

**Comment by robhoes** [comment]
Oh, and "eliminate"...

**Comment by robhoes** [comment]
Looks good, thanks!

**Pull request merged**
