### PR TITLE
Fix @stresstest failure

### PR DESCRIPTION
**Pull request by edwintorok**
Noticed by @psafont in https://github.com/xapi-project/xen-api/actions/runs/9901545401/job/27354091939#step:7:149.

The bug is in the test code, I misinterpreted what the meaning of the timeout parameter in `Buf_io.really_input` means, it is not the overall timeout, but the timeout for each individual read call.
So if the other end decides to send 1 byte at a time, then the overall timeout will be number of bytes * timeout.

This may be an unintentional bug in `really_input`, however it is unknown whether any callers rely on the current semantics or not, so fix the test instead to check for the actual behaviour of `really_input`.

There is also a bug in the use of `setsockopt`. It gets converted to a `struct timeval`, and the microseconds value truncated.
So if we end up asking for a too small timeout (which as a result of the above change we might!) then that would get truncated to 0 and instead we'd hang indefinetely, because 0 means "no timeout".

### CODE REVIEW

**Review by psafont — APPROVED** [review]

**Comment by edwintorok** [comment]
Marking as draft there is another failure in the CI (which didn't happen locally):
```
  --- Failure --------------------------------------------------------------------
  
  Test Dune__exe__Bufio_test.test_buf_io failed (2 shrink steps):
  
  (delay_read: duration: 152ns;every_bytes: 1; delay_write: duration: 152ns;every_bytes: 1; size: 655363; file_kind: "socket", 0.001)
  
  +++ Messages ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  
  Messages for test Dune__exe__Bufio_test.test_buf_io:
  
  Timed out earlier than requested: 289μs < 1ms
  ================================================================================
  failure (1 tests failed, 0 tests errored, ran 1 tests)
```

**Comment by edwintorok** [comment]
Looks like the generated delay is too small, we can't perform delays <1us.
I'll update the generator and add a constraint.

**Review by Vincent-lau — APPROVED** [review]

**Comment by edwintorok** [comment]
```
--- Failure --------------------------------------------------------------------

Test Dune__exe__Bufio_test.test_buf_io failed (17 shrink steps):

(delay_read: duration: 4.28μs;every_bytes: 7; delay_write: duration: 4.28μs;every_bytes: 7; size: 655363; file_kind: "socket", 0.1)

+++ Messages ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Messages for test Dune__exe__Bufio_test.test_buf_io:
```

Still fails, I wonder whether this is because this is the old code using `gettimeofday` and `select`.

**Comment by edwintorok** [comment]
10 iterations of stresstest in `ocaml/libs` has passed now:
```
for i in $(seq 1 10); do dune build @stresstest --profile=release --no-buffer -j 8 --force; done
```

**Pull request merged**
