### PR TITLE
Facilities to support multiple HA cluster stacks

### PR DESCRIPTION
**Pull request by robhoes**
See the design at http://xapi-project.github.io/xapi/design/multiple-cluster-managers.html.

Note: this must go in together with a change to install xhad's scripts under the new cluster-stack-root.

### CODE REVIEW

**Comment by robhoes** [comment]
Travis failed:
`- configure: unknown option `--xhadir'.`
That needs to change to `--cluster-stack-root`.

**Comment by robhoes** [comment]
I've tried to fix this by patching the `opam` file.

**Comment by djs55** [comment]
Looks ok to me! Once there's a way for SMAPIv3 to tell you a cluster stack constraint, we should make sure to test this end-to-end.

**Comment by johnelse** [comment]
@xen-git test this please

**Pull request merged**
