### PR TITLE
CP-49900: Removed templates folder from python3/

### PR DESCRIPTION
**Pull request by ashwin9390**
Main ticket CP-49100 :Move python3 scripts from scripts directory to python3 directory.

Sub task CP-49900
-This PR makes changes to https://github.com/xapi-project/xen-api/pull/5758
-It was decided we can remove templates directory as it is not used in Dom0
- Removed templates debian and debug from Makefile
-  ocaml Smoketest did not throw any error. 

 Signed-off-by: Ashwinh <ashwin.h@cloud.com>

### CODE REVIEW

**Comment by psafont** [comment]
This must have a corresponding xapi.spec change for the feature/py3 branch @liulinC

**Comment by liulinC** [comment]
> This must have a corresponding xapi.spec change for the feature/py3 branch @liulinC

yes, 
@ashwin9390 you need to create `feature/py2` in xapi.spec repo, from staging branch, to make sure the rpm build does not break.  We need to run enough XenRT test before feature merge back to master.  (and remove this file from spec file).

This PR looks good to me if we are sure the removed python scripts no longer necessary.

**Review by liulinC — APPROVED** [review]
This PR looks good by itself,

@stephenchengCloud Please prepare a feature branch with this update so @ashwin9390  can do rpm/XenRT test if he want. (looks low risk as not used at all)

**Comment by stephenchengCloud** [comment]
> This PR looks good by itself,
> 
> @stephenchengCloud Please prepare a feature branch with this update so @ashwin9390 can do rpm/XenRT test if he want. (looks low risk as not used at all)

You mean a feature branch for xapi.spec repo? Sure, will do it.

**Review by stephenchengCloud — APPROVED** [review]

**Review by bernhardkaindl — APPROVED** [review]
Based on the comments by Lin and Stephen, I understand the following from what Lin wrote:

The team is now aware that when merging it, `xapi.spec` will be updated as well. Also, complete XenRT testing will be done as well when all changes need to be tested for the merge of the feature branch.

On this ground, I think I can also add my approval to the PR.

**Pull request merged**
