### PR TITLE
CA-189154: Check featureset when selecting a host for a VM

### PR DESCRIPTION
**Pull request by euanh**
Signed-off-by: Euan Harris <euan.harris@citrix.com>

### CODE REVIEW

**Comment by robhoes** [comment]
Would this not break VM.start_on?

**Comment by robhoes** [comment]
I think it also doesn't do the check for VM.resume_on?

**Comment by robhoes** [comment]
I just discussed this with Euan:
* VM.start and VM.resume_on are fine.
* The assertion can go into `vm_can_run_on_host`.

**Comment by euanh** [comment]
`VM.start_on` is ok because `Cpuid_helpers.assert_vm_is_compatible` is a no-op if the VM is halted:
   https://github.com/xapi-project/xen-api/blob/c2f7a08973b37e4f5f031dab59e012556266f03b/ocaml/xapi/cpuid_helpers.ml#L71

`VM.resume_on` is ok because VM.resume itself calls `Cpuid_helpers.assert_vm_is_compatible` and won't let you resume on an incompatible host unless you force it:
   https://github.com/xapi-project/xen-api/blob/4513459a8be7fbfb7fbcd2faf486229dc3430245/ocaml/xapi/xapi_vm.ml#L350

Since vm_can_run_on_host is only used in this module, I think it's fine to put the calll to `Cpuid_helpers.assert_vm_is_compatible` in there and get rid of the ugly wrapper.

**Comment by robhoes** [comment]
:shipit:

**Pull request merged**
