### PR TITLE
CP-15358: support external ip address setting

### PR DESCRIPTION
**Pull request by Chunjie**
1. configure-ip(v4,v6)
      2. static-ip-setting feature flag
      3. bash completion

Signed-off-by: Chunjie Zhu <chunjie.zhu@citrix.com>

### CODE REVIEW

**Comment by xen-git** [comment]
Can one of the admins verify this patch for testing?

**Comment by thomassa** [comment]
@xen-git Test this please

**Comment by robhoes** [comment]
Replaces #2593.

**Comment by Chunjie** [comment]
add a patch to remove unnecessary diff

**Comment by robhoes** [comment]
I'm going to close this in favour of #2605, in which I have fixed up a few more things (mainly in xapi_vif.ml), as said in #2593.

**Pull request closed without merging**
