### PR TITLE
maintenance: update opam metadata from xs-opam

### PR DESCRIPTION
**Pull request by psafont**
In particular fixes a lot of errors caused by the incorrect format of the 'dev' pseudo-urls

### CODE REVIEW

**Comment by edwintorok** [comment]
there is a problem with 'io-page' now.

**Comment by psafont** [comment]
Yes, I need to change the io-page dependency

**Comment by robhoes** [comment]
Does this still need work?

**Comment by psafont** [comment]
I force-pushed the change, all the work is done and works

**Review by lindig — APPROVED** [review]

**Review by robhoes — APPROVED** [review]

**Pull request merged**
