### PR TITLE
CP-26685 Adapt network interface when porting to ppx

### PR DESCRIPTION
**Pull request by krizex**
1. update idl call
2. update exception

Signed-off-by: Yang Qian <yang.qian@citrix.com>

This PR should goes in with https://github.com/xapi-project/xcp-idl/pull/189

### CODE REVIEW

**Comment by minishrink** [comment]
Could you rename this PR since it doesn't contain changes to `xcp-idl`, but instead updates Xapi with your `xcp-idl` changes?

**Comment by krizex** [comment]
Update the PR title and commit message accordingly.

**Comment by krizex** [comment]
Ring3 BVT passed in job 79965
Ring3 BST passed job 79962
Network regression passed job 80071 except infrastructure issues of bond cases on BOURNE04, I have spoke it to Rama and got confirmed, the ticket has been assigned to him.

**Comment by mseri** [comment]
I understand that the implementation does not support named arguments, but I thought that the interface does, am I wrong @jonludlam. Can we keep the named arguments here?

**Comment by jonludlam** [comment]
No, I'm afraid the named parameters disappear from both client functions and server implementations. I think the only way to bring them back is to do code-gen ctypes-style, and I'd quite like to avoid that.

**Comment by mseri** [comment]
I am going to do a manual merge to master

**Pull request closed without merging**
