### PR TITLE
CP-15745: Use xenserver-build-env for travis build

### PR DESCRIPTION
**Pull request by johnelse**

### CODE REVIEW

**Comment by johnelse** [comment]
Travis is failing because the external repo is returning 403. Once that is fixed, this should work.

**Comment by simonjbeaumont** [comment]
Cool. This looks sane. Although it's blocked behind the yum repo 403s.

**Comment by johnelse** [comment]
Don't merge this yet - I'd like to genericise these scripts and add them to https://github.com/xenserver/xenserver-build-env

**Comment by djs55** [comment]
How are you finding docker on travis? I've not gotten around to trying it myself.

**Comment by johnelse** [comment]
Don't merge yet - I'd like to genericise some of this new code and add it to xenserver-build-env

@djs55 it works well actually - the xenserver-build-env CI has been using it for a while now.

**Comment by johnelse** [comment]
Depends on https://github.com/xenserver/xenserver-build-env/pull/55

**Comment by johnelse** [comment]
Updated - config is now all via `.travis.yml`.

**Comment by simonjbeaumont** [comment]
This looks good now! Expecting a :white_check_mark: from travis now that xenserver/xenserver-build-env#55 has been merged.

**Comment by simonjbeaumont** [comment]
Not waiting for @xen-git since this change is only to the travis.yml.

**Pull request merged**
