### PR TITLE
Windows PV auto-update feature support

### PR DESCRIPTION
**Pull request by cheng--zhang**
This pull request include three part of code change:

1. Add VHP for xenserver
2. Add flag VM.platform.pci_pv and its default value
3. Add pci_pv check for VHP

### CODE REVIEW

**Comment by cheng--zhang** [comment]
Hi @simonjbeaumont 
Could you please help to review the code?
Some of the code are reviewed here: https://github.com/xapi-project/xen-api/pull/2180
I made another commit which based on https://github.com/xapi-project/xen-api/pull/2180. So I compose all the code together. 
Thank you so much for your great support.

**Comment by simonjbeaumont** [comment]
@xen-git: retest this please.

**Comment by simonjbeaumont** [comment]
Hi Cheng, I've added some comments on the commits that are the extras to #2180. One of them looks like it needs to be removed. I'm concerned by some of (what look like) conflicting comments in the final commit.

Also, the build on xen-git failed. I've kicked it off again because the logs have expired but if it's failing then we'll need to fix it up.

**Comment by cheng--zhang** [comment]
Hi @simonjbeaumont 
Thank you so much for your great help. I already removed the empty commit. Seems this time the merge build test passed.
Please help to check it again.

Why I create pull request for all the code is because we just waiting on the feature to be test. I know there is already a pull request on trunk which include a lot of my code pull request. But I still create this because we want to integrate the code in early stage, so QA team can have something to test.

Thanks again for your great support.

**Comment by robhoes** [comment]
I've merged the original pull request to master just now (#2180). It seems that the new commits in this pull request are the 6th and the 9th.

**Comment by robhoes** [comment]
I discussed briefly with @thomassa and it seems that the current implementation using platform keys was chosen in order to start testing of this stuff soon. However, it may be decided that another approach is better, and the design may be revised. I'll merge this pull request, since it is for a feature branch, but would expect a new pull request for master at some point.

**Pull request merged**
