### PR TITLE
CA-172901: XenAPI.py, make SSL verification optional

### PR DESCRIPTION
**Pull request by mseri**
SSL verification is still enabled by default, but can be disabled by
developer for testing purposes by adding the optional parameter
`ignore_ssl` during the Session creation.

### CODE REVIEW

**Comment by mseri** [comment]
Although there are few `python 2.4` compatibility tricks in the code, 
the python SDK is not `python 2.4` compatible.

For example, the `except ... as` syntax used here is not supported by 2.4: https://github.com/xapi-project/xen-api/pull/2883/files#diff-54f2bd385e85ed6d1adfc9ed258719ffR182

I have a version of this file, requiring python's `six` package as a dependency, that is python 2.6+ and python 3+ compatible. If there is no objection, it would be worth cleaning up this script and having something working also with recent versions of python (and properly packaged using setuptools)

**Comment by kc284** [comment]
I think the 2.4 compatibility tricks are just older code that has not been updated because python 2.6+ still understands it; however, 3+ does not. I agree we should do further cleaning, but I think the trend should be towards newer rather than older versions.
I'd be interested in knowing what the others think on this too, because I'm not aware of an official statement (documentation) on what versions each module release is compatible with.

**Comment by mseri** [comment]
In view of today's discussions, I suggest that we review and merge this PR, and I open a new ticket to update to python 2.7 and 3+, and use a saner install way with setuptools.

**Comment by lindig** [comment]
I'd like that idea as it avoids having PRs open for a long time.

**Pull request merged**
