### PR TITLE
Update definitions of HTTP actions

### PR DESCRIPTION
**Pull request by robhoes**

### CODE REVIEW

**Comment by robhoes** [comment]
@kc284 This has some impact on the SDK:
* Some handler definitions are deleted.
* Additional parameters are added for SDK-exposed HTTP actions. Note that the added arguments are optional, but there is currently no way to express this. I also believe that the C# code generator doesn't use optional arguments, so these changes may impact the users of these bindings. Is that what we want?

**Comment by lippirk** [comment]
Can we also add the necessary files to be able to generate your HTTP endpoints document? (with `make doc` perhaps)

**Comment by robhoes** [comment]
> Can we also add the necessary files to be able to generate your HTTP endpoints document?

Yep, but I'd do that separately.

**Review by lippirk — APPROVED** [review]

**Comment by kc284** [comment]
The SDK code could be modified to generate optional arguments for the http actions, but if there is no way to tell them apart from the mandatory parameters, we'll resort to adding manually the old version of these methods as overloads.

**Comment by robhoes** [comment]
We can of course change the type in the datamodel to express more details about the args, such as optionality and possible values. Does C# have optional function args with defaults? Or do you need overloads?

We also have some that accept `uuid` as well as `ref`, but only one is required. I didn't even add those yet to avoid confusion, but I could add the additional one as optional.

**Comment by kc284** [comment]
Recent versions of C# understand optional arguments, but the SDK generator was written before that time, hence it generates method overloads instead, it will need some work to change it. However, this does not prevent you from defining the Ocaml parameters in any way you want. The option to use the opaque_ref instead of the uuid would be useful for the consumers of the SDK. Note though that there may be some calls where the parameter is called "uuid", when in reality this is an opaque_ref; it would be nice if the definition could hold additionally parameter decsription so it can be output in the generated code.

**Review by kc284 — APPROVED** [review]

**Review by lindig — APPROVED** [review]
Has this been ocamlformat'ed?

**Comment by robhoes** [comment]
OK thanks, let's put this in as it is now. Then I'll do a proposal for an extended type later.

**Comment by robhoes** [comment]
> Has this been ocamlformat'ed?

`ocaml/idl/datamodel*` has been excluded from the formatter.

**Pull request merged**
