### PR TITLE
CA-211264: Re-run chkconfig on upgrade to pickup ordering changes

### PR DESCRIPTION
**Pull request by simonjbeaumont**
Signed-off-by: Si Beaumont <simon.beaumont@citrix.com>

### CODE REVIEW

**Comment by robhoes** [comment]
Where does `$1` actually come from?

**Comment by euanh** [comment]
@robhoes: $1 is set by rpm: https://fedoraproject.org/wiki/Packaging:Scriptlets

**Comment by robhoes** [comment]
How about always doing `--del` and `--add`? `--del` seems to be idempotent.

**Comment by simonjbeaumont** [comment]
Agreed that we'd make this "most like the other spec files" (i.e. the ones found in xen-api-base/libs-specs) for now with the understanding that almost all of this boilerplate will be reduced to some simple RPM macros when we move to systemd.

**Comment by simonjbeaumont** [comment]
Travis :x: not to be concerning:
```
ocamlfind: Package `xapi-test-utils' not found
```
The yum repo on AWS hasn't been updated (/cc @jonludlam).

The internal CI worked :white_check_mark:

**Pull request merged**
