### PR TITLE
CA-270405: Can't set USB pass-through to disable

### PR DESCRIPTION
**Pull request by taoyongd**
1. No matter vusbs is [] nor not, we still need to
continue executing the set passthrough code.
2. List.hd vusbs is no need when match [vusb]

Signed-off-by: Taoyong Ding <taoyong.ding@citrix.com>

### CODE REVIEW

**Comment by mseri** [comment]
I don't understand how does this solve the issue of being unable to disable passthrough. It is still checking if there are vusbs attached and failing if there are, before trying to destroy them and then setting the enable/disable passthtrough

**Comment by taoyongd** [comment]
@mseri . When vusb is [], we still need to do following code. 
`List.iter (fun vusb -> Db.VUSB.destroy ~__context ~self:vusb) vusbs;		           
 debug "set passthrough_enabled %b." value;
The original one will not go through the code vusb is [].

**Comment by mseri** [comment]
Oh I see, it was the missing semicolon! Great, thanks

**Comment by robhoes** [comment]
Not sure about the missing semicolon. The problem was that the last couple of lines were part of the last case in the match. A `begin`/`end` around the match would have fixed it as well (in fact, there was an `end` already, but the `begin` was in the wrong place).

**Comment by mseri** [comment]
I disagree. If you test it with
```ocaml
let test lst = 
match lst with
| _ :: _ :: _ -> failwith "A"
| [] -> ()
| [a] -> if a then failwith "B";

Printf.printf "here!"
```

You have
```
- test []
;;
- : unit = ()
- test [true]
;;
Exception: Failure "B".
- test [false]
;;
here!- : unit = () 
```

**Comment by mseri** [comment]
Maybe it would have been more coherent to move the `begin` as you suggest. Do you think we should change it or it is fine as it is?

**Comment by robhoes** [comment]
Doesn't this prove that the print line is part of the `[a]` case?

**Comment by robhoes** [comment]
I wouldn't change it anymore.

**Comment by mseri** [comment]
It does indeed. It is clear if you try to move the `[] -> ()` as the final match expression. That would be a syntax error due to the missing semicolons 😄

**Comment by robhoes** [comment]
Well, sure @mseri... :)

**Pull request merged**
