### PR TITLE
Reorganise datamodel some more

### PR DESCRIPTION
**Pull request by jonludlam**
Now we can build without `ulimit -s unlimited` :-)

### CODE REVIEW

**Comment by mseri** [comment]
```
      ocamlc ocaml/idl/json_backend/gen_json.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /usr/bin/ocamlc.opt -w -40 -g -bin-annot -I /usr/lib/opamroot/system/lib/astring -I /usr/lib/opamroot/system/lib/base -I /usr/lib/opamroot/system/lib/base/caml -I /usr/lib/opamroot/system/lib/base/shadow_stdlib -I /usr/lib/opamroot/system/lib/base64 -I /usr/lib/opamroot/system/lib/biniou -I /usr/lib/opamroot/system/lib/bytes -I /usr/lib/opamroot/system/lib/cmdliner -I /usr/lib/opamroot/system/lib/cohttp -I /usr/lib/opamroot/system/lib/easy-format -I /usr/lib/opamroot/system/lib/fd-send-recv -I /usr/lib/opamroot/system/lib/fieldslib -I /usr/lib/opamroot/system/lib/forkexec -I /usr/lib/opamroot/system/lib/gzip -I /usr/lib/opamroot/system/lib/http-svr -I /usr/lib/opamroot/system/lib/message-switch-core -I /usr/lib/opamroot/system/lib/message-switch-unix -I /usr/lib/opamroot/system/lib/ocaml-compiler-libs/common -I /usr/lib/opamroot/system/lib/ocaml-compiler-libs/shadow -I /usr/lib/opamroot/system/lib/ocaml-migrate-parsetree -I /usr/lib/opamroot/system/lib/ppx_ast -I /usr/lib/opamroot/system/lib/ppx_core -I /usr/lib/opamroot/system/lib/ppx_derivers -I /usr/lib/opamroot/system/lib/ppx_deriving -I /usr/lib/opamroot/system/lib/ppx_deriving_rpc -I /usr/lib/opamroot/system/lib/ppx_driver -I /usr/lib/opamroot/system/lib/ppx_driver/print_diff -I /usr/lib/opamroot/system/lib/ppx_optcomp -I /usr/lib/opamroot/system/lib/ppx_sexp_conv -I /usr/lib/opamroot/system/lib/ppx_sexp_conv/expander -I /usr/lib/opamroot/system/lib/ppx_tools -I /usr/lib/opamroot/system/lib/ppx_traverse_builtins -I /usr/lib/opamroot/system/lib/ppx_type_conv -I /usr/lib/opamroot/system/lib/re -I /usr/lib/opamroot/system/lib/result -I /usr/lib/opamroot/system/lib/rpclib -I /usr/lib/opamroot/system/lib/rresult -I /usr/lib/opamroot/system/lib/sexplib -I /usr/lib/opamroot/system/lib/sexplib/0 -I /usr/lib/opamroot/system/lib/sexpr -I /usr/lib/opamroot/system/lib/sha -I /usr/lib/opamroot/system/lib/stdio -I /usr/lib/opamroot/system/lib/stringext -I /usr/lib/opamroot/system/lib/stunnel -I /usr/lib/opamroot/system/lib/uri -I /usr/lib/opamroot/system/lib/uuid -I /usr/lib/opamroot/system/lib/uuidm -I /usr/lib/opamroot/system/lib/xapi-backtrace -I /usr/lib/opamroot/system/lib/xapi-stdext-base64 -I /usr/lib/opamroot/system/lib/xapi-stdext-bigbuffer -I /usr/lib/opamroot/system/lib/xapi-stdext-date -I /usr/lib/opamroot/system/lib/xapi-stdext-encodings -I /usr/lib/opamroot/system/lib/xapi-stdext-monadic -I /usr/lib/opamroot/system/lib/xapi-stdext-pervasives -I /usr/lib/opamroot/system/lib/xapi-stdext-std -I /usr/lib/opamroot/system/lib/xapi-stdext-threads -I /usr/lib/opamroot/system/lib/xapi-stdext-unix -I /usr/lib/opamroot/system/lib/xcp -I /usr/lib/opamroot/system/lib/xcp-inventory -I /usr/lib/opamroot/system/lib/xml-light2 -I /usr/lib/opamroot/system/lib/xmlm -I /usr/lib/opamroot/system/lib/yojson -I /usr/lib64/ocaml -I /usr/lib64/ocaml/compiler-libs -I /usr/lib64/ocaml/threads -I ocaml/database -I ocaml/idl -I ocaml/xapi-consts -no-alias-deps -I ocaml/idl/json_backend -o ocaml/idl/json_backend/gen_json.cmo -c -impl ocaml/idl/json_backend/gen_json.ml)
File "ocaml/idl/json_backend/gen_json.ml", line 161, characters 21-39:
Error: Unbound value Datamodel._session
```

**Comment by robhoes** [comment]
Will the API bindings be happy with this?

**Comment by jonludlam** [comment]
I built the bindings locally - but I also built xapi locally, and still broke the json backend :-/

**Comment by robhoes** [comment]
Hmmm.... "Remove field_has_effect from VBD.mode in favour of explicit declaration of setter" seems to do "a little" more than just that 🙄

**Comment by jonludlam** [comment]
Ah, so it does. Must have forgotten to commit the previous change... :hammer:

**Pull request merged**
