### PR TITLE
Host.license_add and related

### PR DESCRIPTION
**Pull request by robhoes**
This is a forward port of https://github.com/xenserver/xen-api/pull/54, leaving out the patches that were already applied, plus the patches about the OEM keys.

### CODE REVIEW

**Comment by johnelse** [comment]
@xen-git test this please

**Comment by robhoes** [comment]
xen-git said:
```
09:49:02 cp: writing `/local/bigdisc/jenkins-builds/jenkins-xen-api-1710/trunk-ring3/obj/c/.chroot-dom0-installed.md5': No space left on device
```

**Comment by simonjbeaumont** [comment]
@xen-git: retest this please.

**Comment by robhoes** [comment]
:green_heart:

**Comment by robhoes** [comment]
I've rebased this, because there were conflicts due to recent changes in master.

**Comment by robhoes** [comment]
xen-git built OK, but:
```
15:10:02 + tests/test_thin_lvhd
15:10:18 ==> host1: Checking for updates to 'jonludlam/xs-trunk-ring3'
15:10:18     host1: Latest installed version: 0.0.109979
15:10:18     host1: Version constraints: 
15:10:18     host1: Provider: xenserver
15:10:23 ==> host1: Updating 'jonludlam/xs-trunk-ring3' with provider 'xenserver' from version
15:10:23 ==> host1: '0.0.109979' to '0.0.110009'...
15:10:24 ==> host1: Loading metadata for box 'https://vagrantcloud.com/jonludlam/xs-trunk-ring3'
15:10:26 ==> host1: Adding box 'jonludlam/xs-trunk-ring3' (v0.0.110009) for provider: xenserver
15:10:26     host1: Downloading: https://vagrantcloud.com/jonludlam/boxes/xs-trunk-ring3/versions/0.0.110009/providers/xenserver.box
15:10:27 
[K    host1: Progress: 0% (Rate: 0/s, Estimated time remaining: --:--:--)
[KAn error occurred while downloading the remote file. The error
15:10:27 message, if any, is reproduced below. Please fix this error and try
15:10:27 again.
15:10:27 
15:10:27 The requested URL returned error: 404 Not Found
```

**Pull request merged**
