### PR TITLE
API changes for reporting and modifying PGPU.dom0_access

### PR DESCRIPTION
**Pull request by johnelse**

### CODE REVIEW

**Comment by johnelse** [comment]
Good catch! I think this predates `rel_cream`.

**Comment by johnelse** [comment]
Updated with cream instead of creedence (as @thomassa pointed out was necessary) and rebased.

**Comment by johnelse** [comment]
Just realised that the API version should be bumped as well...

**Comment by johnelse** [comment]
@xen-git test this please

**Comment by johnelse** [comment]
Rebased.

**Comment by jonludlam** [comment]
Looks good to me!

**Pull request merged**
