### PR TITLE
CA-389496: Avoid conflicts in configuration for rotating xapi logs

### PR DESCRIPTION
**Pull request by psafont**
The custom logrotation sometimes conflicted with the normal one. Remove the former.

Install the xapi logrotate configuration has been moved to be managed as part of the normal logrotation, with the global settings removed.

Drafting as I'm creating the builds

### CODE REVIEW

**Comment by psafont** [comment]
@rosslagerwall you might want to review this

**Comment by psafont** [comment]
Manual testing shows that logrotation on size reached happens correctly, and no loss is observed. I'm double-checking the update case

**Comment by psafont** [comment]
I've tested the following update cases:
- On an unfixed system, got xensource.log to +101MiB; see how it gets stuck there
- Ran `/opt/xensource/libexec/xapi-logrotate.sh ` and saw xensource.log renamed to xensource.log.1, and xensource.log starts being written to.
- Updated to the new version; logrotation happens as expected when reaching 101MB
And
- On an unfixed system, got xensource.log to +101MiB; see how it gets stuck there
- Updated to the new version; logrotation doesn't happen. rsyslogd need to reopen the configuration files (e.g. `kill -HUP $(pidof rsyslogd)`)

**Comment by rosslagerwall** [comment]
```
    # Rotate when file exceeds this size, even if we rotated it today already.
    maxsize 100M
```

This should already be set in `/etc/logrotate.conf` so it is not necessary to specify it here.

**Comment by psafont** [comment]
> ```
>     # Rotate when file exceeds this size, even if we rotated it today already.
>     maxsize 100M
> ```
> 
> This should already be set in `/etc/logrotate.conf` so it is not necessary to specify it here.

The kill -HUP also seems suspect as well, but I'm seeing that in many  of the logrotate configuration files (with rsyslogd.pid, which doesn't exist)

**Review by robhoes — APPROVED** [review]

**Pull request merged**
