### PR TITLE
Add backtraces to import.ml

### PR DESCRIPTION
**Pull request by johnelse**

### CODE REVIEW

**Comment by johnelse** [comment]
Just building RPMs for now...

**Comment by johnelse** [comment]
Ran some SXM, DR and import/export tests against this and all is OK, so this is ready for review.

**Comment by johnelse** [comment]
From what I understand of the `Backtrace` library:

* `Backtrace.is_important e` is used when you want to catch `e` (a "nice" exception), associate the current backtrace with `e`, and then reraise e after doing some cleanup.
* `Backtrace.reraise old new` is used when you want to catch `old` (typically a non-useful exception like `Not_found`), and turn it into `new` (a more useful exception) while reassociating the old backtrace with the new exception.

**Comment by robhoes** [comment]
Ok, sounds good!
:shipit:

**Comment by johnelse** [comment]
:+1:

**Pull request merged**
