### PR TITLE
Add 'threads_per_core' in 'Host.cpu_info'

### PR DESCRIPTION
**Pull request by benjamreis**
Discussed here: https://github.com/xapi-project/xen-api/issues/5462

### CODE REVIEW

**Comment by robhoes** [comment]
@andyhhp I know you have ideas about exposing CPU topologies... does this proposal fit?

**Comment by andyhhp** [comment]
Right now it's going to give you some quite creative (mis)truths.  We have plans, but there's quite a lot of upstream Xen work required before we can provide good accurate information here.

@benjamreis What precisely are you looking for here?  I presume some kind of "is SMT activate or not?"

**Comment by olivierlambert** [comment]
For Windows server licenses or other Oracle-like commercial reasons, people need to have the number of real physical cores on a machine.

**Comment by benjamreis** [comment]
Thx for the answer Olivier.

Tested:
```
                              cpu_info (MRO): cpu_count: 1; socket_count: 1; threads_per_core: 1; vendor: GenuineIntel; speed: 1700.121; modelname: Intel(R) Xeon(R) CPU E5-2650L v2 @ 1.70GHz; family: 6; model: 62; stepping: 4; flags: fpu de tsc msr pae mce cx8 apic sep mca cmov pat clflush acpi mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc rep_good ...
```
and compared to:
```
[15:49 xcp-ng-fnownclp ~]# xl info threads_per_core
1
```

**Comment by andyhhp** [comment]
Right, but note how https://ark.intel.com/content/www/us/en/ark/products/75270.html is 10 cores and 20 threads.

**Comment by lindig** [comment]
I would be fine to merge this if we understand that these numbers don't mean much in a virtual environment.

**Comment by olivierlambert** [comment]
@lindig what do you mean exactly? it's just exposing something already exposed by `xl info`, we are not creating new data.

**Review by robhoes — APPROVED** [review]
I've talked to Andy about this. Generally speaking, there is a lot to improve in the way we expose CPU topology info. However, this is passing on data from Xen that fits within the context of what is already there. So it's fine to add it, if we acknowledge and accept its limitations.

**Comment by lindig** [comment]
I'm not saying you are inventing numbers but is the number XL presents even well defined? @andyhhp's comments suggests to me that what we think and what code using that number thinks it means could be different. And you are adding this because you want some code to use it, I assume.

**Review by lindig — APPROVED** [review]

**Pull request merged**
