### PR TITLE
Use cmdliner for command-line parsing and manpage generation

### PR DESCRIPTION
**Pull request by djs55**
Note this is a backwards-incompatible change to the command-line arguments.
Where an argument was previously '-foo' it will now be '--foo'. Where an
argument was a flag '-flag' it is now '--flag true'.

Signed-off-by: David Scott <dave.scott@citrix.com>

### CODE REVIEW

**Comment by euanh** [comment]
@djs55: Could you please rebase this pull request?  Also, is it possible to keep the command line flags as they were before, as @simonjbeaumont suggests above?

**Comment by simonjbeaumont** [comment]
Just had a look over my comment again. Looks like this is a consequence of here:
https://github.com/xapi-project/xcp-idl/blob/2e075427187402782173e12cb17a6e25501468d0/lib/xcp_service.ml#L342

This enables the `Xcp_service.configure_common` call to "just work" with old and new. I still think it's a little strange to have to pass a boolean argument on a command line and Cmdliner is capable of defining `flag`s... from the docs of Cmdliner.Arg:

> `val flag : info -> bool t`
> 
> flag i is a bool argument defined by an optional flag that may appear at most once on the command line under one of the names specified by i. The argument holds true if the flag is present on the command line and false otherwise.

**Comment by djs55** [comment]
Yeah, I agree that if it can be done with more conventional use of cmdliner flags then that's better than passing the boolean argument. I'll take a look when I have a suitably-sized chunk of time.

**Comment by euanh** [comment]
At our review today we agreed to close pull requests which need to be rebased and appear to be languishing.  Please reopen if you find time to do the rebase.

**Pull request closed without merging**
