### PR TITLE
Add build shortcut for VS Code

### PR DESCRIPTION
**Pull request by Frezzle**
Press Ctrl+Shift+B to `make test` from the editor terminal!

Signed-off-by: Frederico Mazzone <frederico.mazzone@citrix.com>

### CODE REVIEW

**Comment by kc284** [comment]
I don't think we should take this change in. It is useful for people that use vscode, but they are only a fraction of the developers working in this repo. In general we should avoid adding to source control stuff that is IDE or environment specific, unless it is the norm for development in a repo (for example VisualStudio specifics in https://github.com/xenserver/xenadmin). Otherwise, we have to start adding metadata files for all possible editors and IDEs, which I think pollutes the repo unnecessarily.

**Comment by kc284** [comment]
Alternatively, we could add this on a plugin/snippets wiki page.

**Comment by jonludlam** [comment]
I don't think it gets in the way particularly.

**Comment by Frezzle** [comment]
@kc284 i see what you mean, but i see it as adding value to the VS Code users at little/no cost to everyone else - what's one little file compared to saving seconds and improving the workflow for some of us? :slightly_smiling_face: it can always be removed later if these types of files start polluting the repo?

**Comment by Frezzle** [comment]
@kc284 what do you mean by the plugins/snippets approach?

**Comment by kc284** [comment]
@Frezzle I see your point, it's just that I wouldn't like to see the repos getting in a state of certain Java repos I've seen which contain more metadata files for all the different Java IDEs existing than code files. Regarding the snippets, I was suggesting attaching this and other files on a wiki page, from where people can download them and add them to their repo depending on what they use. Or perhaps you could add them to the dev-vm repo.

**Comment by Frezzle** [comment]
@kc284 oh i see; at that point there is no time-saving benefit anymore having to copy that every time i clone a repo :/ but in terms of dev-vm it would be nice to have it as the default in the editor to `make` on `Ctrl+Shift+B` and `make test` on `Ctrl+Shift+T`, etc, or something similar. i'll see if there is a way to do this.. @jonludlam do you know if this can be done?

**Comment by jonludlam** [comment]
OCaml doesn't currently suffer from the Java problem of having a vast number of editors - and most of the current crop don't store config info in repositories like this, so I don't forsee us having the problem that @kc284 is concerned about. Having said that, I'm not totally unsympathetic to the argument. 

How about we merge this as is, but keep an eye on https://github.com/Microsoft/vscode/issues/1435 so we can switch to a global config if vscode fixes that issue?

**Comment by lindig** [comment]
I'm fine with merging and trying this.

**Pull request merged**
