### PR TITLE
CA-229028: Check VDI size is valid in vdi-import

### PR DESCRIPTION
**Pull request by Frezzle**
Signed-off-by: Frederico Mazzone <frederico.mazzone@citrix.com>

### CODE REVIEW

**Comment by jonludlam** [comment]
Int64.div is your friend!

**Comment by Frezzle** [comment]
@jonludlam updated with Int64.rem

**Comment by Frezzle** [comment]
Decided with @jonludlam that these changes are sufficient for improving the error message for this bug, but the error handling in this module overall needs some work (e.g. more specific errors rather than all internal errors, and more) and so that will be done separately.

**Comment by robhoes** [comment]
Note: this was CA-229038, not CA-229028...

**Pull request merged**
