### PR TITLE
CCM backport

### PR DESCRIPTION
**Pull request by xiewei20082008**
The original commits are:

cda2ac696 2018-09-05 CA-296204: Reduce stunnel RSA key length to 2048                  Wei Xie     
6a82382f6 2018-09-05 CA-295828: set 'fips = no' for both ssl-legacy mode and non-leg.. Wei Xie     
392b232e4 2018-09-05 CP-29015: Set correct ciphers for stunnel server                  Wei Xie     
ae892fb8e 2018-09-05 CA-291569: Change config for stunnel                              Wei Xie

### CODE REVIEW

**Comment by taoyongd** [comment]
Yes. The target branch is right. Thanks. @cheng-z

**Comment by cheng-z** [comment]
@taoyongd may need to create the release branch for havana.

**Comment by lindig** [comment]
Is Havana based on Honolulu? If so, using `1.14-lcm` is fine.

**Comment by krizex** [comment]
@lindig So when releasing Havana we will add a tag on 1.14-lcm rather than checkout a new branch?

**Comment by lindig** [comment]
We are at these versions:

```
origin/release/honolulu/lcm   SPECS/xapi.spec                             Version   1.14.39
origin/release/inverness/lcm  SPECS/xapi.spec                             Version   1.60.2
origin/release/jura/lcm       SPECS/xapi.spec                             Version   1.60.11
origin/release/kolkata/lcm    SPECS/xapi.spec                             Version   1.90.6
origin/release/lima/master    SPECS/xapi.spec                             Version   1.110.1
origin/release/havana/master  SPECS/xapi.spec                             Version   1.14.39
```

Thinking about this some more, I think we probably should create a new branch when we release Havana to avoid that `1.14-lcm` no longer can be used for Honolulu. The new versioning scheme would have to use 4 numbers: `1.14.39.x`. I'll raise a discussion.

**Comment by lindig** [comment]
The original commits are:

```
cda2ac696 2018-09-05 CA-296204: Reduce stunnel RSA key length to 2048                  Wei Xie     
6a82382f6 2018-09-05 CA-295828: set 'fips = no' for both ssl-legacy mode and non-leg.. Wei Xie     
392b232e4 2018-09-05 CP-29015: Set correct ciphers for stunnel server                  Wei Xie     
ae892fb8e 2018-09-05 CA-291569: Change config for stunnel                              Wei Xie     
```

**Pull request merged**
