### PR TITLE
Merge `feature/vm-anti-affinity` to `master`

### PR DESCRIPTION
**Pull request by BengangY**
Merge `feature/vm-anti-affinity` to `master`

### CODE REVIEW

**Comment by gangj** [comment]
The latest commit in the source branch: https://github.com/BengangY/xen-api/commit/daa687c36ec17a280e797f38ec867d57290f6584 is not in the [feature branch](https://github.com/xapi-project/xen-api/commits/feature/vm-anti-affinity/) yet, I think you should first have a PR to merge master into the feature branch.

**Comment by edwintorok** [comment]
The schema hash needs to be updated to fix the CI failure.

**Comment by gangj** [comment]
`$ git show 813b3b538
commit 813b3b5387f3c4776fc635e872e11d412801c750 (HEAD -> private/bengangy/vm-anti-affinity-to-master, bengang_github/private/bengangy/vm-anti-affinity-to-master)
Merge: 6cd2d82f2 f11657e4c
Author: Bengang Yuan <118869129+BengangY@users.noreply.github.com>
Date:   Tue Jul 2 18:11:42 2024 +0800

    Merge branch 'master' into feature/vm-anti-affinity

    Signed-off-by: Bengang Yuan <bengang.yuan@cloud.com>

diff --cc ocaml/idl/schematest.ml
index 1d48ba780,8ec116452..f2ee8fe4b
--- a/ocaml/idl/schematest.ml
+++ b/ocaml/idl/schematest.ml
@@@ -3,7 -3,7 +3,7 @@@ let hash x = Digest.string x |> Digest.
  (* BEWARE: if this changes, check that schema has been bumped accordingly in
     ocaml/idl/datamodel_common.ml, usually schema_minor_vsn *)

- let last_known_schema_hash = "92e75e20c5d0e319b0df73145be12b8e"
 -let last_known_schema_hash = "e34cd0d32cdcec7805c2d3ed4e4a0c25"
++let last_known_schema_hash = "efdb1c7e536362523741ccdb7f33f797"

  let current_schema_hash : string =
    let open Datamodel_types in
diff --cc quality-gate.sh
index 09cd3ef06,7bc8f35cf..b504ed69d
--- a/quality-gate.sh
+++ b/quality-gate.sh
@@@ -25,7 -25,7 +25,7 @@@ verify-cert ()
  }

  mli-files () {
-   N=516
 -  N=514
++  N=515
    # do not count ml files from the tests in ocaml/{tests/perftest/quicktest}
    MLIS=$(git ls-files -- '**/*.mli' | grep -vE "ocaml/tests|ocaml/perftest|ocaml/quicktest|ocaml/message-switch/core_test" | xargs -I {} sh -c "echo {} | cut -f 1 -d '.'" \;)
    MLS=$(git  ls-files -- '**/*.ml'  | grep -vE "ocaml/tests|ocaml/perftest|ocaml/quicktest|ocaml/message-switch/core_test" | xargs -I {} sh -c "echo {} | cut -f 1 -d '.'" \;)
[gangj@xenrt1015818055 scm]$`

@BengangY  I see ml files without mli increased from 514 to 515, there is a new file from feature/vm-anti-affinity added without a mli?

**Comment by BengangY** [comment]
> ` $ git show [813b3b5](https://github.com/xapi-project/xen-api/commit/813b3b5387f3c4776fc635e872e11d412801c750) commit [813b3b5](https://github.com/xapi-project/xen-api/commit/813b3b5387f3c4776fc635e872e11d412801c750) (HEAD -> private/bengangy/vm-anti-affinity-to-master, bengang_github/private/bengangy/vm-anti-affinity-to-master) Merge: [6cd2d82](https://github.com/xapi-project/xen-api/commit/6cd2d82f20753f2cb67dbe34b533f75329739a62) [f11657e](https://github.com/xapi-project/xen-api/commit/f11657e4c69cb1fc6ef03aeb921fcbf61a915180) Author: Bengang Yuan [118869129+BengangY@users.noreply.github.com](mailto:118869129+BengangY@users.noreply.github.com) Date: Tue Jul 2 18:11:42 2024 +0800
> 
> ```
> Merge branch 'master' into feature/vm-anti-affinity
> 
> Signed-off-by: Bengang Yuan <bengang.yuan@cloud.com>
> ```
> 
> diff --cc ocaml/idl/schematest.ml index 1d48ba780,8ec116452..f2ee8fe4b --- a/ocaml/idl/schematest.ml +++ b/ocaml/idl/schematest.ml @@@ -3,7 -3,7 +3,7 @@@ let hash x = Digest.string x |> Digest. (* BEWARE: if this changes, check that schema has been bumped accordingly in ocaml/idl/datamodel_common.ml, usually schema_minor_vsn *)
> 
> - let last_known_schema_hash = "92e75e20c5d0e319b0df73145be12b8e" -let last_known_schema_hash = "e34cd0d32cdcec7805c2d3ed4e4a0c25" ++let last_known_schema_hash = "efdb1c7e536362523741ccdb7f33f797"
> 
> let current_schema_hash : string = let open Datamodel_types in diff --cc quality-gate.sh index 09cd3ef06,7bc8f35cf..b504ed69d --- a/quality-gate.sh +++ b/quality-gate.sh @@@ -25,7 -25,7 +25,7 @@@ verify-cert () }
> 
> mli-files () { - N=516 - N=514 ++ N=515 # do not count ml files from the tests in ocaml/{tests/perftest/quicktest} MLIS=$(git ls-files -- '**/*.mli' | grep -vE "ocaml/tests|ocaml/perftest|ocaml/quicktest|ocaml/message-switch/core_test" | xargs -I {} sh -c "echo {} | cut -f 1 -d '.'" ;) MLS=$(git ls-files -- '**/*.ml' | grep -vE "ocaml/tests|ocaml/perftest|ocaml/quicktest|ocaml/message-switch/core_test" | xargs -I {} sh -c "echo {} | cut -f 1 -d '.'" ;) `
> 
> @BengangY I see ml files without mli increased from 514 to 515, there is a new file from feature/vm-anti-affinity added without a mli?

This feature added `datamodel_vm_group.ml` without an mli file. But seems there is no mil file for the most of other datamodel files.

**Review by gangj — APPROVED** [review]

**Review by minglumlu — APPROVED** [review]

**Pull request merged**
