### PR TITLE
CA-337546: resource leak handling

### PR DESCRIPTION
**Pull request by edwintorok**
Needs to be merged together with https://github.com/xapi-project/xen-api-libs-transitional/pull/78

### CODE REVIEW

**Comment by edwintorok** [comment]
I used a result type in the xapi-libs-transitional PR, I can try to see whether something like that would work here.

**Comment by edwintorok** [comment]
Dropped the fallback ref code, use result type instead.
Note that there are more Unix.pipe in xapi that could be converted, but I'll leave that for later, we may not have to convert them.

**Comment by lindig** [comment]
The DCO test is complaining - are commits signed off?

**Comment by edwintorok** [comment]
There was a fixup without a signoff, I've squashed it now

**Pull request merged**
