### PR TITLE
Further oasis cleanups

### PR DESCRIPTION
**Pull request by jonludlam**
If anyone is aware of any users of these files, please shout!

### CODE REVIEW

**Comment by mseri** [comment]
Spring cleaning?

**Comment by johnelse** [comment]
`mk/Makefile` is no more! 💥

**Comment by djs55** [comment]
That's quite a big diff..

**Comment by robhoes** [comment]
How about sacrificing xapi.spec.in while you're at it?

**Comment by jonludlam** [comment]
Ah nuts, missed xapi.spec.in! away it goes...

**Comment by jonludlam** [comment]
:boom:

**Comment by jonludlam** [comment]
Incidentally this breaks planex because it can't cope with binary diffs. The fix is to tag this c/s and to bump the version in the spec file.

**Pull request merged**
