### PR TITLE
CA-237993 xe vm-migrate: guess when user wants SXM

### PR DESCRIPTION
**Pull request by gaborigloi**
Chooses SXM if any SXM-specific arguments were supplied, and then warn
the user about any missing required parameters.

This could help users who accidentally left out any of the required
remote-master, remote-username, and remote-password fields. However,
this commit does not fix the general issue, that we do not detect and
warn the user about unrecognized superfluous command-line parameters at
the moment.

Old behavior:
```
[root@xrtuk-11-27 bin]# xe vm-migrate vm=71b5c809-282d-9191-1839-867e354dea7d host=xrtuk-11-28 vdi:fdsfdsa=fsa
Error: Unknown field 'vdi:fdsfdsa'
```

New behavior:
```
[root@xrtuk-11-27 bin]# xe vm-migrate vm=71b5c809-282d-9191-1839-867e354dea7d host=xrtuk-11-28 vdi:fdsfdsa=fsa
Performing a Storage XenMotion migration. Your VM's VDIs will be migrated with the VM.
Error: Storage XenMotion requires remote-master, remote-username, and remote-password to be specified. Please see 'xe help vm-migrate' for help.
```

However, the original error is returned for misspelled parameters:
```
[root@xrtuk-11-27 bin]# xe vm-migrate vm=71b5c809-282d-9191-1839-867e354dea7d host=xrtuk-11-28 vid:fdsfdsa=fsa
Error: Unknown field 'vid:fdsfdsa'
```

I'm still unsure about how the error message should be phrased and what it should say. Maybe it could also mention that only the destination host and VM should be specified for simple XenMotion.

Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>

### CODE REVIEW

**Comment by gaborigloi** [comment]
I could make the recognition of SXM parameters more accurate by splitting the keys at the `:` character, and the checking for exact equality instead of using `String.startswith` - don't know how much difference that makes.

**Comment by gaborigloi** [comment]
Also, maybe I could mention how to do simple XenMotion, not Storage XenMotion - maybe a user might want to do XenMotion, but accidentally specified an SXM-specific parameter instead. Or maybe the current error message is sufficient as it refers users to the help.

**Comment by gaborigloi** [comment]
And maybe we should display the error message about the missing parameters before "`Performing a Storage XenMotion migration. Your VM's VDIs will be migrated with the VM.`" to make it clear to the user that nothing has been done yet.

**Comment by lindig** [comment]
I like having this heuristic and would consider it good enough. Making it a lot better would require re-architecting the command line handling. The implementation looks fine to me.

**Comment by lindig** [comment]
I will merge this today.

**Comment by gaborigloi** [comment]
Oh OK, thanks for the review. (I think some of the decisions I made are questionable, as I explained above, but if other agree with the current version that's fine, but I'm happy to change it.) I think @jonludlam wanted to talk to me about this, so we should probably wait for him to give his opinion on this.

**Comment by jonludlam** [comment]
Forgot to add the 'approved' thing to my review. For the record, I approve of this PR.

**Pull request merged**
