### PR TITLE
CA-298373: Set ssl_legacy=true by default in Havana

### PR DESCRIPTION
**Pull request by xiewei20082008**
Job passed - id 2258127.

Signed-off-by: Wei Xie <wei.xie@citrix.com>

### CODE REVIEW

**Comment by cheng-z** [comment]
Small change. LGTM.

**Comment by cheng-z** [comment]
@lindig  can I ask your help to have a look also.
In havana, when backport master change, we need to do so to keep backward keep the same.

**Comment by cheng-z** [comment]
Hi @lindig 
It is not a backport, it is for havana only. Changed the commit message now.
Merge the code now as the code seems all good.

**Comment by xiewei20082008** [comment]
> This needs a better commit message. If this is a backport, what is the commit that is backported? If this required for some other backport, please explain it in the commit message.

This is not a backport - it is just a CA for Havana.

**Pull request merged**
