### PR TITLE
CP-12148: Inherit auto_update_drivers and hardware_platform_version on VM.clone

### PR DESCRIPTION
**Pull request by cheng--zhang**
Not using the default of "false", but use the value of the VM clone from.

Signed-off-by: chengz <cheng.zhang@citrix.com>

### CODE REVIEW

**Comment by simonjbeaumont** [comment]
@cheng--zhang: This pull request looks sane and has passed the jenkins build.

If you want to get Travis builds working on your branch you'll need to open a pull-request _from_ `master` _to_ your branch `trunk-car1755`. I recommend doing that :)

I'm being picky but the commit message could probably be condensed so that the main line contains all the useful information. Maybe use:

```
CP-12148: Inherit value of auto_update_drivers on VM.clone
```

**Comment by cheng--zhang** [comment]
Hi @simonjbeaumont ,
Thanks you so much for your suggestion. I will do that.

**Comment by thomassa** [comment]
Looks fine to me. I'm happy for it to go in when it passes the test.

**Comment by robhoes** [comment]
Looks good to me as well. I'll update the master pull request (#2222) with this as well.

**Pull request merged**
