### PR TITLE
doc: add a Memory documentation tag.

### PR DESCRIPTION
**Pull request by djs55**
Signed-off-by: David Scott <dave.scott@citrix.com>

### CODE REVIEW

**Comment by djs55** [comment]
Hmm
```
17:36:49 Checking environment variable 'build_system_component' exists... OK
17:36:49 Repo: xen-api
17:36:49 Github target branch: master
17:36:49 Pull request #: 2184
17:36:49 Ref: origin/pr/2184/merge
17:36:49 Commit: a8cd31d18e066b6020a826f4aefbef5b43a695ec
17:36:49 --------------------------------------------------------------------------------
17:36:49 Removing artifacts from previous job...
17:36:49 --------------------------------------------------------------------------------
17:36:49 Finding local branches for Github branch 'master' of 'git://github.com/xapi-project/xen-api.git'...
17:36:49 --------------------------------------------------------------------------------
17:36:49 Job failed ([Errno 2] No such file or directory: '/usr/groups/sources/hg/closed/branch-info.hg/sync-git/git-subscriptions'), attempting cleanup...
17:36:49 --------------------------------------------------------------------------------
17:36:49 Warning: Cleanup failed ([Errno 2] No such file or directory: '/usr/groups/sources/hg/closed/branch-info.hg/sync-git/git-subscriptions')
17:36:49 Build step 'Execute shell' marked build as failure
17:36:49 Archiving artifacts
17:36:49 Warning: you have no plugins providing access control for builds, so falling back to legacy behavior of permitting any downstream builds to be triggered
17:36:50 Finished: FAILURE
```

**Comment by djs55** [comment]
@xen-git retest this please

**Comment by simonjbeaumont** [comment]
@xen-git retest this please.

**Comment by robhoes** [comment]
Looks good, and xen-git is now happy as well... merging.

**Pull request merged**
