### PR TITLE
CAR-483: Remove Storage XenMotion Constraints

### PR DESCRIPTION
**Pull request by zli**
For review, don't merge yet until QA has set to integrate their part.

Passed Dundee Ring3 BST (testrun=36934) and Dundee SXM suite w/ updates (testrun=36917).

### CODE REVIEW

**Comment by jonludlam** [comment]
I think this might take some time to review :-)

**Comment by zli** [comment]
We've recently finished the QA review on the new testcases for this feature, so it's ready for integration as soon as we complete the Dev review here.

The pull req has also been updated regarding previous review comments and another small bug discovered lately.

**Comment by jonludlam** [comment]
Great, thanks @zli. I think the branch needs rebasing before we can merge though.

**Comment by jonludlam** [comment]
@zli - we're happy to merge this as soon as the outstanding comments are addressed and it's rebased to be mergable.

**Comment by zli** [comment]
Updated, ready for merge.

**Comment by zli** [comment]
Hmm, some of our XenRT DR testcases seem to depend on the automated behavior of ha_always_restart flag. I'll see whether I can find a different solution for this.

**Comment by zli** [comment]
Updated, should be ready for merge now.

**Pull request merged**
