### PR TITLE
CP-11788: XAPI - Integrate PBIS with XAPI auth plugin

### PR DESCRIPTION
**Pull request by phusl**
Signed-off-by: Phus Lu <phus.lu@citrix.com>

### CODE REVIEW

**Comment by xen-git** [comment]
Can one of the admins verify this patch for testing?

**Comment by johnelse** [comment]
This looks good to me, thanks.

n.b. [this comment](https://github.com/xapi-project/xen-api/pull/2230#issuecomment-103401804) about the travis build also applies here :)

**Comment by johnelse** [comment]
Ah, I wasn't suggesting merging the rebased branch in this PR - rather I was suggesting you b2bmerge trunk-ring3 -> trunk-car1747, and then rebase the top three commits in this pull request.

**Comment by johnelse** [comment]
@xen-git test this please

**Comment by johnelse** [comment]
@xen-git test this please

**Comment by johnelse** [comment]
@xen-git test this please

**Comment by johnelse** [comment]
Jenkins failed because some unrelated things still seem to be out of sync - I'll merge this and keep an eye on the resulting build.

**Comment by Zhengchai** [comment]
hi @johnelse: this one is built successful on trunk-car1747 staging branch, can we close this request please?
hi @phusl: could you please submit this pull request against to master branch (internal trunk-ring3) which is the path for us to merge to trunk. thanks.

**Comment by johnelse** [comment]
@Zhengchai I've already merged this pull request to the staging branch - is there anything else you'd like me to do?

**Pull request merged**
