### PR TITLE
CA-376144: handle host.apply_recommended_guidances first on pool coordinator

### PR DESCRIPTION
**Pull request by gangj**
1. First revert the commit for CP-42011 (Will redo in CP-42810 with new design).
2. Then merge in latest 'master', as the base of this feature branch is too old, otherwise koji build will fail.
3. Fix for CA-376144: Instead of proxying the request directly to pool member, first handler the
    request on pool coordinator, only proxy "VM.pool_migrate", "Host.reboot",
    "Host.restart_agent" to pool member.

### CODE REVIEW

**Comment by gangj** [comment]
DCO failed at 2 old commits:
Commit sha: [1f1bf9d](https://github.com/xapi-project/xen-api/pull/4976/commits/1f1bf9d0100128b552ab60405807b630c9174082), Author: Edwin Török, Committer: Pau Ruiz Safont; Expected "Edwin Török [edvin.torok@citrix.com](mailto:edvin.torok@citrix.com)", but got "Edwin Török [edwin.torok@cloud.com](mailto:edwin.torok@cloud.com)".
Commit sha: [1d27213](https://github.com/xapi-project/xen-api/pull/4976/commits/1d27213e79d220632902dc4f0e1236ec93606b0d), Author: Marcello Seri, Committer: GitHub; The sign-off is missing.

Would you please help to have a look how to pass the test?

**Comment by psafont** [comment]
This is taking in all the ezxenstore commits in the master branch into the feature branch. It would be better to have a PR to update the feature branch, and another independent one for the changes on top of the feature branch

**Comment by gangj** [comment]
Hi, I did not find how to review the merge commit d6d07e1 (which resolved the merging conflict), anyone knows is there a way to review the merge commit with github? If there is not a friendly way to review the merge commit, it is indeed impossible to review the change, even if the merging is raised with a individual PR I am afraid.

If you viewing the merging commit d6d07e1 (the 2nd commit in this PR) with other tools like "git log" or "gitk", you can see the change of this commit easily:
image

**Comment by minglumlu** [comment]
I think the changes to resolve the conflicts could be reviewed through `git show <merge commit>` in local command line. Not sure how this could be done in github web UI, in which, clicking the merge commit will show both  merged changes and resolving conflicts changes.

**Comment by lindig** [comment]
I think we agree that we should split this into an update of the feature branch and the new work. Closing this.

**Comment by gangj** [comment]
OK, hope split PRs would make the review easier.
Here is the first step: https://github.com/xapi-project/xen-api/pull/4983, please

**Pull request closed without merging**
