### PR TITLE
CA-228035: Export update-resync-host and deprecate refresh_pack_info

### PR DESCRIPTION
**Pull request by cheng-z**
Signed-off-by: Cheng Zhang <cheng.zhang@citrix.com>

### CODE REVIEW

**Comment by cheng-z** [comment]
Hi @lindig 
Actually, the implementation also changed.

**Comment by lindig** [comment]
Then explain the change in the commit message.

**Comment by cheng-z** [comment]
Hi @lindig 
Updated. Please help to review again.
Thanks.

**Comment by lindig** [comment]
This looks good on the code level. But how does this affect API-level compatibility with existing code given that the name of the API method is changed? I looked at the ticket but it's not clearly addressed there either.

**Comment by jonludlam** [comment]
1. We shouldn't remove API calls without deprecating them.
2. Keeping backwards compatibility is quite simple here.

Whilst this API call is _principally_ for the authors of supplemental packs, it might be used elsewhere and it's very little work to maintain compatibility. Therefore, I think we should deprecate the `patch` call, but change the implementation to call Pool_update.resync_host internally. Additionally, I think we should expose the API call Pool_update.resync host to the CLI, but we shouldn't arbitrarily change the name to  `host-refresh-update-info` - let's keep to the naming conventions of the rest of the Pool_update calls and call it: update-resync-host.

**Comment by cheng-z** [comment]
Hi @jonludlam 
Thanks for your comments. I updated the code based on you suggestion.
Please help to review the code again.

**Comment by jonludlam** [comment]
Hi @cheng-z - looking better now - but can we please use the lifecycle stuff to deprecate the API, which provides a bit more information.

**Comment by cheng-z** [comment]
Hi @jonludlam 
Updated, please help to review it again.
Thanks.

**Comment by jonludlam** [comment]
Thanks @cheng-z, looks good now.

**Pull request merged**
