### PR TITLE
Python3 fixes for storage api

### PR DESCRIPTION
**Pull request by ydirson**
This is a remake of https://github.com/xapi-project/xen-api/pull/5375

It limits messing with the builtins, by only defining on py3 the missing `long` and `unicode` as aliases where needed.

### CODE REVIEW

**Comment by psafont** [comment]
We're in a freeze period, and seeing how porting python code has been risky later, we've prepared a python3 branch where this can be safely merged to, I'm changing the base branch so it can be promptly merged.

**Comment by psafont** [comment]
Ah, this brings a lot of commits into the base branch because it's quite out-of date, let me open a PR to synchronize it

**Comment by ydirson** [comment]
Hm, I don't see why those 4 commits based on `v24.5.0`, included in `feature/py3`, is seen as merging 41 commits:

```
$ git log --oneline --no-decorate  origin/feature/py3..xcpng/storage-api-py3 
eb0210b70 Remove now-unused PY_TEST guard
9acbbdbcc Switch xapi-storage-scripts tests to python3
473d34b30 py3: make sure we are not using unicode type in python3
3791d8954 py3: make xapi-storage py3-compatible
```

**Comment by psafont** [comment]
This is because the PR was created before the feature/py3 branch included the commits

**Comment by psafont** [comment]
Codecov doesn't seem to make sense here, this PR did not change `scripts/ `.

I wonder whether coverage could be calculated when running `make test`, or `dune build @runtest-python`. Any ideas, @bernhardkaindl ?

**Review by psafont — APPROVED** [review]

**Review by bernhardkaindl — APPROVED** [review]
Because it's targeted at the branch `feature/py3`, I add an approval for testing it there!

Regarding coverage, I'm copying this here from #5511 (as Pau asked if it is possible to cover it):

> The `xapi-storage` Python script self-tests are started from
`ocaml/xapi-storage-script/main.ml`, and I do not understand it good enough to see how to make changes to invoke the `coverage` module instead of the script.
```
python -m coverage run scripts/examples/python/shell.py
```
Pau found:  https://coverage.readthedocs.io/en/7.4.4/subprocess.html
> Create or append to sitecustomize.py to add these lines:
```py
    import coverage
    coverage.process_startup()
```
Create a .pth file in your Python installation containing:
```py
    import coverage; coverage.process_startup()
```

**Comment by liulinC** [comment]
I am confused about the PR, 

8a72e0f1f7e11a8307274e455481d4a1825cdfd5 introduced a similar updates, and 1d05a6fbf914830a2ddd107f00464fa979f56584 revert it. 

Here the PR goes to feature branch, what is the plan? 
Also, has the PR been tested in a live XS, as we all know it is tricky to update py2 to py3, and just static checker are NOT good enough.

**Comment by psafont** [comment]
@liulinC can you have a look into how to progress this conversion to python 3? I believe it's worthwhile that the conversion team at the very least tracks progress of this in a ticket so it can be progressed however it's convenient.

**Comment by liulinC** [comment]
> this conversion to pyth
hi @psafont Sorry I just found message.
There are some commit to revert similar changes: 
- d98663c8df9d7517d540521e781dd9f5f68313f8
- 70515807d3a8d37e803581e3845dc35bf233e4bb

May I know the background of such reverts?

**Comment by psafont** [comment]
The previous changes was not a correct conversion and broke the product. This was detected in internal testing.

**Comment by liulinC** [comment]
> The previous changes was not a correct conversion and broke the product. This was detected in internal testing.

Thanks, merge now for further test.

**Pull request merged**
