### PR TITLE
CA-191248: Use vgpu_extra_args key from Xenops_interface

### PR DESCRIPTION
**Pull request by johnelse**

### CODE REVIEW

**Comment by johnelse** [comment]
Depends on https://github.com/xapi-project/xcp-idl/pull/106

**Comment by simonjbeaumont** [comment]
Looks sensible. Once https://github.com/xapi-project/xcp-idl/pull/106 is merged we can re-run the tests and see some :white_check_mark:s

**Comment by johnelse** [comment]
Closing this for now as it needs some rework.

**Comment by johnelse** [comment]
Reopened as https://github.com/xapi-project/xen-api/pull/2526

**Pull request closed without merging**
