### PR TITLE
SMAPIv1: support backtrace reporting via XenAPI-style errors

### PR DESCRIPTION
**Pull request by djs55**
This is an implementation of http://xapi-project.github.io/features/backtraces.html

This must be merged after: https://github.com/xapi-project/backtrace/pull/4

For reference here is an SM patch which consumes this interface: https://github.com/djs55/sm/tree/smapiv1-backtraces

### CODE REVIEW

**Comment by jonludlam** [comment]
@xen-git retest this please. Pretty please?

**Comment by simonjbeaumont** [comment]
@xen-git retest this please.

**Comment by euanh** [comment]
@xen-git retest this please.

**Comment by euanh** [comment]
@xen-git: Retest this please

**Comment by euanh** [comment]
@xen-git: Retest this please

**Comment by euanh** [comment]
@xen-git retest this please

**Comment by jonludlam** [comment]
@xen-git retest this please

**Comment by euanh** [comment]
@xen-git retest this please

**Comment by euanh** [comment]
This pull request seems to be stuck.   Please feel free to reopen it if you find time to work on it.

**Pull request closed without merging**
