### PR TITLE
Restored mustache in xapi-datamodel deps; fixed XSO-244/CA-168413.

### PR DESCRIPTION
**Pull request by kc284**

### CODE REVIEW

**Comment by lindig** [comment]
Travis fails because of Docker problems.

**Comment by lindig** [comment]
There is a merge conflict according to GitHub. Can you take a look at it?

**Comment by edwintorok** [comment]
+ make test
                         Done: 2943/3215 (jobs: 2)Fatal error: exception Unix.Unix_error(Unix.ENOENT, "open", "branding.mustache")
                                jsapi alias ocaml/doc/runtest (exit 2)
(cd _build/default/ocaml/doc && ./jsapi.exe)
                         make: *** [test] Error 1

**Comment by kc284** [comment]
Yes, I'm looking at it, travis has also failed.

**Pull request merged**
