### PR TITLE
[477 merge review draft] GFS2 feature branch

### PR DESCRIPTION
**Pull request by edwintorok**
This is meant for discussion at today's review meeting

### CODE REVIEW

**Comment by mseri** [comment]
😱 💥

**Comment by edwintorok** [comment]
Note: this includes https://github.com/xapi-project/xen-api/pull/3473 and https://github.com/xapi-project/xen-api/pull/3470. If we decide to keep those open I can remove them from this branch and fix the conflicts. (there are some commits touching some of the newly introduced functions there)

**Comment by mseri** [comment]
Yes please, let's merge those first

**Comment by mcintyre94** [comment]
^ Force push rebases on master, so no longer includes any commits merged in the previous PRs :)

**Comment by edwintorok** [comment]
Rebased once more due to merge conflict on xapi_pbd.ml.
Here is the diff compared (based on the review feedback of other PRs), to what was tested in the nightly:
```diff
diff --git a/ocaml/idl/datamodel_cluster.ml b/ocaml/idl/datamodel_cluster.ml
index ec2afa2..a86939e 100644
--- a/ocaml/idl/datamodel_cluster.ml
+++ b/ocaml/idl/datamodel_cluster.ml
@@ -15,7 +15,7 @@ let cluster_operation =
           "destroy", "completely destroying a cluster";
         ])
 
-let lifecycle = [Published, rel_kolkata, ""]
+let lifecycle = [Prototyped, rel_kolkata, ""]
 
 let timeout_params = [
     {param_type=Float; param_name="token_timeout"; param_doc="Corosync token timeout in seconds"; param_release=kolkata_release; param_default=Some(VFloat Constants.default_token_timeout_s)};
diff --git a/ocaml/idl/datamodel_cluster_host.ml b/ocaml/idl/datamodel_cluster_host.ml
index 2391a72..16589fb 100644
--- a/ocaml/idl/datamodel_cluster_host.ml
+++ b/ocaml/idl/datamodel_cluster_host.ml
@@ -11,7 +11,7 @@ let cluster_host_operation =
           "destroy", "completely destroying a cluster host";
         ])
 
-let lifecycle = [Published, rel_kolkata, ""]
+let lifecycle = [Prototyped, rel_kolkata, ""]
 
 let create = call
     ~name:"create"
diff --git a/ocaml/idl/datamodel_host.ml b/ocaml/idl/datamodel_host.ml
index d116782..ef129ef 100644
--- a/ocaml/idl/datamodel_host.ml
+++ b/ocaml/idl/datamodel_host.ml
@@ -1248,7 +1248,7 @@ let host_query_ha = call ~flags:[`Session]
 
   let set_iscsi_iqn = call
     ~name:"set_iscsi_iqn"
-    ~lifecycle:[Published, rel_jura, ""]
+    ~lifecycle:[Published, rel_kolkata, ""]
     ~doc:"Sets the initiator IQN for the host"
     ~params:[
       Ref _host, "host", "The host";
@@ -1437,7 +1437,7 @@ let host_query_ha = call ~flags:[`Session]
            field ~qualifier:DynamicRO ~default_value:(Some (VRef null_ref)) ~in_product_since:rel_ely ~ty:(Ref _vm) "control_domain" "The control domain (domain 0)";
            field ~qualifier:DynamicRO ~lifecycle:[Published, rel_ely, ""] ~ty:(Set (Ref _pool_update)) ~ignore_foreign_key:true "updates_requiring_reboot" "List of updates which require reboot";
            field ~qualifier:DynamicRO ~lifecycle:[Published, rel_falcon, ""] ~ty:(Set (Ref _feature)) "features" "List of features available on this host";
-         field ~qualifier:StaticRO ~lifecycle:[Published, rel_jura, ""] ~default_value:(Some (VString "")) ~ty:String "iscsi_iqn" "The initiator IQN for the host";
+           field ~qualifier:StaticRO ~lifecycle:[Published, rel_kolkata, ""] ~default_value:(Some (VString "")) ~ty:String "iscsi_iqn" "The initiator IQN for the host";
            field ~qualifier:StaticRO ~lifecycle:[Published, rel_kolkata, ""] ~default_value:(Some (VBool false)) ~ty:Bool "multipathing" "Specifies whether multipathing is enabled";
          ])
       ()
diff --git a/ocaml/idl/datamodel_types.ml b/ocaml/idl/datamodel_types.ml
index 528ee12..ebc2e9a 100644
--- a/ocaml/idl/datamodel_types.ml
+++ b/ocaml/idl/datamodel_types.ml
@@ -196,16 +196,15 @@ let release_order_full = [{
      branding   = "XenServer 7.3";
    }; {
      code_name     = Some rel_jura;
-     (** TODO replace with the actual version numbers when Jura is released *)
      version_major = 2;
-     version_minor = 7;
-     branding   = "Unreleased";
+     version_minor = 9;
+     branding   = "XenServer 7.4";
    }; {
      code_name     = Some rel_kolkata;
      version_major = 2;
      version_minor = 10;
      branding   = "Unreleased";
-   }
+   };
   ]
 (* When you add a new release, use the version number of the latest release,
    and "Unreleased" for the branding, until the actual values are finalised. *)
diff --git a/ocaml/tests/suite.ml b/ocaml/tests/suite.ml
index d74c54f..54ae467 100644
--- a/ocaml/tests/suite.ml
+++ b/ocaml/tests/suite.ml
@@ -17,11 +17,8 @@ open OUnit
 let base_suite =
   "base_suite" >:::
   [
-    Test_basic.test;
-    Test_agility.test;
     Test_helpers.test;
     Test_datamodel_utils.test;
-    Test_daemon_manager.test;
     Test_http.test;
     Test_pool_db_backup.test;
     Test_xapi_db_upgrade.test;
@@ -66,10 +63,7 @@ let base_suite =
     Test_network.test;
     Test_pusb.test;
     Test_host_helpers.test;
-    Test_cluster_host.test;
     Test_clustering_allowed_operations.test;
-    Test_cluster.test;
-    Test_host_helpers.test;
     Test_clustering.test;
   ]
 
diff --git a/ocaml/tests/suite_alcotest.ml b/ocaml/tests/suite_alcotest.ml
index 4b873e9..361b51d 100644
--- a/ocaml/tests/suite_alcotest.ml
+++ b/ocaml/tests/suite_alcotest.ml
@@ -11,5 +11,9 @@ let () =
     ; "Test_host", Test_host.test
     ; "Test_vdi_cbt", Test_vdi_cbt.test
     ; "Test_db_lowlevel", Test_db_lowlevel.test
-    ; "Test_vlan", Test_vlan.test;
+    ; "Test_vlan", Test_vlan.test
+    ; "Test_agility", Test_agility.test
+    ; "Test_daemon_manager", Test_daemon_manager.test
+    ; "Test_cluster", Test_cluster.test
+    ; "Test_cluster_host", Test_cluster_host.test
     ]
diff --git a/ocaml/tests/test_agility.ml b/ocaml/tests/test_agility.ml
index 64f702e..58d4cc2 100644
--- a/ocaml/tests/test_agility.ml
+++ b/ocaml/tests/test_agility.ml
@@ -12,7 +12,6 @@
  * GNU Lesser General Public License for more details.
  *)
 
-open OUnit
 open Test_common
 
 let test_vm_agility_with_vgpu () =
@@ -22,13 +21,11 @@ let test_vm_agility_with_vgpu () =
   Agility.vm_assert_agile ~__context ~self:vm;
   (* Create a VGPU - VM should no longer be agile. *)
   let (_: API.ref_VGPU) = make_vgpu ~__context ~vM:vm () in
-  assert_raises_api_error
-    ~args:[Ref.string_of vm]
-    Api_errors.vm_has_vgpu
+  Alcotest.check_raises "VM should no longer be agile"
+    Api_errors.(Server_error (vm_has_vgpu, [Ref.string_of vm]))
     (fun () -> Agility.vm_assert_agile ~__context ~self:vm)
 
 let test =
-  "test_agility" >:::
   [
-    "test_vm_agility_with_vgpu" >:: test_vm_agility_with_vgpu;
+    "test_vm_agility_with_vgpu", `Quick, test_vm_agility_with_vgpu;
   ]
diff --git a/ocaml/tests/test_basic.ml b/ocaml/tests/test_basic.ml
deleted file mode 100644
index 7f31db6..0000000
--- a/ocaml/tests/test_basic.ml
+++ /dev/null
@@ -1,45 +0,0 @@
-(*
- * Copyright (C) 2006-2012 Citrix Systems Inc.
- *
- * This program is free software; you can redistribute it and/or modify
- * it under the terms of the GNU Lesser General Public License as published
- * by the Free Software Foundation; version 2.1 only. with the special
- * exception on linking described in file LICENSE.
- *
- * This program is distributed in the hope that it will be useful,
- * but WITHOUT ANY WARRANTY; without even the implied warranty of
- * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
- * GNU Lesser General Public License for more details.
- *)
-
-open OUnit
-open Test_common
-
-let test_always_pass () = assert_equal 1 1
-let test_always_fail () = skip "This will fail" ; assert_equal 1 0
-
-let test_mock_db () =
-  let __context = Mock.make_context_with_new_db "Mock context" in
-  let blob_ref = Ref.make () in
-  Db.Blob.create __context blob_ref
-    (Uuid.to_string (Uuid.make_uuid ()))
-    "BLOB" "" 5L true (Stdext.Date.of_float 0.0) "" ;
-  ignore (Db.Blob.get_record ~__context ~self:blob_ref) ;
-  ignore (Db.VM.get_all_records ~__context) ;
-  let blob_name = Db.Blob.get_name_label ~__context ~self:blob_ref in
-  assert_equal blob_name "BLOB"
-
-let test_assert_licensed_storage_motion () = skip "TODO" ;
-  let __context = Mock.make_context_with_new_db "Mock context" in
-  let licensed = try Xapi_vm_migrate.assert_licensed_storage_motion ~__context; true
-    with _ -> false in
-  assert_bool "Not licensed for SXM" licensed
-
-let test =
-  "test_basic" >:::
-  [
-    "test_always_pass" >:: test_always_pass ;
-    "test_always_fail" >:: test_always_fail ;
-    "test_mock_db" >:: test_mock_db ;
-    "test_assert_licensed_storage_motion" >:: test_assert_licensed_storage_motion ;
-  ]
diff --git a/ocaml/tests/test_cluster.ml b/ocaml/tests/test_cluster.ml
index 25ec54b..ce11339 100644
--- a/ocaml/tests/test_cluster.ml
+++ b/ocaml/tests/test_cluster.ml
@@ -13,7 +13,6 @@
  *)
 
 open Xapi_cluster
-open OUnit
 
 let test_clusterd_rpc ~__context call =
   let token = "test_token" in
@@ -63,8 +62,6 @@ let test_enable () =
   pool_destroy ~__context ~self:cluster
 
 let test =
-  "test_cluster" >:::
-  [
-    "test_create_destroy_service_status" >:: test_create_destroy_status;
-    "test_enable" >:: test_enable;
+  [ "test_create_destroy_service_status", `Quick, test_create_destroy_status
+  ; "test_enable", `Quick, test_enable
   ]
diff --git a/ocaml/tests/test_cluster_host.ml b/ocaml/tests/test_cluster_host.ml
index 4d72794..ae7bc1b 100644
--- a/ocaml/tests/test_cluster_host.ml
+++ b/ocaml/tests/test_cluster_host.ml
@@ -23,21 +23,22 @@ let create_cluster ~__context pool_auto_join =
     ~current_operations:[] ~pool_auto_join ~cluster_config:[] ~other_config:[];
   cluster_ref
 
+let assert_ref_option =
+  Alcotest.(check (option (Alcotest_comparators.ref ()) ))
+
 let test_dbsync_join () =
   let __context = Test_common.make_test_database () in
   let cluster = create_cluster ~__context true in
   let localhost = Helpers.get_localhost ~__context in
   let result = sync_required ~__context ~host:localhost in
-  OUnit.assert_equal result (Some (cluster))
+  assert_ref_option "Cluster option" result (Some (cluster))
 
 let test_dbsync_nojoin () =
   let __context = Test_common.make_test_database () in
   let _cluster = create_cluster ~__context false in
   let localhost = Helpers.get_localhost ~__context in
   let result = sync_required ~__context ~host:localhost in
-  OUnit.assert_equal result None
-
-open OUnit
+  assert_ref_option "Cluster option" result None
 
 let pif_plug_rpc __context call =
   match call.Rpc.name, call.Rpc.params with
@@ -66,7 +67,7 @@ let test_fix_prereq () =
   let localhost = Helpers.get_localhost ~__context in
   let pifref = Test_common.make_pif ~__context ~network ~host:localhost () in
   let pif = Xapi_clustering.pif_of_host ~__context network localhost in
-  assert_raises
+  Alcotest.check_raises "Should fail when checking PIF prequisites"
     (Failure exn)
     (fun () ->
       try
@@ -77,7 +78,8 @@ let test_fix_prereq () =
   let pif = Xapi_clustering.pif_of_host ~__context network localhost in
   Xapi_cluster_host.fix_pif_prerequisites ~__context pif;
   let pif = Xapi_clustering.pif_of_host ~__context network localhost in
-  assert_equal (Xapi_clustering.assert_pif_prerequisites pif) ()
+  Alcotest.(check unit) "Assert PIF prerequisites without error"
+    (Xapi_clustering.assert_pif_prerequisites pif) ()
 
 let test_create_as_necessary () =
   let __context = Test_common.make_test_database () in
@@ -89,10 +91,10 @@ let test_create_as_necessary () =
   Db.PIF.set_IP ~__context ~self:pifref ~value:"1.1.1.1";
   let _pif = Xapi_clustering.pif_of_host ~__context network localhost in
   let result = sync_required ~__context ~host:localhost in
-  OUnit.assert_equal result (Some cluster);
+  assert_ref_option "Cluster option" result (Some cluster);
   Xapi_cluster_host.create_as_necessary ~__context ~host:localhost;
   let result = sync_required ~__context ~host:localhost in
-  OUnit.assert_equal result None
+  assert_ref_option "Cluster option" result None
 
 (* CA-275728 *)
 let test_destroy_forbidden_when_sr_attached () =
@@ -110,18 +112,18 @@ let test_destroy_forbidden_when_sr_attached () =
     Test_common.make_sr ~__context ~_type:sr_type ()
   in
   let _pbd : _ API.Ref.t = Test_common.make_pbd ~__context ~host ~sR ~currently_attached:true () in
-  OUnit.assert_raises
+  let msg = ("Host has attached SR whose SM requires cluster stack " ^ cluster_stack) in
+  Alcotest.check_raises
+    ("Should raise (Failure " ^ msg ^ ")")
     (* TODO: update this when the exceptions are finalized *)
-    (Failure ("Host has attached SR whose SM requires cluster stack " ^ cluster_stack))
+    (Failure msg)
     (fun () -> Xapi_cluster_host.destroy ~__context ~self:cluster_host)
 
 
 let test =
-  "test_cluster_host" >:::
-  [
-    "test_dbsync_join" >:: test_dbsync_join;
-    "test_dbsync_nojoin" >:: test_dbsync_nojoin;
-    "test_fix_prerequisites" >:: test_fix_prereq;
-    "test_create_as_necessary" >:: test_create_as_necessary;
-    "test_destroy_forbidden_when_sr_attached" >:: test_destroy_forbidden_when_sr_attached;
+  [ "test_dbsync_join", `Quick, test_dbsync_join
+  ; "test_dbsync_nojoin", `Quick, test_dbsync_nojoin
+  ; "test_fix_prerequisites", `Quick, test_fix_prereq
+  ; "test_create_as_necessary", `Quick, test_create_as_necessary
+  ; "test_destroy_forbidden_when_sr_attached", `Quick, test_destroy_forbidden_when_sr_attached
   ]
diff --git a/ocaml/tests/test_clustering_allowed_operations.ml b/ocaml/tests/test_clustering_allowed_operations.ml
index 139b562..c04f6e3 100644
--- a/ocaml/tests/test_clustering_allowed_operations.ml
+++ b/ocaml/tests/test_clustering_allowed_operations.ml
@@ -52,7 +52,7 @@ let test_cluster_ops_not_allowed_during_cluster_op () =
   Xapi_cluster_helpers.with_cluster_operation ~__context ~self ~doc:"" ~op:`add
     (fun () ->
        let allowed_ops = Db.Cluster.get_allowed_operations ~__context ~self in
-       assert_bool "Cluster.allowed_operations should be empty" (List.length allowed_ops = 0))
+       assert_bool "Cluster.allowed_operations should be empty" (allowed_ops = []))
 
 (** all cluster operations are allowed if no cluster operations are in progress *)
 let test_all_cluster_ops_allowed_when_no_cluster_ops_in_progress () =
@@ -98,7 +98,7 @@ let test_cluster_host_ops_not_allowed_during_cluster_host_op () =
   Xapi_cluster_host_helpers.with_cluster_host_operation ~__context ~self ~doc:"" ~op:`disable
     (fun () ->
        let allowed_ops = Db.Cluster_host.get_allowed_operations ~__context ~self in
-       assert_bool "Cluster_host.allowed_operations should be empty" (List.length allowed_ops = 0))
+       assert_bool "Cluster_host.allowed_operations should be empty" (allowed_ops = []))
 
 let test =
   "test_clustering_allowed_operations" >:::
diff --git a/ocaml/tests/test_daemon_manager.ml b/ocaml/tests/test_daemon_manager.ml
index bdf3d22..e6919c0 100644
--- a/ocaml/tests/test_daemon_manager.ml
+++ b/ocaml/tests/test_daemon_manager.ml
@@ -12,8 +12,6 @@
  * GNU Lesser General Public License for more details.
  *)
 
-open OUnit
-
 type stop_failure = {
   error: exn;
   (** The exception thrown when trying to stop the daemon. *)
@@ -63,14 +61,17 @@ end
 
 module Mock_manager = Daemon_manager.Make(Mock_daemon)
 
+let check_times_called ~start ~stop =
+  Alcotest.(check int) "times_called_start" !Mock_daemon.times_called_start start;
+  Alcotest.(check int) "time_until_stopped" !Mock_daemon.times_called_stop stop
+
 (* Test that the daemon is restarted, and that the return value of the function
    passed to with_daemon_stopped is propagated. *)
 let test_basic_operation () =
   Mock_daemon.reset ~is_running:true;
   let result = Mock_manager.with_daemon_stopped (fun () -> 123) in
-  assert_equal result 123;
-  assert_equal !Mock_daemon.times_called_start 1;
-  assert_equal !Mock_daemon.times_called_stop 1
+  Alcotest.(check int) "result" result 123;
+  check_times_called ~start:1 ~stop:1
 
 (* Two sequential calls to with_daemon_stopped should restart the daemon
    twice. *)
@@ -78,25 +79,22 @@ let test_two_restarts () =
   Mock_daemon.reset ~is_running:true;
   Mock_manager.with_daemon_stopped (fun () -> ());
   Mock_manager.with_daemon_stopped (fun () -> ());
-  assert_equal !Mock_daemon.times_called_start 2;
-  assert_equal !Mock_daemon.times_called_stop 2
+  check_times_called ~start:2 ~stop:2
 
 (* Test that if the daemon is stopped, calling with_daemon_stopped does not
    attempt to stop or start it. *)
 let test_already_stopped () =
   Mock_daemon.reset ~is_running:false;
   let result = Mock_manager.with_daemon_stopped (fun () -> 123) in
-  assert_equal result 123;
-  assert_equal !Mock_daemon.times_called_start 0;
-  assert_equal !Mock_daemon.times_called_stop 0
+  Alcotest.(check int) "result" result 123;
+  check_times_called ~start:0 ~stop:0
 
-(* Test that an exception is propagated by with_daemon_stopped. *)
 let test_exception () =
   Mock_daemon.reset ~is_running:true;
-  assert_raises (Failure "fail")
+  Alcotest.check_raises "exception is propagated by with_daemon_stopped"
+    (Failure "fail")
     (fun () -> Mock_manager.with_daemon_stopped (fun () -> failwith "fail"));
-  assert_equal !Mock_daemon.times_called_start 1;
-  assert_equal !Mock_daemon.times_called_stop 1
+  check_times_called ~start:1 ~stop:1
 
 let spawn_threads_and_wait task count =
   let rec spawn_threads task count acc =
@@ -117,8 +115,7 @@ let test_threads () =
     Mock_manager.with_daemon_stopped (fun () -> Thread.delay 5.0)
   in
   spawn_threads_and_wait delay_thread 5;
-  assert_equal !Mock_daemon.times_called_start 1;
-  assert_equal !Mock_daemon.times_called_stop 1
+  check_times_called ~start:1 ~stop:1
 
 (* The daemon initially fails to stop, but it stops within the timeout. *)
 let test_timeout_succeed () =
@@ -128,8 +125,7 @@ let test_timeout_succeed () =
       time_until_stopped = 2.0;
     };
   Mock_manager.with_daemon_stopped ~timeout:5.0 (fun () -> ());
-  assert_equal !Mock_daemon.times_called_start 1;
-  assert_equal !Mock_daemon.times_called_stop 1
+  check_times_called ~start:1 ~stop:1
 
 (* The daemon does not stop within the timeout, so the exception is raised. *)
 let test_timeout_fail () =
@@ -138,19 +134,18 @@ let test_timeout_fail () =
       error = Failure "stop failed";
       time_until_stopped = 5.0;
     };
-  assert_raises (Failure "stop failed")
+  Alcotest.check_raises "does not stop within timeout"
+    (Failure "stop failed")
     (fun () -> Mock_manager.with_daemon_stopped ~timeout:2.0 (fun () -> ()));
-  assert_equal !Mock_daemon.times_called_start 0;
-  assert_equal !Mock_daemon.times_called_stop 1
+  check_times_called ~start:0 ~stop:1
 
 let test =
-  "daemon_manager" >:::
   [
-    "test_basic_operation" >:: test_basic_operation;
-    "test_two_restarts" >:: test_two_restarts;
-    "test_already_stopped" >:: test_already_stopped;
-    "test_exception" >:: test_exception;
-    "test_threads" >:: test_threads;
-    "test_timeout_succeed" >:: test_timeout_succeed;
-    "test_timeout_fail" >:: test_timeout_fail;
+    "test_basic_operation", `Quick, test_basic_operation;
+    "test_two_restarts", `Quick, test_two_restarts;
+    "test_already_stopped", `Quick, test_already_stopped;
+    "test_exception", `Quick, test_exception;
+    "test_threads", `Slow, test_threads;
+    "test_timeout_succeed", `Slow, test_timeout_succeed;
+    "test_timeout_fail", `Slow, test_timeout_fail;
   ]
diff --git a/ocaml/tests/test_network_event_loop.ml b/ocaml/tests/test_network_event_loop.ml
index 1bc1521..9d6e11d 100644
--- a/ocaml/tests/test_network_event_loop.ml
+++ b/ocaml/tests/test_network_event_loop.ml
@@ -14,6 +14,7 @@
 
 let test_network_event_loop ~no_nbd_networks_at_start () =
   let __context, _ = Test_event_common.event_setup_common () in
+  Context.set_test_rpc __context (Mock_rpc.rpc __context);
 
   let localhost = Helpers.get_localhost ~__context in
   let other_host = Test_common.make_host ~__context () in
diff --git a/ocaml/xapi/static_vdis.ml b/ocaml/xapi/static_vdis.ml
index feafacf..5b36fd7 100644
--- a/ocaml/xapi/static_vdis.ml
+++ b/ocaml/xapi/static_vdis.ml
@@ -44,8 +44,9 @@ let permanent_vdi_detach ~__context ~vdi =
   info "permanent_vdi_detach: vdi = %s; sr = %s"
     (Ref.string_of vdi) (Ref.string_of (Db.VDI.get_SR ~__context ~self:vdi));
   let vdi_uuid = Db.VDI.get_uuid ~__context ~self:vdi in
+  log_and_ignore_exn(fun () ->
     ignore(Helpers.call_script !Xapi_globs.static_vdis
-           [ "detach"; vdi_uuid ]);
+           [ "detach"; vdi_uuid ]));
   ignore(Helpers.call_script !Xapi_globs.static_vdis
            [ "del"; vdi_uuid ])
 
@@ -53,7 +54,8 @@ let permanent_vdi_detach ~__context ~vdi =
 let permanent_vdi_detach_by_uuid ~__context ~uuid =
   info "permanent_vdi_detach: vdi-uuid = %s" uuid;
   (* This might fail because the VDI has been destroyed *)
-  ignore(Helpers.call_script !Xapi_globs.static_vdis [ "detach"; uuid ]);
+  log_and_ignore_exn(fun () ->
+    ignore(Helpers.call_script !Xapi_globs.static_vdis [ "detach"; uuid ]));
   ignore(Helpers.call_script !Xapi_globs.static_vdis [ "del"; uuid ])
 
 let detach_only vdi =
diff --git a/ocaml/xapi/vm_evacuation.ml b/ocaml/xapi/vm_evacuation.ml
index 1d979b6..6cd6249 100644
--- a/ocaml/xapi/vm_evacuation.ml
+++ b/ocaml/xapi/vm_evacuation.ml
@@ -35,15 +35,26 @@ let ensure_no_vms ~__context ~rpc ~session_id ~evacuate_timeout =
     |> List.filter (fun vm -> is_running vm && not (self_managed_poweroff vm))
   in
 
+  let cancel_vm_tasks self =
+    Db.VM.get_current_operations ~__context ~self
+    |> List.rev_map fst
+    |> List.rev_map Ref.of_string
+    |> List.iter (fun (task:[`task] Ref.t) ->
+        let name = Db.VM.get_name_label ~__context ~self in
+        debug "Canceling operation on VM %s" name;
+        log_and_ignore_exn (fun () -> Client.Task.cancel ~rpc ~session_id ~task))
+  in
+
   let evacuate () =
     TaskHelper.exn_if_cancelling ~__context; (* First check if _we_ have been cancelled *)
     info "Requesting evacuation of host";
     let timeout = if evacuate_timeout > 0. then evacuate_timeout
                   else estimate_evacuate_timeout ~__context ~host in
     let tasks = [ Client.Async.Host.evacuate ~rpc ~session_id ~host ] in
-    (* XXX: shutdown.py used to cancel every task of every running domain if
-       evacuation failed *)
-    Tasks.with_tasks_destroy ~rpc ~session_id ~timeout ~tasks |> ignore
+    if not (Tasks.with_tasks_destroy ~rpc ~session_id ~timeout ~tasks) then begin
+      get_running_domains ()
+      |> List.iter cancel_vm_tasks
+    end
   in
 
   let clean_shutdown vms =
@@ -78,10 +89,10 @@ let ensure_no_vms ~__context ~rpc ~session_id ~evacuate_timeout =
 
   let shutdown vms =
     log_and_ignore_exn (fun () -> clean_shutdown vms);
-    (* XXX: shutdown.py only acted on running domains, but what about
-     * suspended/paused? *)
+    (* We can unplug the PBD if a VM is suspended or halted, but not if
+      * it is running or paused, i.e. "live" *)
     vms
-    |> List.filter is_running
+    |> List.filter (fun self -> Xapi_vm_lifecycle.is_live ~__context ~self)
     |> hard_shutdown
   in
 
diff --git a/ocaml/xapi/xapi_cluster_helpers.ml b/ocaml/xapi/xapi_cluster_helpers.ml
index fade6a4..3d375ff 100644
--- a/ocaml/xapi/xapi_cluster_helpers.ml
+++ b/ocaml/xapi/xapi_cluster_helpers.ml
@@ -51,10 +51,9 @@ let get_operation_error ~__context ~self ~op =
   (* if other operations are in progress, check that the new operation is allowed concurrently with them *)
   let current_error = check current_error (fun () ->
       let current_ops = cr.Db_actions.cluster_current_operations in
-      if List.length current_ops <> 0 && not (is_allowed_concurrently ~op ~current_ops)
+      if (current_ops <> []) && not (is_allowed_concurrently ~op ~current_ops)
       then report_concurrent_operations_error ~current_ops ~ref_str
       else None) in
-
   current_error
 
 let assert_operation_valid ~__context ~self ~op =
diff --git a/ocaml/xapi/xapi_cluster_host_helpers.ml b/ocaml/xapi/xapi_cluster_host_helpers.ml
index d2205d4..38a6a82 100644
--- a/ocaml/xapi/xapi_cluster_host_helpers.ml
+++ b/ocaml/xapi/xapi_cluster_host_helpers.ml
@@ -49,7 +49,7 @@ let get_operation_error ~__context ~self ~op =
   (* if other operations are in progress, check that the new operation is allowed concurrently with them *)
   let current_error = check current_error (fun () ->
       let current_ops = chr.Db_actions.cluster_host_current_operations in
-      if List.length current_ops <> 0 && not (is_allowed_concurrently ~op ~current_ops)
+      if current_ops <> [] && not (is_allowed_concurrently ~op ~current_ops)
       then report_concurrent_operations_error ~current_ops ~ref_str
       else None) in
 
diff --git a/ocaml/xapi/xapi_host.ml b/ocaml/xapi/xapi_host.ml
index 59563f0..597eee3 100644
--- a/ocaml/xapi/xapi_host.ml
+++ b/ocaml/xapi/xapi_host.ml
@@ -1806,6 +1806,16 @@ let set_iscsi_iqn ~__context ~host ~value =
   (* Note, the following sequence is carefully written - see the
      other-config watcher thread in xapi_host_helpers.ml *)
   Db.Host.remove_from_other_config ~__context ~self:host ~key:"iscsi_iqn";
+  (* we need to first set the iscsi_iqn field and then the other-config field:
+   * setting the other-config field triggers and update on the iscsi_iqn
+   * field if they are different
+   *
+   * we want to keep the legacy `other_config:iscsi_iqn` and the new `iscsi_iqn`
+   * fields in sync:
+   * when you update the `iscsi_iqn` field we want to update `other_config`,
+   * but when updating `other_config` we want to update `iscsi_iqn` too.
+   * we have to be careful not to introduce an infinite loop of updates.
+   * *)
   Db.Host.set_iscsi_iqn ~__context ~self:host ~value;
   Db.Host.add_to_other_config ~__context ~self:host ~key:"iscsi_iqn" ~value;
   Xapi_host_helpers.Configuration.set_initiator_name value
diff --git a/ocaml/xapi/xapi_host_helpers.ml b/ocaml/xapi/xapi_host_helpers.ml
index 64e8428..5c688db 100644
--- a/ocaml/xapi/xapi_host_helpers.ml
+++ b/ocaml/xapi/xapi_host_helpers.ml
@@ -294,7 +294,7 @@ module Configuration = struct
     let flag = !Xapi_globs.multipathing_config_file in
     if enabled then Unixext.touch_file flag
     else begin
-      if Sys.file_exists flag then Sys.remove flag
+      Unixext.unlink_safe flag
     end
 
   let sync_config_files ~__context =
diff --git a/ocaml/xapi/xapi_host_helpers.mli b/ocaml/xapi/xapi_host_helpers.mli
index d2c2e86..02f259c 100644
--- a/ocaml/xapi/xapi_host_helpers.mli
+++ b/ocaml/xapi/xapi_host_helpers.mli
@@ -12,7 +12,7 @@
  * GNU Lesser General Public License for more details.
  *)
 
-(** Common code between for dealing with Hosts.
+(** Common code for dealing with Hosts.
  * @group Host Management
 *)
 
diff --git a/scripts/xapi-domains.service b/scripts/xapi-domains.service
index 8d96a22..e9ec14f 100644
--- a/scripts/xapi-domains.service
+++ b/scripts/xapi-domains.service
@@ -1,7 +1,7 @@
 [Unit]
 Description=Start/stop domains on dom0 start/shutdown
 Requires=proc-xen.mount
-After=remote-fs.target xapi.service xapi-clusterd.service
+After=remote-fs.target xapi.service
 
 [Service]
 Type=oneshot
diff --git a/scripts/xapi.service b/scripts/xapi.service
index f00ca8f..c28d464 100644
--- a/scripts/xapi.service
+++ b/scripts/xapi.service
@@ -15,7 +15,6 @@ After=xcp-networkd.service
 After=xcp-rrdd.service
 After=xenopsd-xc.service
 After=xenstored.service
-After=xapi-clusterd.service
 
 Conflicts=shutdown.target
 
diff --git a/scripts/xe-set-iscsi-iqn b/scripts/xe-set-iscsi-iqn
index c0a2c11..5c7da9c 100755
--- a/scripts/xe-set-iscsi-iqn
+++ b/scripts/xe-set-iscsi-iqn
@@ -8,7 +8,6 @@ set -e
 
 XE="@BINDIR@/xe"
 
-configmap="other-config"
 configkey="iscsi_iqn"
 
 if [ ! -f @INVENTORY@ ]; then
@@ -30,4 +29,4 @@ fi
 
 . @INVENTORY@
 
-${XE} host-param-set uuid=${INSTALLATION_UUID} ${configmap}:${configkey}=${iqn}
+${XE} host-param-set uuid=${INSTALLATION_UUID} ${configkey}=${iqn}
diff --git a/xapi-client.opam b/xapi-client.opam
index 670989a..b012ee5 100644
--- a/xapi-client.opam
+++ b/xapi-client.opam
@@ -9,6 +9,7 @@ build: [[ "jbuilder" "build" "-p" name ]]
 
 depends: [
   "jbuilder" {build & >= "1.0+beta11"}
+  "mtime"
   "xapi-datamodel"
   "xapi-types"
   "xapi-stdext-date"
```

**Comment by edwintorok** [comment]
Discussed with @lindig that it is OK to merge.

**Pull request merged**
