### PR TITLE
CP-28923: Add sm capability for large and thinly provisioned VDIs

### PR DESCRIPTION
**Pull request by thomasmck**
Signed-off-by: Thomas Mckelvey <thomas.mckelvey@citrix.com>

### CODE REVIEW

**Comment by gaborigloi** [comment]
We can optionally add these as `storage_operations` enums, if these things may be useful for api users:
https://xapi-project.github.io/xen-api/classes/sr.html

**Comment by thomasmck** [comment]
@gaborigloi If we add them as storage_operation enums does that mean when creating the SR from the cli they can specify that is has the "LARGE_VDIS" or "THIN_PROVISIONING" features?

**Comment by gaborigloi** [comment]
It would be in the read-only `allowed-operations` SR field.
But actually, now that I think about it, these aren't really SR operations.

**Comment by edwintorok** [comment]
If we are going to use the Thin_provisioning capability, then we should probably add it to the existing SRs as well (Local storage Ext, SMB, NFS, and filebased, GFS2, nfs-ng).

**Comment by thomasmck** [comment]
@edvint Change for GFS2 is merged. Made the changes for existing SRs but waiting for Stefano to create a feature branch for me to merge to.

**Comment by edwintorok** [comment]
thanks, my username here is edwintorok though, edvint is someone else unrelated to me.

**Pull request merged**
