### PR TITLE
test: Add printer combinators to use with Test_highlevel

### PR DESCRIPTION
**Pull request by euanh**
First pass adds printers for basic types and combinators for
lists, arrays, pairs and association lists.

Signed-off-by: Euan Harris <euan.harris@citrix.com>

### CODE REVIEW

**Comment by euanh** [comment]
To replace the more complicated printers currently in use in the tests, we will need a way to specify constant text in the printer and to handle records.

**Comment by johnelse** [comment]
I like it!

I wonder if it's worth trying to use [this](https://github.com/whitequark/ppx_deriving#plugin-show) once we switch to OCaml 4.02.

**Comment by euanh** [comment]
Yes, I think ppx_deriving would be ideal.   We should probably use it for almost every type we define!

**Comment by johnelse** [comment]
:shipit: :ship: :boom:

**Pull request merged**
