### PR TITLE
Add the ability to run xapi while out-of-sync with Xen and/or libxenctrl

### PR DESCRIPTION
**Pull request by robhoes**
Depends on:
- https://github.com/xapi-project/ezxenstore/pull/13
- https://github.com/xapi-project/ocaml-rrdd-plugin/pull/31
- https://github.com/xapi-project/rrd-transport/pull/57
- https://github.com/xapi-project/xenopsd/pull/646

### CODE REVIEW

**Comment by lindig** [comment]
The commit message for ac6e420 has a typo in the subject line (no/not) and in the body (does/do).

**Comment by robhoes** [comment]
I have run the usual regression-test suites. Most of the changes only kick in in the out-of-sync situation, where previously xapi wouldn't even start, so they probably won't regress that bit :)

**Comment by edwintorok** [comment]
Lets put a ticket number on one of the commits so it is easier to track in the changelog.

**Comment by robhoes** [comment]
Thanks, I've updated the commit messages to fix the type and include the ticket numbers.

**Pull request merged**
