### PR TITLE
Refine the format of generated db_actions code

### PR DESCRIPTION
**Pull request by krizex**
Signed-off-by: Yang Qian <yang.qian@citrix.com>

### CODE REVIEW

**Comment by krizex** [comment]
Diffs of the generated file: [diff.txt](https://github.com/xapi-project/xen-api/files/2373968/diff.txt)

**Comment by robhoes** [comment]
Hmm... is this useful?

**Comment by krizex** [comment]
Yes, it helps me when reading these generated code

________________________________

**Comment by lindig** [comment]
I have no strong opinion. Code that emits code is difficult to write and I don't mind one way or the other.

**Pull request merged**
