### PR TITLE
CP-10787: functions for (un)hiding PCI devices from dom0 kernel.

### PR DESCRIPTION
**Pull request by thomassa**
pciops now has functions hide_pci, unhide_pci, is_pci_hidden

Signed-off-by: Thomas Sanders <thomas.sanders@citrix.com>

### CODE REVIEW

**Comment by thomassa** [comment]
This probably needs some code to handle exceptions thrown from `Scanf.sscanf` and turn them into some other kind of exception. What kind? Needs thought.

I think the pciops module is a sensible place for these new functions, but the division between
* pciops
* pci_db
* xapi_pci
* xapi_pci_helpers

is not as clear-cut as it might be.

**Comment by johnelse** [comment]
I agree, this is as good a place for this code as any.

**Comment by johnelse** [comment]
I think this would be better as two commits, one with the scanf/printf refactoring, and one with the new functionality.

**Comment by thomassa** [comment]
I agree. I'll do that.=

**Comment by thomassa** [comment]
I've split this into two commits now.

**Comment by thomassa** [comment]
...and updated the example in the comment to use the extended version of the BDF format, adding `0000:` to the beginning of each BDF string.

**Comment by johnelse** [comment]
Looks good now, thanks! I'll merge this once the build is finished.

**Pull request merged**
