### PR TITLE
CA-88550: Block VM.import during RPU

### PR DESCRIPTION
**Pull request by Annie-XIE**
Importing VMs during RPU sometimes will meet problems, this patch
disables such opertaion when rolling_poll_upgrade_in_progress

Signed-off-by: Huan Xie <huan.xie@citrix.com>

### CODE REVIEW

**Comment by cheng-z** [comment]
Hi @jonludlam 
Please help to have a look of this code. Thanks.

**Comment by Annie-XIE** [comment]
Although tested manually, I need to double check existing XenRT testcase to make this fix won't break current XenRT and modify XenRT code if necessary.

**Comment by Annie-XIE** [comment]
Have tested some XenRT job and pass, so reopen this PR

**Comment by jonludlam** [comment]
Looks good. Thanks @Annie-XIE!

**Pull request merged**
