### PR TITLE
Py3 merge to master

### PR DESCRIPTION
**Pull request by stephenchengCloud**
The nightly tests passed.

- [x] In the master branch https://github.com/xapi-project/xen-api/pull/5592 moved python CI config from main.yml to other.yml, while the feature/py3 branch modified the CI config in main.yml. Need to resolve this.
- [x] pytype failed

### CODE REVIEW

**Comment by stephenchengCloud** [comment]
- [ ] https://github.com/xapi-project/xen-api/pull/5592 moved python CI config in master branch to other.yml, while the feature/py3 branch modified the CI config in main.yml. Need to resolve this.

**Review by psafont — CHANGES_REQUESTED** [review]
All python 2 code needs to be removed before this PR can be merged.

I also don't understand why isn't feature/py3 being merged instead of a branch in a fork. What's the relationship between the two branches?

**Comment by stephenchengCloud** [comment]
The DCO check failed:

> Commit sha: [9b73950](https://github.com/xapi-project/xen-api/pull/5616/commits/9b73950b01641eec54e098858c3f06cd715d50ae), Author: acefei, Committer: GitHub; Expected "acefei [fei.su@cloud.com](mailto:fei.su@cloud.com)", but got "Fei Su [fei.su@cloud.com](mailto:fei.su@cloud.com)".
> Commit sha: [7b7a1f0](https://github.com/xapi-project/xen-api/pull/5616/commits/7b7a1f0f5a62653f5b7dfe1704ddabe7d11c6e6f), Author: acefei, Committer: GitHub; Expected "acefei [fei.su@cloud.com](mailto:fei.su@cloud.com)", but got "Fei Su [fei.su@cloud.com](mailto:fei.su@cloud.com)".

@psafont @liulinC Could we ignore this failure?

**Comment by stephenchengCloud** [comment]
> I also don't understand why isn't feature/py3 being merged instead of a branch in a fork. What's the relationship between the two branches?
This is tricky. After merging feature/py3 to master, the CI check failed because issues like `https://github.com/xapi-project/xen-api/pull/5592 moved python CI config from main.yml to other.yml`, and we need to manually move the changes in main.yml to other.yml.
So I created a branch which checked out from feature/py3 to do this.

**Comment by robhoes** [comment]
The usual way to do it is to first merge the master branch into the feature branch and resolve conflicts on the feature branch. Then create a PR back to master from the feature branch.

**Comment by stephenchengCloud** [comment]
Based on the comments. We'll continue the removing work in feature/py3 branch and then merge to the master branch.
Close this PR.

**Pull request closed without merging**
