### PR TITLE
CA-154009: Failure("int_of_string") raised by assert_can_migrate

### PR DESCRIPTION
**Pull request by Chunjie**

### CODE REVIEW

**Comment by Chunjie** [comment]
add @johnelse to review

**Comment by xen-git** [comment]
Can one of the admins verify this patch for testing?

**Comment by johnelse** [comment]
@xen-git test this please

**Comment by thomassa** [comment]
The commit-message needs a `Signed-off-by: ` line, and it would be nice if it said something about caching the stunnel connection (i.e. what the change is, not just what it fixes).

**Comment by thomassa** [comment]
As for using the stunnel cache, this is almost always a good idea, and it might be nice to make it the default in `SSL.make` (but not as part of this bugfix). I remember there were a few places where it caused problems, but it would be nice to have those as the unusual cases where we specify `~use_stunnel_cache:false`.

If we lose data when we don't cache the stunnel, that suggests a bug elsewhere: we must be closing the stunnel connection before we've finished with it (or to put the problem another way, trying to use the stunnel connection after we've closed it, or possibly trying to re-use a non-reusable http connection carried over the stunnel connection).

I feel that bug is the root cause of this symptom-ticket, and if we don't fix it then I worry that it might cause unreliability in other areas.

**Comment by Chunjie** [comment]
@thomassa , thanks sincerely for the detailed explanation about this issue.

I agree with you, such a fix cannot always avoid this problem since it is likely that any stunnel cache entry might be evicted. I will add this potential issue into comments.

**Pull request closed without merging**
