### PR TITLE
CA-150395: Ignore Storage_interface.Sr_not_attached exception when do xapi_vbd.unplug

### PR DESCRIPTION
**Pull request by phusl**
like SCTX-1892, but seems that we cannot catch Storage_interface.Sr_not_attached exception at storage_impl.ml
Here're a possible solution: use try-with statement to wrap xapi_vbd.unplug

### CODE REVIEW

**Comment by jonludlam** [comment]
Looks to me like we should close this one as a different solution is being pursued. Is that correct, @phusl?

**Comment by phuslu** [comment]
@jonludlam Yes, please.

**Comment by phusl** [comment]
@jonludlam  Yes, please

**Comment by simonjbeaumont** [comment]
@phusl: does this pull request contain the same things for trunk? https://github.com/xapi-project/xen-api/pull/2124. I.e. should it be also closed in pursuit of a different solution.

Also, where are we up to on another solution?

**Comment by Zhengchai** [comment]
Hi Simon and Jon, according to the discussion here with Phus Lu, we think this one are properly fixed customer's issue (SCTX-1901) and verified at customer environment already, while the another one is not verified yet, but customer doesn't want to re-test it again because the first solution already fixed their problem from customer point of view. However, we can not reproduce this issue in lab as it is a concurrent situation with CCP to verify the #2124, so we are not sure if this #2124 can fix this problem of not at the moment. 

Any other solution(s) or do you think that we need to figure out another new solution for this? thank you.

**Pull request closed without merging**
