### PR TITLE
Private/mingl/cp 32124

### PR DESCRIPTION
**Pull request by minglumlu**

### CODE REVIEW

**Comment by edwintorok** [comment]
Please add a signoff to each of your commits, see the error from the DCO bot.

**Comment by edwintorok** [comment]
To fix the build error from Travis please merge from latest master (we just fixed that build error there).

**Comment by minglumlu** [comment]
> I think these changes are fairly independent of the stunnel version.
> Does the last change (with debug=authpriv.5) work with the old stunnel as well?

Yes. "debug=authpriv.5" work with the old one also.

**Comment by minglumlu** [comment]
Not sure why github displays the extra commits in PR even rebase hase been done on source/destination branches.

**Comment by edwintorok** [comment]
The feature branch doesn't track master automatically, its fine those commits from master.

**Pull request merged**
