### PR TITLE
support python 3 too

### PR DESCRIPTION
**Pull request by timkuik**
Changed syntax to work with multiple versions.
Leveraged six.

### CODE REVIEW

**Comment by mseri** [comment]
I am very happy with this change, however we need to document somewhere that to use the new `XenAPI` python module it is necessary to install `six` as dependency.

**Comment by mseri** [comment]
In the future it would be nice to move the script on it's own place and add a proper `setup.py` and a decent install procedure (and dependency checks).

**Comment by mseri** [comment]
After discussing this with @robhoes we are happy to merge the change. The `python-six` package is installed in `xenserver` (That anyways uses `2.7`) and the old script can be always obtained by anybody needing it. 

Ping @kc284 to see if there is anything that need to be done to document this change in the sdk

**Comment by timkuik** [comment]
@mseri @kc284 I really like the idea of moving this file into a subdirectory and adding a setup.py. Honestly, I'm not certain how the pypi package is built today but that would allow for others to reference the very latest prior to the next official release. Do you want me to offer up a PR with that change?
I'm assuming that there isn't a documentation change for this since I only ran into it because I had tried to run my client on a remote machine that used python 3.5.

**Comment by mseri** [comment]
Unfortunately the pypi package is in a stuck state. Was done sometime in the past by a citrix employee that left and we have not been able to convince the pypi managers to unlock it for us to allow an update.

I'd love a PR with the change but it requires also changes in how the xapi-sdk is generated, so I'd leave it pending as is now and I'll create an internal ticket to do asap it in the future.

Thanks again!

**Comment by kc284** [comment]
@mseri please feel free to move XenAPI.py to a more appropriate location, just remember to update the README.md in the xen-api-sdk repo afterwards.

**Pull request merged**
