### PR TITLE
`storage/api/volume.py`: Replace `if not(fn)` with `if not fn`

### PR DESCRIPTION
**Pull request by bernhardkaindl**
`storage/api/volume.py`: Apply automatic conversion script:

Replace all
```py
if not(is_long(value)):
```
with:
```py
if not is_long(value):
```
Conversion script:
```py
import re, sys

def isinstance_to_is_str(line):
    pattern = r"(.*)if not\(is_long\((.*)\)\):"
    replace = r'\1if not is_long(\2):'
    match = re.match(pattern, line)
    return re.sub(pattern, replace, line) if match else line

def main():
    with open(sys.argv[1], "r") as file:
        code = file.readlines()
    with open(sys.argv[1], "w") as file:
        file.write("".join(isinstance_to_is_str(code_line) for code_line in code))

main()
```

### CODE REVIEW

**Review by edwintorok — COMMENTED** [review]
This appears to be auto-generated code, why are we changing it this way?

**Review by edwintorok — COMMENTED** [review]
I think this was code for testing backward compatibility with old versions of SMAPIv3. By definition that code would've been Python2-only (because there was no Python3 version of it at the time).
So if we change this we also break backward compatibility for those SMAPIv3 plugins.

And if we do that we might as well go ahead and delete this and the backward compatibility tests. (will need updates to the specfile).

**Comment by bernhardkaindl** [comment]
> This appears to be auto-generated code, why are we changing it this way?

In 2018, you did update this code by re-generating it: https://github.com/xapi-project/xen-api/commit/fc4355eafd4a2becd8551bb2c7dc836320051a23
But the old generator was then deleted and related code seems to have been used for a new Codegen: https://github.com/xapi-project/xen-api/commit/3a369260486234e29569a7298f5424826966ee64

@MarkSymsCtx: I think we spoke at the XenSummit 2023 in Prague with Edwin about this.
I don't know the details, but it was after that we began to merge steps to update the code to Python3.

Hello Yann (@ydirson) chatting with you, I also understood that this code is used for GFS2 (for example) and would need to be updated to work with Python3 in the future?

**Comment by ydirson** [comment]
> Hello Yann (@ydirson): Chatting with you, I also understood that this code is used for GFS2 (for example) and would need to be updated to work with Python3 in the future?

My understanding is that XS' FGS2 SR and support code have already moved to python3.

Anyway the `not()` syntax does not seem to be that much of a problem, what do I miss?
```
Python 3.11.2 (main, May  2 2024, 11:59:08) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> not(False)
True
```

**Comment by bernhardkaindl** [comment]
Closing. This will be obsolete with the removal of `ocaml/xapi-storage/python/xapi/storage/api/{volume,plugin,*datapath}.py`:
They should have no consumers left that we know of (at least for XenServer).

**Comment by bernhardkaindl** [comment]
Closing. This will be obsolete with the removal of `ocaml/xapi-storage/python/xapi/storage/api/{volume,plugin,*datapath}.py`:
They should have no consumers left that we know of (at least for XenServer). 

#5867 is for preparing the removal of those scripts and related obsolescence of Pyhon2.7.

**Pull request closed without merging**
