### PR TITLE
CP-11034: Report the system display device via a new PGPU field

### PR DESCRIPTION
**Pull request by euanh**

### CODE REVIEW

**Comment by johnelse** [comment]
Looks good, except the setter should be removed - this should just be a read only field which reflects the state of the hardware.

**Comment by euanh** [comment]
Yes, I wasn't sure if that would be needed, but I had the patch.   I'll take it off.

**Comment by johnelse** [comment]
This might need rebasing on top of #2126, sorry! Also the version bump got merged via #2126 so you can drop that commit.

**Comment by euanh** [comment]
@johnelse: Rebased

**Comment by johnelse** [comment]
`0b9bfce` can go as well, as it's just code for the setter. Otherwise looks good.

**Comment by euanh** [comment]
@johnelse: Ok, gone.  The compiler error I was getting must have been because I only had half of this setter implemented, whereas in fact I didn't need it at all!

**Comment by johnelse** [comment]
Great :) I'll merge this once Jenkins has finished with it.

**Pull request merged**
