### PR TITLE
CA-189076: Make sure perfmon wait at least the defined interval

### PR DESCRIPTION
**Pull request by zli**

### CODE REVIEW

**Comment by johnelse** [comment]
Code looks sensible; the comment above could do with an update so that it reflects the new behaviour :-)

**Comment by simonjbeaumont** [comment]
@johnelse: comment looks correct to me. More so with the code change.

**Comment by simonjbeaumont** [comment]
Ignore my last (deleted comment) bit early and read the diff the wrong way around.

**Comment by zli** [comment]
Updated wrt @johnelse's review comment, good catch!

**Comment by johnelse** [comment]
Looks good, thanks! Ready to go in once we've unfrozen the staging branch.

**Pull request merged**
