### PR TITLE
CA-195652: Cause Xenopsd to cleanup before creating new domains

### PR DESCRIPTION
**Pull request by simonjbeaumont**
This pull request addresses several issues with the handling of events between Xapi and Xenopsd.

Prior to this patch series there were some race-conditions on error paths that could cause 2 domains to be concurrently running for the same VM due to events being missed by Xapi and Xapi not syncing with events before doing lifecycle operations.

Among the commits in this pull-request, these are the ones that are of most interest with respect to re-gaining thread safety:

	4486f94: CA-195652: Stack with_events_suppressed calls …
	cd12c21: CA-195652: Sync with Xenopsd events after suppression …
	b5ff609: CA-195652: Cause Xenopsd to cleanup before creating new domains …
	e768829: CA-195652: Wait for events to be un-suppressed after suppression …
	f6b51b3: CA-195652: Refresh VM after re-enabling events from Xenopsd …
	b962fcd: CA-195652: Handle pool_migrate errors with events suppressed …

### CODE REVIEW

**Comment by robhoes** [comment]
So this patch:
- does the "tidy up" on all exceptions, rather than only on some;
- calls `XenAPI.VM.pool_migrate_complete` even on the error path.

The `VM.pool_migrate_complete` call gets forwarded to the destination host of the pool_migrate. Is that correct in all error cases?

**Comment by simonjbeaumont** [comment]
> The VM.pool_migrate_complete call gets forwarded to the destination host of the pool_migrate. Is that correct in all error cases?
This is a good question. It was originally there in a call_api_functions wrapper so I retained that. I need to kick the tires harder on a cross-host migrate and check that this doesn't need to be called on both hosts.

My intention in opening this pull request is to take the RPMs from xen-git and throw them at some XenRT testcases.

**Comment by robhoes** [comment]
Also, which bit of the `VM.pool_migrate_complete` is what makes this actually work? Is it something in `Xapi_xenops.set_resident_on`?

Finally, if `VM.pool_migrate_complete` is called on the error path, the message in the logs saying "VM.pool_migrate_complete" may be a little misleading.

**Comment by simonjbeaumont** [comment]
Note to reviewer: The commits are not displayed in commit order (due to rebasing).

**Comment by simonjbeaumont** [comment]
This has a counterpart fix in Xenopsd: https://github.com/xapi-project/xenopsd/pull/243

**Comment by simonjbeaumont** [comment]
Renamed pull-request title to reflect the principle commit's message.

**Comment by johnelse** [comment]
Looks good to me now, just needs approval from @jonludlam

**Comment by simonjbeaumont** [comment]
@xen-git retest this please.

**Comment by simonjbeaumont** [comment]
There's actually one more patch (in addition to the fixups) that I've added after testing my RPMs against XenRT.

**Comment by simonjbeaumont** [comment]
Right, I'll squash that fix up now things have been reviewed.

**Pull request merged**
