### PR TITLE
CA-183272: Improving Dom0 mem usage alert mail text

### PR DESCRIPTION
**Pull request by koushikcgit**
Signed-off-by: Koushik Chakravarty <koushik.chakravarty@citrix.com>

### CODE REVIEW

**Comment by koushikcgit** [comment]
Adding @johnelse  as reviewer

**Comment by johnelse** [comment]
This change looks fine. However the ticket mentions two issues:

```
Observed:
1. Alert description says "ratio of memory demand to physical memory is beyond 0.0%" which is not clear to understand
2. Alert priority reduced when it is generated after repeat interval
```

This looks like it only fixes #1 - do we need a separate ticket for #2?

**Comment by jonludlam** [comment]
I don't think the message should contain the text 'Dom0' - that's not Approved Vocabulary :-)

Perhaps we could get someone used to writing user-facing docs to write the text?

**Comment by robhoes** [comment]
"Dom0" -> "The Control Domain"?

**Comment by stephen-turner** [comment]
I've created CA-187949 for the other issue.

**Comment by johnelse** [comment]
Actually yes I agree with @robhoes, "the control domain" would be better than "dom0".

**Comment by stephen-turner** [comment]
I'm actually still confused what the message means, and what is being compared. What is the "control domain memory demand" and what is the "domain physical memory"? (Or should it be host memory?)

**Comment by koushikcgit** [comment]
This is actually calculated as (res_mem + swap_in_use) / phy_mem (using /proc/meminfo as data source).

So yes, I think its better to use "Control domain memory usage" with respect to "Control domain physical memory".

@johnelse : The issue #2 is not reproducible and this PR is to fix the issue #1 mail-alarm bit.

**Comment by stephen-turner** [comment]
So would it be accurate to say it's the amount of RAM actually in use in dom0 compared with the total amount of dom0 RAM?

**Comment by koushikcgit** [comment]
@stephen-turner  Yes.

**Comment by stephen-turner** [comment]
Re issue 2, if it's really not reproducible, we should close CA-187949. However, there is a screenshot there, so it clearly happened somehow!

**Comment by stephen-turner** [comment]
OK, so next question: why does it say the "ratio ... is beyond 0%". It's always beyond 0%! Does it mean 100%, or is the number not getting passed around and defaults to zero?

**Comment by koushikcgit** [comment]
Updated.

**Comment by johnelse** [comment]
I've asked the docs team to have a look at the wording of this message.

**Comment by thomassa** [comment]
At that rate, I think we should assign the "CA" bug-ticket to the docs people and close this pull-request for the time being, until we have wording from the official word-wranglers.

**Comment by stephen-turner** [comment]
Wait a bit, I was hoping to come up with a wording we could use in the GUI.

**Comment by stephen-turner** [comment]
How about something like: "The memory required by the control domain is above x% of its allocated memory". Is that accurate?

**Comment by koushikcgit** [comment]
@stephen-turner : Makes sense to me. Do you want me to update the PR in accordance to this?

**Comment by stephen-turner** [comment]
Yes, please do.

**Comment by thomassa** [comment]
Looks good. Merging.

**Pull request merged**
