### PR TITLE
[CA-223800] Fix xapi-xenopsd assert-statements

### PR DESCRIPTION
**Pull request by mseri**
Replace all assert statements with appropriate `Server_errors` carrying enough information for debugging.

Signed-off-by: Marcello Seri <marcello.seri@citrix.com>

### CODE REVIEW

**Comment by robhoes** [comment]
We need to make sure that error messages imply some sort of action for the user, if the error happens for a legitimate reason. If the error happens because the software has somehow messed up, then this should result in an "internal error"; this basically implies a bug in the software. I think that many, if not all, of these assertions are in fact internal errors (though I haven't checked all).

**Comment by mseri** [comment]
Yes, I thought that was the reason all those exceptions were raised inside `transform_xenops_exn`, but it was an oversight. In all cases, the exceptions are happening because something is in an unexpected status. Does this mean that they should all become internal? In this case I could also avoid modifying `ocaml/idl/api_errors.ml` and add more explicit error messages.

**Comment by robhoes** [comment]
If they are errors "that should never happen", then `Api_error.internal_error` is appropriate. It takes a string argument that can be set to something useful describing the issue. The user would interpret this as "call support and tell them that string".

**Comment by mseri** [comment]
I have modified the PR and made the errors internal, with a more descriptive comment in each case.

**Comment by robhoes** [comment]
Is this really CA-223380?

**Comment by mseri** [comment]
Wow, well spotted. It is `CA-223800`.

**Comment by mseri** [comment]
I look through the code to check if there were other `asserts` that could be converted to more meaningful errors. I think this is now covered by the last two commits should.

**Pull request merged**
