### PR TITLE
CP-10773 - move xe-install-supplemental-pack into xen-api.git and expand it slightly

### PR DESCRIPTION
**Pull request by jonludlam**
Add the xe-install-supplemental-pack script to xapi, and modify it to be suitable to install from a VDI.

### CODE REVIEW

**Comment by johnelse** [comment]
Please could the pull request have a more descriptive title? :)

**Comment by jonludlam** [comment]
@johnelse done!

**Comment by srowe** [comment]
Can you nuke the file from dom.hg too?

**Comment by jonludlam** [comment]
@srowe will do, once this is in.

**Pull request merged**
