### PR TITLE
CA-215578: Fixed issue where halted control domains were deleted from…

### PR DESCRIPTION
**Pull request by kc284**
… the database after a pool restore.

Signed-off-by: Konstantina Chremmou <konstantina.chremmou@citrix.com>

### CODE REVIEW

**Comment by jonludlam** [comment]
I don't think this is the right fix.

I'm not convinced we even need the VM.destroy - have you tried the backup/restore?

Even if we do need it, I think a simpler fix will be to just remove the VM only if it's power_state is 'Running', and the resident_on is invalid.

**Comment by jonludlam** [comment]
Also, it looks to me like it will destroy dom0, since it doesn't have any disks usually.

**Comment by jonludlam** [comment]
Oh no, I see, you've left in the check for the real resident_on.

**Comment by kc284** [comment]
@jonludlam, unless there is an issue with leaving control domains, upon which one cannot perform lifecycle operations, lying aroung halted, it's probably not necessary to destroy them, hence I reworked the code to halt those too. Please comment on this fix. Thanks.

**Comment by jonludlam** [comment]
Looks good!

**Pull request merged**
