### PR TITLE
CA-154780: System Template import should raise an error

### PR DESCRIPTION
**Pull request by sharady**
Signed-off-by: Sharad Yadav <sharad.yadav@citrix.com>

### CODE REVIEW

**Comment by thomassa** [comment]
The function name `is_system_template` looks as if it should return a Boolean corresponding to whether or not the metadata is a system template.

In fact it returns unit, but can raise an exception.

It would be better to name it something like `assert_not_system_template`, or change it to return a Boolean and change the calling code from
```
is_system_template metadata;
```
to
```
if is_system_template metadata then raise (IFailure System_template_file);
```

(The same goes for the `is...` functions it uses, obviously.)

Also, as Dave says, there should be an explanation of why we forbid import of system templates. Dave says this explanation should go in the git commit comment. I think it would be useful as a comment in the code as well.

**Comment by djs55** [comment]
I just wanted to check that this is really what we wanted to do -- we
always intended to replace create_templates.ml in guest-templates with VM
exports which would be "xe vm-import"ed by a firstboot script. Would this
change make that impossible?

On Fri, Jan 2, 2015 at 2:26 PM, thomassa <notifications@github.com> wrote:

> The function name `is_system_template` looks as if it should return a
> Boolean corresponding to whether or not the metadata is a system template.
>
> In fact it returns unit, but can raise an exception.
>
> It would be better to name it something like `assert_not_system_template`,
> or change it to return a Boolean and change the calling code from
> ```
> is_system_template metadata;
> ```
> to
> ```
> if is_system_template metadata then raise (IFailure System_template_file);
> ```
>
> (The same goes for the `is...` functions it uses, obviously.)
>
> Also, as Dave says, there should be an explanation of why we forbid import
> of system templates. Dave says this explanation should go in the git commit
> comment. I think it would be useful as a comment in the code as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xapi-project/xen-api/pull/2072#issuecomment-68529597>.
>



-- 
Dave Scott

**Comment by sharady** [comment]
Thanks Dave, for pointing out this situation, I was not aware of these firstboot scripts "create_templates".

However I have tried deleting these templates and then running create_templates with my patch.
"create_templates" successfully restores the templates. From xensource logs it seems "create_templates" uses VM.create calls - this patch should not block these calls.
But I am not able to figure out "from where create_templates script" are generated.

Please correct me if I misunderstood your question.

**Comment by jonludlam** [comment]
@djs55 If we wanted to import the system templates at start of day, we could always (as was pointed out to me by someone) set the other_config key afterwards.

However, before we merge this, I'm interested in why the import actually fails in the first place. Do you know, @sharady?

**Comment by sharady** [comment]
@jonludlam 

There is no "VMRef" created while importing a system template.
There is a precheck condition which returns "Ref.null" which results in no value.

Maybe this code snippet is not performing well.
https://github.com/xapi-project/xen-api/blob/master/ocaml/xapi/import.ml#L285-294

If this is the case then i can fix the existing code.

**Comment by jonludlam** [comment]
@sharady I suspect you're right. It's a different question whether we should do what that code looks like it was designed to do. However, I think this PR is not the right solution today, and so it should be closed. @sharady if you want to fix this in such a way that it returns the reference to the already-created template then please create a new PR for that.

**Pull request closed without merging**
