### PR TITLE
Add some basic unit tests for the HA planner

### PR DESCRIPTION
**Pull request by johnelse**

### CODE REVIEW

**Comment by johnelse** [comment]
No product change - just tests.

**Comment by johnelse** [comment]
Updates:

* Added a test which makes `plan_for_n_failures` return `No_plan_exists`. I haven't found a trivial way of making `plan_for_n_failures` return `Plan_exists_excluding_non_agile_VMs` so I'm going to leave that out for now.
* Gave all the test VMs a VBD to a shared SR, and a VIFto a shared network.

**Comment by thomassa** [comment]
All the code here looks fine to me, but it would be nice to add a couple of tests to the plan_for_n_failures case.

**Comment by thomassa** [comment]
The code all looks good now. Can merge once the tests pass.
(Probably worth squashing the last commit into the first one, as well.)

**Comment by johnelse** [comment]
Merged the refactoring into the earlier commit.

**Comment by johnelse** [comment]
Jenkins build and unit test passed so I'll merge this.

**Pull request merged**
