### PR TITLE
Add VDI.is_tools_iso

### PR DESCRIPTION
**Pull request by robhoes**

### CODE REVIEW

**Comment by johnelse** [comment]
I think it would be nice to pull this logic

```
(List.mem_assoc "xs-tools" vdi.sm_config && List.assoc "xs-tools" vdi.sm_config = "true")
```

out into its own function; otherwise looks good.

**Comment by robhoes** [comment]
@johnelse Thanks. Updated...

**Comment by robhoes** [comment]
xen-git, during testarossa testing:
```
12:54:15 Fatal error: exception Server_error(SR_BACKEND_FAILURE_47, [ ; The SR is not available [opterr=Logical Volume group creation failed];  ])
```

**Comment by robhoes** [comment]
@xen-git re-test this please

**Comment by robhoes** [comment]
Now:
```
15:02:56 Fatal error: exception Server_error(INTERNAL_ERROR, [ Connection failed: good_ciphersuites is unset in the ocaml stunnel module.. ])
```

**Pull request merged**
