### PR TITLE
CP-20344: Sdn set the port number and protocol

### PR DESCRIPTION
**Pull request by liulinC**
Signed-off-by: Lin Liu <lin.liu@citrix.com>

### CODE REVIEW

**Comment by liulinC** [comment]
I have done some basic test about the change.
`import xmlrpclib
import json


class NotEqualError(Exception):
	def __init__(self,message):
		self.message=message
	
class VSwitchContrllerTester():
	def __init__(self,server_addr):
		self.server_addr=server_addr;
		self.xen = xmlrpclib.Server(server_addr)
		self.session = self.xen.session.login_with_password("root", "xenroot")['Value']
		pools=self.xen.pool.get_all(self.session)['Value']
		self.pool=pools[0]

		def __del__(self):
			xen.session.logout(self.session)


	def assert_set_and_get(self,test_controller):
		self.xen.pool.set_vswitch_controller(self.session,test_controller)
		current_controller=self.xen.pool.get_vswitch_controller(self.session,self.pool)['Value']
		if current_controller != test_controller:
			err_msg = "set controller to %s but get %s" %(test_controller,current_controller)
			print err_msg
			raise NotEqualError(err_msg)
	
	def assert_equal(self,target,compare,test_function_name):
		if compare != target:
			err_msg = "test %s: expect %s but get %s" %(test_function_name,target,compare)
			print err_msg
			raise NotEqualError(err_msg)
		else:
			print(test_function_name+" Pass")
			
	def get_current_controller(self):
		return self.xen.pool.get_vswitch_controller(self.session,self.pool)['Value']
		
	def test_backward_compatible(self):
		test_ip="192.168.1.1"
		self.assert_set_and_get(test_ip)
		
	def test_ssl_tcp(self):
		protocol="ssl"
		ip="10.71.216.120"
		port=6632
		target_controller=protocol+":"+ip+":"+str(port)
		self.xen.pool.set_vswitch_controller(self.session,ip,port,protocol)
		result=self.get_current_controller()
		self.assert_equal(target_controller,result,"test_ssl_tcp -->ssl")
		
		protocol="tcp"
		target_controller=protocol+":"+ip+":"+str(port)
		self.xen.pool.set_vswitch_controller(self.session,ip,port,protocol)
		result=self.get_current_controller()
		self.assert_equal(target_controller,result,"test_ssl_tcp-->tcp")
		
		
	def test_pssl_ptcp_with_ip(self):
		protocol="pssl"
		ip="10.71.216.120"
		port=6632
		target_controller=protocol+":"+str(port)+":"+ip
		self.xen.pool.set_vswitch_controller(self.session,ip,port,protocol)
		result=self.get_current_controller()
		self.assert_equal(target_controller,result,"test_pssl_ptcp_with_ip-->pssl")
		
		protocol="ptcp"
		target_controller=protocol+":"+str(port)+":"+ip
		self.xen.pool.set_vswitch_controller(self.session,ip,port,protocol)
		result=self.get_current_controller()
		self.assert_equal(target_controller,result,"test_pssl_ptcp_with_ip-->ptcp")


	def test_pssl_ptcp_no_ip(self):
		protocol="pssl"
		ip=""
		port=6632
		target_controller=protocol+":"+str(port)
		self.xen.pool.set_vswitch_controller(self.session,ip,port,protocol)
		result=self.get_current_controller()
		self.assert_equal(target_controller,result,"test_pssl_ptcp_no_ip-->pssl")
		
		protocol="ptcp"
		target_controller=protocol+":"+str(port)
		self.xen.pool.set_vswitch_controller(self.session,ip,port,protocol)
		result=self.get_current_controller()
		self.assert_equal(target_controller,result,"test_pssl_ptcp_no_ip-->ptcp")
	
	def test_invalid_protocol(self):
		protocol="abc"
		ip="192.168.1.1"
		port=6632
		try:
			result=self.xen.pool.set_vswitch_controller(self.session,ip,port,protocol)
			assert result['Status']=='Failure'
			error_desc=result['ErrorDescription']
			assert error_desc[0] == "VALUE_NOT_SUPPORTED" and error_desc[1]=="protocol"
			print "test test_invalid_protocol pass"
		except Exception:
			print "test test_invalid_protocol failed"
			
	def test_invalid_port(self):
		protocol="ssl"
		ip="192.168.1.1"
		port=65536
		try:
			result=self.xen.pool.set_vswitch_controller(self.session,ip,port,protocol)
			assert result['Status']=='Failure'
			error_desc=result['ErrorDescription']
			assert error_desc[0] == "VALUE_NOT_SUPPORTED" and error_desc[1]=="port"
			print "test test_invalid_port pass"
		except Exception:
			print "test test_invalid_port failed"
			
	def test_invalid_ip(self):
		protocol="ssl"
		ip="192.1"
		port=6632
		try:
			result=self.xen.pool.set_vswitch_controller(self.session,ip,port,protocol)
			assert result['Status']=='Failure'
			error_desc=result['ErrorDescription']
			assert error_desc[0] == "INVALID_IP_ADDRESS_SPECIFIED" and error_desc[1]=="address"
			print "test test_invalid_ip pass"
		except Exception:
			print "test test_invalid_ip failed"
			
			
		
tester = VSwitchContrllerTester("https://10.71.71.33:443")
tester.test_backward_compatible()
tester.test_ssl_tcp()
tester.test_pssl_ptcp_with_ip()
tester.test_pssl_ptcp_no_ip()
tester.test_invalid_protocol()
tester.test_invalid_port()
tester.test_invalid_ip()
`

**Comment by liulinC** [comment]
I have done some basic test about it.

import xmlrpclib
import json


class NotEqualError(Exception):
	def __init__(self,message):
		self.message=message
	
class VSwitchContrllerTester():
	def __init__(self,server_addr):
		self.server_addr=server_addr;
		self.xen = xmlrpclib.Server(server_addr)
		self.session = self.xen.session.login_with_password("root", "xenroot")['Value']
		pools=self.xen.pool.get_all(self.session)['Value']
		self.pool=pools[0]

		def __del__(self):
			xen.session.logout(self.session)


	def assert_set_and_get(self,test_controller):
		self.xen.pool.set_vswitch_controller(self.session,test_controller)
		current_controller=self.xen.pool.get_vswitch_controller(self.session,self.pool)['Value']
		if current_controller != test_controller:
			err_msg = "set controller to %s but get %s" %(test_controller,current_controller)
			print err_msg
			raise NotEqualError(err_msg)
	
	def assert_equal(self,target,compare,test_function_name):
		if compare != target:
			err_msg = "test %s: expect %s but get %s" %(test_function_name,target,compare)
			print err_msg
			raise NotEqualError(err_msg)
		else:
			print(test_function_name+" Pass")
			
	def get_current_controller(self):
		return self.xen.pool.get_vswitch_controller(self.session,self.pool)['Value']
		
	def test_backward_compatible(self):
		test_ip="192.168.1.1"
		self.assert_set_and_get(test_ip)
		
	def test_ssl_tcp(self):
		protocol="ssl"
		ip="10.71.216.120"
		port=6632
		target_controller=protocol+":"+ip+":"+str(port)
		self.xen.pool.set_vswitch_controller(self.session,ip,port,protocol)
		result=self.get_current_controller()
		self.assert_equal(target_controller,result,"test_ssl_tcp -->ssl")
		
		protocol="tcp"
		target_controller=protocol+":"+ip+":"+str(port)
		self.xen.pool.set_vswitch_controller(self.session,ip,port,protocol)
		result=self.get_current_controller()
		self.assert_equal(target_controller,result,"test_ssl_tcp-->tcp")
		
		
	def test_pssl_ptcp_with_ip(self):
		protocol="pssl"
		ip="10.71.216.120"
		port=6632
		target_controller=protocol+":"+str(port)+":"+ip
		self.xen.pool.set_vswitch_controller(self.session,ip,port,protocol)
		result=self.get_current_controller()
		self.assert_equal(target_controller,result,"test_pssl_ptcp_with_ip-->pssl")
		
		protocol="ptcp"
		target_controller=protocol+":"+str(port)+":"+ip
		self.xen.pool.set_vswitch_controller(self.session,ip,port,protocol)
		result=self.get_current_controller()
		self.assert_equal(target_controller,result,"test_pssl_ptcp_with_ip-->ptcp")


	def test_pssl_ptcp_no_ip(self):
		protocol="pssl"
		ip=""
		port=6632
		target_controller=protocol+":"+str(port)
		self.xen.pool.set_vswitch_controller(self.session,ip,port,protocol)
		result=self.get_current_controller()
		self.assert_equal(target_controller,result,"test_pssl_ptcp_no_ip-->pssl")
		
		protocol="ptcp"
		target_controller=protocol+":"+str(port)
		self.xen.pool.set_vswitch_controller(self.session,ip,port,protocol)
		result=self.get_current_controller()
		self.assert_equal(target_controller,result,"test_pssl_ptcp_no_ip-->ptcp")
	
	def test_invalid_protocol(self):
		protocol="abc"
		ip="192.168.1.1"
		port=6632
		try:
			result=self.xen.pool.set_vswitch_controller(self.session,ip,port,protocol)
			assert result['Status']=='Failure'
			error_desc=result['ErrorDescription']
			assert error_desc[0] == "VALUE_NOT_SUPPORTED" and error_desc[1]=="protocol"
			print "test test_invalid_protocol pass"
		except Exception:
			print "test test_invalid_protocol failed"
			
	def test_invalid_port(self):
		protocol="ssl"
		ip="192.168.1.1"
		port=65536
		try:
			result=self.xen.pool.set_vswitch_controller(self.session,ip,port,protocol)
			assert result['Status']=='Failure'
			error_desc=result['ErrorDescription']
			assert error_desc[0] == "VALUE_NOT_SUPPORTED" and error_desc[1]=="port"
			print "test test_invalid_port pass"
		except Exception:
			print "test test_invalid_port failed"
			
	def test_invalid_ip(self):
		protocol="ssl"
		ip="192.1"
		port=6632
		try:
			result=self.xen.pool.set_vswitch_controller(self.session,ip,port,protocol)
			assert result['Status']=='Failure'
			error_desc=result['ErrorDescription']
			assert error_desc[0] == "INVALID_IP_ADDRESS_SPECIFIED" and error_desc[1]=="address"
			print "test test_invalid_ip pass"
		except Exception:
			print "test test_invalid_ip failed"
			
			
		
tester = VSwitchContrllerTester("https://10.71.71.33:443")
tester.test_backward_compatible()
tester.test_ssl_tcp()
tester.test_pssl_ptcp_with_ip()
tester.test_pssl_ptcp_no_ip()
tester.test_invalid_protocol()
tester.test_invalid_port()
tester.test_invalid_ip()

**Comment by liulinC** [comment]
I have done some basic test about it the the test script is available from
https://issues.citrite.net/secure/attachment/1096964/test_vswitch_controller.py

**Comment by jonludlam** [comment]
Would it not make sense to have protocol as an enum rather than a string that has to be checked in the code?

**Comment by robhoes** [comment]
I am still reviewing the design for this feature, so won't comment on the code yet. But in any case, this should be a PR to a feature branch, not master.

**Comment by liulinC** [comment]
@jonludlam, It is make sense to use enum type,
I will changed it and pull to feature branch, 
please help to review it.
thanks.

**Comment by liulinC** [comment]
updated PR to feature branch link
https://github.com/xapi-project/xen-api/pull/2921

**Pull request closed without merging**
