### PR TITLE
tests: Move test_highlevel.ml and test_printers.ml to xapi-test-utils…

### PR DESCRIPTION
**Pull request by robhoes**
… package

This package is in its own repo (xapi-test-utils.git), so that we can easily
make use of the unit test facilities in other xapi daemons.

Signed-off-by: Rob Hoes <rob.hoes@citrix.com>

### CODE REVIEW

**Comment by robhoes** [comment]
Depends on https://github.com/xenserver/xen-api-base-specs/pull/49.

**Comment by robhoes** [comment]
@xen-git re-test this please

**Comment by robhoes** [comment]
Xen-git is now happy with this patch. Travis is not, but that is because the SRPM repo is out of date.

**Comment by robhoes** [comment]
@johnelse What do you think?

**Comment by johnelse** [comment]
I think :shipit: :shipit:

**Pull request merged**
