### PR TITLE
RFC, Untested: CA-175353: resync networking after VMs have been resynced

### PR DESCRIPTION
**Pull request by djs55**
When performing a bond/VLAN resync we need the ability to call the
xenopsd VIF.move API to move the backend device onto the right
bridge or switch. Previously these attempts would block because
the events from xenopsd thread wasn't running. To start the
events from xenopsd thread we need to have resynchronised the VM
state, which also requires the storage to be online.

Note this makes the case where a resync is done after a `service
xapi restart` on a live system, with plugged storage and running
VMs, more similar to the case where a resync is done after a
reboot.

Signed-off-by: David Scott <dave.scott@citrix.com>

### CODE REVIEW

**Comment by robhoes** [comment]
Argg.... another Startup-Sequence Ordering Problem (SSOP)?

**Comment by djs55** [comment]
I should have cc:d you, or better yet used one of these:

**Comment by robhoes** [comment]
Don't worry: I have a nose for this kind of thing....

**Comment by jonludlam** [comment]
@djs55 - what, if anything, do you think we can do to validate this before merging? If there's nothing obvious, we should just merge and BST immediately... :-)

**Comment by jonludlam** [comment]
OK, I'm going to speculatively merge this, give we've just done a push to trunk. If we find any regressions during tests we can fix/backout as necessary.

**Pull request merged**
