### PR TITLE
Update Travis: Get dependencies from ely-bugfix branch

### PR DESCRIPTION
**Pull request by Frezzle**

### CODE REVIEW

**Comment by gaborigloi** [comment]
Why do we have both this and the `ely-bugfix` branch in `xenserver`?

**Comment by Frezzle** [comment]
@gaborigloi Good question; my guess is that since Ely is coming with us into the new world we are also taking it's lcm branches to xapi-project, but I'm not sure. @robhoes ?

**Comment by robhoes** [comment]
@Frezzle Yes, I think we should forget about the ely-bugfix branches on github.com/xenserver, and have the LCM branches in the same place as the master branch.

**Comment by Frezzle** [comment]
@robhoes Great - just to confirm: LCM/bugfix branches for Dundee and earlier will remain on github.com/xenserver ?

**Pull request merged**
