### PR TITLE
CA-227062: Fix cli selector fns for host, vm, sr

### PR DESCRIPTION
**Pull request by mseri**
This fix reorders the checks when using the `host=` and `vm=` slectors in the calls to `xe host-...` and `xe vm-...` to make sure that the eventual call `get_by_uuid` is done only after `name-label` (and for hosts also `hostname`) has been checked first.

This avoid the appearance of a spurious backtrace. Also fixes a minor issue that could prevent a confusing lookup if `hostname` and `name-label` are out of sync (they are synced on start but `name-label` can be easily modified and this would not be reflected in the `hostname`).

### CODE REVIEW

**Comment by thomassa** [comment]
I've made a start at reading through these changes.

In the mean time, the title of the pull-request itself is misleading: it sounds as if the query function throws an exception about logging, whereas in fact it just logs a description of an exception that it handles.
Trying to make it as short as possible, I suggest
`CA-227062: host-data-source-query logs dud exception`

**Comment by thomassa** [comment]
The `do_filter` part of `select_hosts` is nice and clean and straightforward, but then handling the `host=` part of the user-supplied query is awkward and cumbersome. Also, it is poorly specified:

> The simplest way to select the host on which the operation is to be performed is by supplying the argument 'host=<name or uuid>'. Hosts can also be specified by filtering the full list of hosts on the values of fields. For example, specifying 'enabled=true' will select all hosts whose 'enabled' field is equal to 'true'. Where multiple hosts are matching, and the operation can be performed on multiple hosts, the option '--multiple' must be specified to perform the operation. The full list of fields that can be matched can be obtained by the command 'xe host-list params=all'. If no parameters to select hosts are given, the operation will be performed on all hosts.

There is no parameter (no field) called `name` so it is unclear whether this means `hostname` or `name-label` or both.
It is unclear what is meant to happen if `host=` is supplied along with other (real) fields.

I don't know why the existing code uses
`let hosts = Client.Host.get_all_records_where rpc session_id "true"`
rather than just
`let hosts = Client.Host.get_all_records rpc session_id`
but I think a cleaner way to implement the whole thing would be something like this:
```
  let select_hosts rpc session_id params ignore_params =
    let let host_name_or_ref = try Some (List.assoc "host" params) with _ -> None in
    let params, where_clause = match host_name_or_ref with
      | None -> params, "true"
      | Some v -> (
          List.remove_assoc "host" params,
          Printf.sprintf "(field \"uuid\"=\"%s\") or (field \"hostname\"=\"%s\") or (field \"name_label\"=\"%s\")" v v v
        )
    in
    let hosts = Client.Host.get_all_records_where rpc session_id where_clause in
    ...
```
...and then carrying on as before with the rest of the content of what is currently the `do_filter` function.
Then we would not need any of the rest of the current `select_hosts` function (i.e. everything after the definition of `do_filter`).

The behaviour here would be slightly different from the existing behaviour, but more reasonable: someone who types at the command-line
`xe host-list enabled=true host=host123` or
`xe host-list enabled=true host=f51296c6-ac53-404a-b341-d5fd29510e86`
would reasonably expect to see only hosts that are enabled.
The current code would comply with that for the name-label case (and the hostname case after your change) but not for the uuid case.

We should definitely clarify the text that describes the "host-selectors" behaviour, making it more specific.
This is defined in the `hostselectorsinfo` variable in `ocaml/xapi/cli_frontend.ml`.

**Comment by mseri** [comment]
I completely agree with you.

I am going to refactor the solution following your suggestions. I was not aware of get_all_records_where, this would avoid also the backtrace that I had missed (it would also help to  solve the issue of spurious backtraces in other parts of xapi but that is not relevant for this pr). 

I will also reword the help message trying to make it more clear and explicit. 

I will update the PR after I have tested the new code

**Comment by mseri** [comment]
While working on the fix, I've found the same issue also in `select_srs`.

**Comment by mseri** [comment]
Updated. As mentioned before, I had to strip out the comments because `"` and `\` where crashing a `scan` pass of the compilation. Also `name-label` is serialized in the database as `name__label` (with double underscore).

**Comment by thomassa** [comment]
This looks pretty good now.
There are some minor changes that I feel would make it a litte better though.
Each of the `select_xyz` functions now ends with
```
let do_filter params =
    <body>
in
do_filter params
```
which could be simplified to just
```
<body>
```

Given the final nature of the overall change in the pull-request, I think its first-line summary would be better as something like `CA-227062: Fix cli selector fns for host, vm, sr.`

**Comment by thomassa** [comment]
This is good to merge after squashing.
(Though when there are only two items, it is usual to say "either of" rather than "any of" them.)

**Comment by mseri** [comment]
Thanks. I've fixed the `either of`s before squashing

**Comment by mseri** [comment]
Merge agreed together during the sprint planning

**Pull request merged**
