### PR TITLE
Further improvements to pass traceparent `XenAPI.py`

### PR DESCRIPTION
**Pull request by GabrielBuica**
Follow-up to: https://github.com/xapi-project/xen-api/pull/5639.

This attempts to instrument non-local `XenAPI.py`  sessions.

### CODE REVIEW

**Comment by GabrielBuica** [comment]
Passes BVT+BST 199742 & 199740, all components enabled and no tracing, respectively

**Comment by mg12** [comment]
after looking at the PR, this is my attempt to summarize the changes, @GabrielBuica are these correct?
* the PR #5639 applied only to UDSTransport (local_login)
* this PR is more generic, and it applies to anything derived from Transport (so it includes UDSTransport, SafeTransport and of course Transport)
* the new behaviour is only present if otel=true (ie both OTEL_SDK_DISABLED=false and required open-telemetry libs are present)

**Comment by GabrielBuica** [comment]
That's correct @mg12!

**Comment by psafont** [comment]
Could the explanation be added also to the commit message?

**Comment by GabrielBuica** [comment]
Sure, I'll update the commit message as well.

**Comment by GabrielBuica** [comment]
Updated the commit message.

**Comment by GabrielBuica** [comment]
I'll changed it to draft for the time being. With the changes from feature/perf merged, we are now reusing the initial connection, therefore subsequent spans of xapi requests appear in the under the wrong parent.

**Comment by psafont** [comment]
Can this PR be closed? Looks like it's not useful anymore

**Comment by GabrielBuica** [comment]
> Can this PR be closed? Looks like it's not useful anymore

The purpose of it is still the same: to be the general version of https://github.com/xapi-project/xen-api/pull/5639. 

I will close it for now and keep the code on my branch (in case someone asks for it).

**Pull request closed without merging**
