### PR TITLE
CA-145540: Restrict VDI snapshot during VDI copy

### PR DESCRIPTION
**Pull request by simonjbeaumont**
This is a forward port of https://github.com/xapi-project/xen-api/pull/1970 which missed the last release's window.

### CODE REVIEW

**Comment by simonjbeaumont** [comment]
This is failing the unit tests:

==============================================================================
Failure: base_suite:5:test_vdi_allowed_operations:3:test_ca126097

OUnit: expected: Some (OPERATION_NOT_ALLOWED, []) but got: None
------------------------------------------------------------------------------
Ran: 67 tests in: 1.95 seconds.
FAILED: Cases: 67 Tried: 67 Errors: 0 Failures: 1 Skip:6 Todo:0

**Comment by ravippandey** [comment]
@xen-git test this please

**Comment by ravippandey** [comment]
@simonjbeaumont i think following check needs to be removed for this to pass.
https://github.com/xapi-project/xen-api/blob/creedence-bugfix/ocaml/test/test_vdi_allowed_operations.ml#L188-L195

**Comment by johnelse** [comment]
@ravippandey I would prefer we fixed the test to test the new behaviour, rather than removing it.

n.b. the previous unit test failures may have been part of the recent GPU passthrough changes (now fixed).

**Comment by johnelse** [comment]
This needs some fixes to the unit tests, which went in as part of the CA-143836 fix but then got reverted.

See https://github.com/xapi-project/xen-api/pull/2156

**Comment by simonjbeaumont** [comment]
I have just cherry-picked these changes into this pull request. I await @xen-git's response...

**Comment by johnelse** [comment]
@xen-git likes it!

**Pull request merged**
