### PR TITLE
Reinstate CA-187693: Handle unmapped VIFs and VDIs correctly

### PR DESCRIPTION
**Pull request by simonjbeaumont**
This pull request needs to be on-hold until QA update their test cases. It is also more lenient w.r.t. intra-pool migration.

### CODE REVIEW

**Comment by simonjbeaumont** [comment]
This is reinstating #2529 with an addtional commit (e6a66d1)

**Comment by simonjbeaumont** [comment]
@jonludlam there's one extra patch in addition to what's already been reviewed above: e6a66d1.

**Comment by euanh** [comment]
https://github.com/xapi-project/xen-api/commit/e6a66d149c10d03e49e5ee25a0fa1fa3fc024f18 looks good to me. :shipit:

**Comment by simonjbeaumont** [comment]
@xen-git: retest this please. (I'll give the output RPM from the Jenkins job to QA to see which TCs need updating)

**Comment by simonjbeaumont** [comment]
@xen-git: retest this please.

**Comment by thomassa** [comment]
"Unmapped VIFs and VIFs"... should that be VIfs and VBDs?

**Comment by simonjbeaumont** [comment]
@thomassa said:
> "Unmapped VIFs and VIFs"... should that be VIfs and VBDs?

Ah yes. It should be VIFs and VDIs. I'll change that. Just in the title of the PR by the looks of things.

**Pull request merged**
