### PR TITLE
CA-360485: Fix SR-IOV capability detection

### PR DESCRIPTION
**Pull request by robhoes**
Always require that the device has declared SR-IOV support in sysfs.
This is independent of the way that SR-IOV would eventually be enabled
for the NIC, which may be through either of the "sysfs" or "modprobe"
methods, as before.

Signed-off-by: Rob Hoes <rob.hoes@citrix.com>

### CODE REVIEW

**Comment by robhoes** [comment]
@idruzhinin I think that this is the safest way to fix the problem. What do you think?

**Comment by idruzhinin** [comment]
IMO get_config_from_comments  was always wrong and no longer needed. Max number of VFs should be taken from sysfs file.

**Comment by robhoes** [comment]
Unfortunately, it is a documented manual way to set maxvfs (setting `VFs-maxvfs-by-user`), and it is used by the "enable" function as well. The fix the current bug, I would preserve this. We can have a separate discussion about the future modprobe thing.

**Comment by idruzhinin** [comment]
Maybe we have to keep it - I'm looking at the driver now and it does not allow setting max_vfs higher than 7 while the hardware says it's capable of 8.

**Comment by robhoes** [comment]
Igor helped to verify the fix, so I've now declared it "ready".

**Review by psafont — APPROVED** [review]

**Review by edwintorok — APPROVED** [review]

**Pull request merged**
