### PR TITLE
CP-25141 SCTX-2619 fix sync from xenopsd in on_xapi_restart

### PR DESCRIPTION
**Pull request by lindig**
When xapi starts, it queries xenopsd about the state of local VMs. In
SCTX-2619 we found that xenopsd passed data about a VM that was *not*
resident locally but was left over from a previous failed migration to
local host. This data was erroneously used to reset the power state of
that non-local VM. This commit fixes this.

If xenopsd reports the VM as running, it must indeed be resident on the
local host - so we reset the state of the VM to what xenopsd is
reporting.

If xenopsd reports the VM as suspended or halted, we only reset the
state of the VM if xapi believes the VM is resident on localhost.
Previously it would reset the state regardless - which caused the error.

Signed-off-by: Christian Lindig <christian.lindig@citrix.com>

### CODE REVIEW

**Comment by jonludlam** [comment]
Is there adequate logging here? If force_state_reset doesn't log, we should make this function do more logging.

**Comment by lindig** [comment]
I'll add `info` log lines.

**Comment by lindig** [comment]
I made a second commit that adds logging on my branch but it does not show up here. https://github.com/lindig/xen-api/commit/1d0eb3feaa5532be3e966ed1e0a4133f183956d3

**Comment by lindig** [comment]
There is some GitHub glitch here as is does not update the PR. Closing this and opening it again.

**Pull request closed without merging**
