### PR TITLE
CPU Feature Levelling v2: alerts

### PR DESCRIPTION
**Pull request by robhoes**

### CODE REVIEW

**Comment by simonjbeaumont** [comment]
@xen-git test this please.

**Comment by simonjbeaumont** [comment]
@xen-git: retest this please.

**Comment by simonjbeaumont** [comment]
PLEEEEEEAAAASE!!!

**Comment by simonjbeaumont** [comment]
@xen-git: thanks.

**Comment by simonjbeaumont** [comment]
Looks good apart from the backtrace laundering.

**Comment by robhoes** [comment]
@simonjbeaumont I've addressed the laundering.

**Comment by simonjbeaumont** [comment]
Looks good. Leave it up to you whether you squash https://github.com/robhoes/xen-api/commit/a1f25d1f01d49e6385e9af8e50b431faf58c18a0 into https://github.com/robhoes/xen-api/commit/acbb12d1483a995a918db5f4e3c4f4de8b7f7626.

**Comment by robhoes** [comment]
:cool:, thanks. I'll do the squashing in the PR for master, where there is more squashing to do.

**Pull request merged**
