### PR TITLE
VM.update_allowed_operations: cache some common values when checking operation errors in a loop

### PR DESCRIPTION
**Pull request by gaborigloi**
By specialising the function for a given VM.

Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>

### CODE REVIEW

**Comment by gaborigloi** [comment]
:warning: I have checked the code, and realized that there are even more values we could extract this way, possibly combined with `lazy` (which is not thread safe, but should be okay in this case), will try that when I get a chance.

**Comment by gaborigloi** [comment]
This should undo the performance greression I introduced in https://github.com/xapi-project/xen-api/pull/3056

**Comment by gaborigloi** [comment]
The changes are minimal, it's best to view them with `git` and the `--color-words` option.

**Comment by lindig** [comment]
That's cool. I would have liked the explanation @gaborigloi gave me in the commit message. The idea is to to use partial evaluation of arguments and by this avoiding re-evaluation when only remaining arguments are applied. I'll have to take another look to understand what is going on.

**Comment by jonludlam** [comment]
Ah, this is neat. Looks good to me!

**Comment by gaborigloi** [comment]
I've update the commit message, but GitHub did not pick up the change. I'll close this PR and reopen it as a new one.

**Comment by gaborigloi** [comment]
New PR is: https://github.com/xapi-project/xen-api/pull/3301

**Pull request closed without merging**
