### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by johnelse**

### CODE REVIEW

**Comment by jonludlam** [comment]
Ah, the fast-becoming-traditional typo-fixing last PR :-)

**Comment by johnelse** [comment]
Indeed :-) I think I can get away without dev testing this one...

**Comment by robhoes** [comment]
Have you been collecting these over the years?

**Comment by robhoes** [comment]
Oh go on then :trollface:

**Comment by johnelse** [comment]
Actually this is only about 6 months' worth :stuck_out_tongue:

**Pull request merged**
