### PR TITLE
Test commit, do not merge!

### PR DESCRIPTION
**Pull request by euanh**
Signed-off-by: Euan Harris <euan.harris@citrix.com>

### CODE REVIEW

**Comment by johnelse** [comment]
:horse:

**Comment by euanh** [comment]
@xen-git Retest this please

**Comment by euanh** [comment]
@xen-git retest this please

**Comment by euanh** [comment]
@xen-git retest this please

**Comment by euanh** [comment]
@xen-git retest this please

**Comment by simonjbeaumont** [comment]
@euanh I assume we're done with this now.

**Pull request closed without merging**
