### PR TITLE
Define cream in trunk

### PR DESCRIPTION
**Pull request by thomassa**
Define creedence_cream in datamodel, and change augusta to dundee.

Update last_release_schema_(major|minor)_version in datamodel.

### CODE REVIEW

**Comment by robhoes** [comment]
Good idea, but perhaps just use `cream` rather than `creedence_cream` for simplicity? There is a precedent for a SP release with a simple name: `cowley`.

**Comment by thomassa** [comment]
True, but we also have the precedents of `clearwater_felton` and `clearwater_whetstone`.

As for simplicity or otherwise, there's a trade-off: I think `cream` is more convenient than `creedence_cream` now and for the rest of the year, but further into the future the additional context of the `creedence_` prefix will be useful for those who don't remember what Cream was.

**Comment by robhoes** [comment]
True, but felton and whetstone were hotfixes, the names of which as much more obscure. I suspect that Cream is going to remembered as well as Creedence itself :)

**Comment by jonludlam** [comment]
I prefer just 'cream' too

**Comment by thomassa** [comment]
Sigh. I've changed it to `cream` now. (Maybe `creedence_sp1` would have been best...)

**Pull request merged**
