### PR TITLE
CAR-1744: add support for running in-guest user scripts

### PR DESCRIPTION
**Pull request by zli**
This pull req implements a vm plugin to run in-guest scripts provided by users. See REQ-103 (ScaleXtreme PR) for the actual requirements.

### CODE REVIEW

**Comment by jonludlam** [comment]
I think it would be better if the xenopsd was doing the actual xenstore manipulations - it's the only thing that can safely do it without fear of writing into the wrong place in xenstore. Also, we're trying to remove the last few calls to xenstore from within xapi.

**Comment by zli** [comment]
@jonludlam The reason we didn't pump through xenopsd was that the current implementation doesn't do anything low level other than just xenstore read/write. In theory the same function can be implemented as a 3rd party plugin using xenstore directly. 

Also the current implementation is meant to be a temporary mechanism based on xenstore communication.  The future version using different mechanism would require totally different interaction pattern with xenopsd. Just wanted to avoid leaving holes on the interface, but if you believe that's better to go via xenopsd,  I can try to make an update.

**Comment by simonjbeaumont** [comment]
The pull request title and description body persist in the git history. Can these be made more descriptive please? :)

**Comment by jonludlam** [comment]
Yes, we'd like this to go through xenopsd rather than have xapi do the xenstore operations (as discussed f2f).

**Comment by zli** [comment]
I'll work on a revision using xenopsd next week.

One problem I bumped into was: we need to use xenopsd's  Async/Task mechanism so that a task cancellation can be dump through from xapi to xenopsd; meanwhile we'll also need to get the actual result (data given back by the guest agent) of that task upon success --- this is unfortunately not the case with current xenopsd implementation, as the result of a task is always discarded (None):

https://github.com/xapi-project/xenopsd/blob/master/lib/xenops_server.ml#L1529

This is fine for the current operation set, as their return type is uniformly unit/void, as in

https://github.com/xapi-project/xcp-idl/blob/master/xen/xenops_interface.ml#L492

To make use of the task result and potentially support any operation that demands a result, the result type needs to be generic. I've discussed this with Dave, it seems that the best way to do this (without getting into too much trouble) is to use Rpc.t instead of unit, functions along the route (xcp-idl/xenopsd/xapi) will need to update to make this happen.

**Comment by zli** [comment]
Updated, now depends on xapi-project/xcp-idl#95 and xapi-project/xenopsd#210

**Pull request merged**
