### PR TITLE
Add SR Multipath capability

### PR DESCRIPTION
**Pull request by MarkSymsCtx**
Signed-off-by: Mark Syms <mark.syms@citrix.com>

### CODE REVIEW

**Comment by jonludlam** [comment]
Fancy adding some tests similar to https://github.com/xapi-project/xen-api/commit/4cbad0d2dabe05d54267000f2bfd5098bc131958 ?

**Comment by MarkSymsCtx** [comment]
Yep, will do

**Comment by edwintorok** [comment]
How should XAPI behave when an SR does not support multipath? Should we add some checks when enabling/disabling multipath and plugging the PBDs?

**Comment by MarkSymsCtx** [comment]
This is (at least at the moment) expected to be transparent to Xapi but used by XenCenter

**Pull request merged**
