### PR TITLE
CP-12398 - Add Intel GVT-g support

### PR DESCRIPTION
**Pull request by johnelse**

### CODE REVIEW

**Comment by euanh** [comment]
@johnelse: Should we arrange a group walk through of this pull request, like the one we did for storage motion?

**Comment by jonludlam** [comment]
@euanh I agree. You're good at booking meetings... :-)

**Comment by johnelse** [comment]
[This value](https://github.com/johnelse/xen-api/blob/4c6edc38a6662c454166246a7c058b4aa0c57fd3/ocaml/xapi/xapi_vgpu_type.ml#L34) should be renamed to `passthrough_gpu`.

**Comment by johnelse** [comment]
Like that!

**Pull request merged**
