### PR TITLE
CA-223505 detach a VM's network (PVS) when migrating away from a host

### PR DESCRIPTION
**Pull request by lindig**
This commit hooks Network.detach_for_vm() into
VM.atomic_set_resident_on() to ensure that a VM's network is detached
when a VM is migrating away from a host.

Signed-off-by: Christian Lindig <christian.lindig@citrix.com>

### CODE REVIEW

**Comment by lindig** [comment]
From the ticket: 

> After migration, the source side does not detach the PVS proxy from the VM that this no longer there. This means the Xapi database is in the wrong state and (not sure about this) network traffic is still directed towards a VM that does not exist any more. [..] The root of the problem is here: xenops events are suppressed on the source side and the the code that does the detach is never reached.
> 
> https://github.com/xapi-project/xen-api/blob/master/ocaml/xapi/xapi_xenops.ml#L1667
 
This has been tested on a pool observing that the network detach is actually executed when a VM migrates away from a host (be it a slave or the master).

**Comment by jonludlam** [comment]
We're already calling 'attach networks' in the block of code in which the events are suppressed - I think it might be better to be doing the symmetric detach in the same place:

https://github.com/xapi-project/xen-api/blob/master/ocaml/xapi/xapi_vm_migrate.ml#L193

**Comment by lindig** [comment]
I'm not sure that this solves the problem. After a migration inside a pool, I can't see any of the log messages from the `try` block in `pool_migrate`. I also suspect that we would miss cross-pool migration.

**Comment by lindig** [comment]
I have updated the PR - the code is now in `migrate_send` and it is correctly executed on the source side at the end of a migration. I've verified migrating machines in a pool to do trigger and local-host migration to not trigger the detach.

**Comment by jonludlam** [comment]
Hmm, I think we also want the code in pool_migrate as well - sorry if I didn't make that clear.

**Comment by lindig** [comment]
I've updated the PR - now the code (as a function call) is in both places. Will test it again just to be sure.

**Comment by jonludlam** [comment]
Looks good!

**Pull request merged**
