### PR TITLE
Undeprecate VM.create

### PR DESCRIPTION
**Pull request by robhoes**
Signed-off-by: Rob Hoes <rob.hoes@citrix.com>

### CODE REVIEW

**Comment by jonludlam** [comment]
looks good to me!

**Comment by pauldu** [comment]
Why has this been done? We agreed that VM.create should be deprecated.

**Comment by jonludlam** [comment]
We agreed mainly on the basis that it was causing problems for the has-vendor-device field, and on the assumption that most clients use clone/provision of templates. We now know for sure that many many clients are using VM.create. Since it's now not fundamentally broken (CA-208836), and there's no replacement for it, I think it shouldn't be deprecated. We've also got a plan for making it not horrific to use (see e.g. https://github.com/xapi-project/xen-api/blob/master/ocaml/test/has_vendor_device_test.py#L12 for an example of what has to be passed to create today).

**Comment by pauldu** [comment]
I thought we agreed that VM.create was broken in principle in that, because the set of parameters is not versioned, there's no way to choose sensible defaults for parameters that are missing. If we dodged a bullet with has-vendor-device then we probably got lucky.

**Comment by jonludlam** [comment]
xapi _must_ be able to supply suitable default for missing parameters - otherwise upgrade wouldn't work. In this case, there was just a conflict with this desired behaviour and the product requirements, which we have now fixed.

**Comment by pauldu** [comment]
Agreed. But what's to say you're going to be able to divine suitable defaults in future?

**Comment by jonludlam** [comment]
Otherwise all VMs in the database are toast! Because we need to support this, we must be able to fill in defaults for unspecified fields. And because we have to do that, we might as well apply the same logic to VM.create.

**Pull request merged**
