### PR TITLE
Modify xapi.opam for AlpineLinux

### PR DESCRIPTION
**Pull request by Bobberty**
Added an OS package dependency line for AlpineLinux.

### CODE REVIEW

**Review by psafont — APPROVED** [review]

**Comment by psafont** [comment]
Thanks! Could you please add sign-offs to the commit messages?

This can be done by running `git rebase master --signoff`

**Comment by lindig** [comment]
@Bobberty could you sign off your commits, please, such that we can merge this?

**Comment by psafont** [comment]
hwids is unmaintained and will be replaced by hwdata: https://gitlab.alpinelinux.org/alpine/aports/-/issues/14188

**Comment by lindig** [comment]
What is the state of this? It looks it could be merged but there is a comment from @psafont that could suggest otherwise.

**Comment by lindig** [comment]
@Bobberty please rebase and sign-off your commit. We won't merge it otherwise.

**Comment by psafont** [comment]
I'll push the change here, hwids is not used anymore in alpine and uses hwdata, the same package as the rest of the distributions

**Pull request merged**
