### PR TITLE
CA-186158: Make VM.auto_update_drivers a StaticRO field

### PR DESCRIPTION
**Pull request by johnelse**
This enables API clients to set it when creating a VM.

### CODE REVIEW

**Comment by johnelse** [comment]
Untested - I will test it once Jenkins has built me some RPMs.

**Comment by simonjbeaumont** [comment]
Looks sane, await the results of the dev-testing.

**Comment by robhoes** [comment]
Jon, didn't you do this last week as well?

**Comment by johnelse** [comment]
@robhoes yes - @thomassa said it would be useful after all.

**Comment by johnelse** [comment]
@xen-git test this please

**Comment by simonjbeaumont** [comment]
Needs rebasing on master. The function called in `Xapi_sr`, `Rrdd.push_sr_rrd`, now takes an extra argument since https://github.com/xapi-project/xen-api/commit/a74cdca594e94ba043886445c52c79939509e9fb:

The version in your commit passes only one:
https://github.com/johnelse/xen-api/blob/a1fa627c3fe56efdbfe0a062a5f84c5b249cebc5/ocaml/xapi/xapi_sr.ml#L622

Resulting in the error we see in xen-git:
```
18:10:08 File "xapi_sr.ml", line 623, characters 4-20:
18:10:08 Error: This function has type sr_uuid:string -> unit Rrdd.RPCM.t
18:10:08        It is applied to too many arguments; maybe you forgot a `;'.
```

**Comment by johnelse** [comment]
@xen-git test this please

**Comment by johnelse** [comment]
I can confirm this does fix the original issue, however it breaks the BVT. I'll discuss offline with @benchalmers what to do with this fix.

**Comment by johnelse** [comment]
This change has gone in via the trunk-windows branch, so I'll close this PR.

**Pull request closed without merging**
