### PR TITLE
Absorb ezxenstore 😎

### PR DESCRIPTION
**Pull request by psafont**
This allows us to stop packaging xenctrl in xs-opam's tarball, we need to maintain a shim there to enable devs to compile xapi locally.

### CODE REVIEW

**Comment by psafont** [comment]
I'm afraid I can't do much about the DCO check other than manually override it when it's time to merge

**Comment by psafont** [comment]
Overriding DCO check:

> Commit sha: [1d27213](https://github.com/xapi-project/xen-api/pull/4938/commits/1d27213e79d220632902dc4f0e1236ec93606b0d), Author: Marcello Seri, Committer: GitHub; The sign-off is missing.

This is a commit reverting another one, an easy case to miss the sign-off. I don't think it matters

**Comment by lindig** [comment]
Is this merging an entire repo (or history)?

**Comment by psafont** [comment]
Yes, this is specsaving ezxenstore to drop xenctrl from xs-opam

**Review by robhoes — APPROVED** [review]

**Comment by psafont** [comment]
Xenserver builds are passing the tests with the change, the xs-opam repo PR needs to be approved as well, however

**Pull request merged**
