### PR TITLE
Corrected strings.

### PR DESCRIPTION
**Pull request by kc284**
I noticed these when I dropped the latest SDK into XC.

### CODE REVIEW

**Review by robhoes — APPROVED** [review]
Looks good, but you probably need to update the schema test hash.

**Comment by kc284** [comment]
Yeah, the format too...

**Comment by kc284** [comment]
@robhoes I don't see any test failures that might warrant a schema test hash change, after I fixed the format all checks are passing.

**Comment by psafont** [comment]
We have broken CI internally right now, please hold the merge until it's resolved

**Pull request merged**
