### PR TITLE
Improved descriptions

### PR DESCRIPTION
**Pull request by thomassa**
Improved description for StaticRO and for VM.user_version.

### CODE REVIEW

**Comment by thomassa** [comment]
The "failed" build created the expected RPMs but then failed on `yum -y install rsync`, not indicating a problem with the changes in this pullreq.

**Comment by thomassa** [comment]
@xen-git Retest this please

**Comment by thomassa** [comment]
@johnelse "Keep" the information? I didn't think I removed any. But I've added another commit to be explicit about parameter in constructor. (I'll squash before merge.)

**Comment by jonludlam** [comment]
Are you going to squash these?

**Comment by johnelse** [comment]
Ok great :) just needs some squashing.

**Comment by thomassa** [comment]
Squashed. Just awaiting Travis build.

**Comment by johnelse** [comment]
:shipit: :boom:

**Pull request merged**
