### PR TITLE
CP-10532 (do not merge) work-in-progress for Virtual Hardware Platform Version

### PR DESCRIPTION
**Pull request by thomassa**
Rather than adding more comments to #2119 I thought it would be clearer or quicker to make code-changes.

Still to do:
* Testing
* Some people found "virt_hw_vn" confusing/unclear, and discussion (including looking at our existing names) led to "hardware_platform_version" for the VM, which suggests "virtual_hardware_platform_versions" for the host.

### CODE REVIEW

**Comment by djs55** [comment]
@thomassa just pointed out that I've commented on things he's already addressed -- sorry for the noise!

**Comment by djs55** [comment]
OK, apart from the `virt-hw-vn` name, think this is great :+1:

**Comment by thomassa** [comment]
Thank you @djs55.
Things to do before merging:
* I'll squash my existing commits into one.
* Test the behaviour
* Add another commit to change the names to VM.hardware_platform_version and Host.virtual_hardware_platform_versions.

**Comment by thomassa** [comment]
(In the light of Dave's comments, I've added the "reviewed" label to show that this is not awaiting review.)

**Comment by thomassa** [comment]
Closing this pullreq: it is superseded by and #2138 (which builds on top of it for the same feature-branch) and by #2169 (which selects just the Virtual Hardware Platform versioning and puts it onto the creedence-bugfix branch, with the new fields marked as being introduced in the cream release).

**Pull request closed without merging**
