### PR TITLE
CP-12512 Store copy of ssl_legacy in Inventory

### PR DESCRIPTION
**Pull request by thomassa**
When a slave starts, it cannot learn its Host.ssl_legacy without using
an stunnel to contact the master to consult the database. Therefore a
locally stored copy is needed.

Signed-off-by: Thomas Sanders <thomas.sanders@citrix.com>

### CODE REVIEW

**Comment by thomassa** [comment]
This relies on xapi-project/xcp-inventory#6

**Comment by thomassa** [comment]
@xen-git Retest this please

**Comment by thomassa** [comment]
Build failed with
```17:50:52 File "xapi_host.ml", line 892, characters 24-54:
17:50:52 Error: Unbound value Xapi_inventory._stunnel_legacy```
even though that value has been added to xapi_inventory in xapi-project/xcp-inventory#6.
We need to make new release of xcp-inventory to be used by xen-api.

**Comment by euanh** [comment]
@xen-git Retest this please

**Pull request merged**
