### PR TITLE
#PR1- CP-47869-Clean up unused XAPI code.

### PR DESCRIPTION
**Pull request by ashwin9390**
Main ticket:CP-47869

Split from https://github.com/xapi-project/xen-api/pull/5662 

This PR is about clean up  of XAPI code .

Reverted  rrdd-example.py as it is required . 

There is no major changes in the code for this PR ,test done in PR 5662  holds good.

Test result -198930 (Dev Run)
Ring0 BST - 8.4.0-206415 (pbb-ashwinh-xapiclean) (repo) run 30 May 2024
Tests Executed (excludes blocked): 47
Tests Failed: 1
Tests Errored: 0
Tests Blocked: 0
Tests Not Executed: 0
Test failed due to production issues: 0
Pass rate (excluding failures due to non product issues): 100.0%
Pass rate (of testcases XenRT was able to resource): 97.9%
Pass rate (of all test cases): 97.9%
Percentage of nightly complete: 100.0%
Tests excluded from numbers: 0

Signed-off-by: Ashwinh <ashwin.h@cloud.com>

@stephenchengCloud @liulinC @psafont

### CODE REVIEW

**Comment by lindig** [comment]
Are we sure this code is unused @edwintorok

**Comment by stephenchengCloud** [comment]
Before removing these files, Ashwin had a talk with Pau and Edwin.
And I double-checked the files below, and they are not installed in Dom0:

> ocaml/message-switch/core_test/message_switch_test.py
> ocaml/message-switch/python/message_switch.py
> ocaml/tests/has_vendor_device_test.py
> scripts/hatests
> scripts/mtcerrno-to-ocaml.py

@ashwin9390 Did you miss some files such as `ocaml/events/event_listen.py`, and `scripts/time-vm-boots.py`?

**Review by stephenchengCloud — APPROVED** [review]

**Comment by ashwin9390** [comment]
> Before removing these files, Ashwin had a talk with Pau and Edwin. And I double-checked the files below, and they are not installed in Dom0:
> 
> > ocaml/message-switch/core_test/message_switch_test.py
> > ocaml/message-switch/python/message_switch.py
> > ocaml/tests/has_vendor_device_test.py
> > scripts/hatests
> > scripts/mtcerrno-to-ocaml.py
> 
> @ashwin9390 Did you miss some files such as `ocaml/events/event_listen.py`, and `scripts/time-vm-boots.py`?


@stephenchengCloud  i did not remove scripts/time-vm-boots.py as this is an example file which will be required for debugging. Pushed commit  where event_listen.py has been removed.

**Comment by stephenchengCloud** [comment]
Might need rebase to the latest code to pass the CI check

**Comment by ashwin9390** [comment]
> 1. Might need to rebase to the latest code to pass the CI check
> 2. Removing scripts requires also removing them from Makefile.  https://github.com/xapi-project/xen-api/blob/feature/py3/scripts/Makefile#L135
@stephenchengCloud  : Need to figure out why ocaml test fails when iovirt is removed  from scripts and Makefile .

Reverted to last  successful commit which passed all the test.

**Review by psafont — APPROVED** [review]
I don't see any particular reason to keep these

**Review by liulinC — APPROVED** [review]

**Pull request merged**
