### PR TITLE
CP-25699 Refine PIF type check related stuff

### PR DESCRIPTION
**Pull request by krizex**
1. Add Xapi_pif_helpers.ml contains:
  + Add get_pif_type to get PIF type
  + Add X_is_allowed_on_pif serial functions to exectue check before creating
  VLAN, bond and tunnel
2. Add support of sriov PIF in nm.bring_pif_up and nm.bring_pif_down
3. Apply Xapi_pif_helpers.get_pif_type in nm.ml
4. Refine VLAN UT

Signed-off-by: Yang Qian <yang.qian@citrix.com>

---
This change is [Reviewable](https://reviewable.io/reviews/xapi-project/xen-api/3431)

### CODE REVIEW

**Comment by krizex** [comment]
Split https://github.com/xapi-project/xen-api/pull/3406 into smaller pull request to make it more reviewable.
This is the first part.

**Comment by robhoes** [comment]
Reviewed 9 of 10 files at r1.
Review status: 9 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[ocaml/idl/datamodel.ml, line 611 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-L4_WZs3ELFTJEzS0BU7:-L4_WZs3ELFTJEzS0BU8:b-hi3wvp) ([raw file](https://github.com/xapi-project/xen-api/blob/fcf85fde6b86799ba02ad2c3b256fce7f66efaff/ocaml/idl/datamodel.ml#L611)):*
> ```OCaml
>   error Api_errors.pif_unmanaged [ "PIF" ]
>     ~doc:"The operation you requested cannot be performed because the specified PIF is not managed by xapi." ();
>   error Api_errors.unknown_pif_type [ "PIF" ]
> ```

This condition would imply a bug in our software. It should therefore be an internal error, and we don't need a new Api_error.

---

*[ocaml/xapi/nm.ml, line 234 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-L4_ZVST7qgabafpnGjz:-L4_ZVST7qgabafpnGk-:b-y6rbz8) ([raw file](https://github.com/xapi-project/xen-api/blob/fcf85fde6b86799ba02ad2c3b256fce7f66efaff/ocaml/xapi/nm.ml#L234)):*
> ```OCaml
>   {default_interface with mtu; ethtool_settings; ethtool_offload; persistent_i=persistent;}
> 
> let rec create_bridges ~__context pif_ref pif_rc net_rc =
> ```

Looks like this ref isn't actually used now.

---

*[ocaml/xapi/xapi_pif.ml, line 27 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-L4__b7vv1rndIaBlFd9:-L4__b7vv1rndIaBlFdA:b-qif1q4) ([raw file](https://github.com/xapi-project/xen-api/blob/fcf85fde6b86799ba02ad2c3b256fce7f66efaff/ocaml/xapi/xapi_pif.ml#L27)):*
> ```OCaml
> open Threadext
> open Network
> open Xapi_pif_helpers
> ```

Why this?

---

*[ocaml/xapi/xapi_vlan.ml, line 67 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-L4__zCOAy4sl7W2MySU:-L4__zCOAy4sl7W2MySV:b4540w6) ([raw file](https://github.com/xapi-project/xen-api/blob/fcf85fde6b86799ba02ad2c3b256fce7f66efaff/ocaml/xapi/xapi_vlan.ml#L67)):*
> ```OCaml
>   (* Check the VLAN is not in use by the kernel *)
>   let open Network in
>   let device = Db.PIF.get_device ~__context ~self:tagged_PIF in
> ```

Again? I think that we should leave the `let device = ...` where it was, so that we can reuse it.

---

*[ocaml/xapi-consts/api_errors.ml, line 123 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-L4_aEUzCOz_uBsfRaJN:-L4_aEUzCOz_uBsfRaJO:b-nwhje3) ([raw file](https://github.com/xapi-project/xen-api/blob/fcf85fde6b86799ba02ad2c3b256fce7f66efaff/ocaml/xapi-consts/api_errors.ml#L123)):*
> ```OCaml
> let pif_has_fcoe_sr_in_use = "PIF_HAS_FCOE_SR_IN_USE"
> let pif_unmanaged = "PIF_UNMANAGED"
> let unknown_pif_type = "UNKNOWN_PIF_TYPE"
> ```

See comment above on datamodel.ml.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/xapi-project/xen-api/3431)*

**Comment by robhoes** [comment]
Reviewed 1 of 10 files at r1.
Review status: all files reviewed at latest revision, 15 unresolved discussions.

---

*[ocaml/xapi/xapi_pif.ml, line 27 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-L4__b7vv1rndIaBlFd9:-L4_fcFjJhAX5SNzH-up:b-bf9fr5) ([raw file](https://github.com/xapi-project/xen-api/blob/fcf85fde6b86799ba02ad2c3b256fce7f66efaff/ocaml/xapi/xapi_pif.ml#L27)):*
<details><summary><i>Previously, robhoes (Rob Hoes) wrote…</i></summary><blockquote>

Why this?
</blockquote></details>

Oh, the assert was moved. But better just prefix it with `Xapi_pif_helpers` where it is used. It is preferred to not routinely open modules, because it makes it harder to see where things come from.

---

*[ocaml/xapi/xapi_pif_helpers.ml, line 61 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-L4_h4VWedDsY3_GXoZF:-L4_h4VWedDsY3_GXoZG:b-pgm9y0) ([raw file](https://github.com/xapi-project/xen-api/blob/fcf85fde6b86799ba02ad2c3b256fce7f66efaff/ocaml/xapi/xapi_pif_helpers.ml#L61)):*
> ```OCaml
>     | None, _ -> f pif_rec, pif_rec
>   in
>   let get_pif_type pif_rec =
> ```

Maybe put this on the top level, so that Nm can use it directly (it doesn't need the whole chain).

---

*[ocaml/xapi/xapi_pif_helpers.ml, line 70 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-L4_gZX-Fo6JuQx7VtKk:-L4_gZX-Fo6JuQx7VtKl:bd509sv) ([raw file](https://github.com/xapi-project/xen-api/blob/fcf85fde6b86799ba02ad2c3b256fce7f66efaff/ocaml/xapi/xapi_pif_helpers.ml#L70)):*
> ```OCaml
>     with
>     | Some v, _ -> v
>     | None, _ -> raise (Api_errors.Server_error (Api_errors.unknown_pif_type, [pif_rec.API.pIF_uuid]))
> ```

This should be `Api_errors.internal_error`.

---

*[ocaml/xapi/xapi_pif_helpers.ml, line 130 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-L4_kxoN2YnStKkD3RJr:-L4_kxoN2YnStKkD3RJs:bcrg9z1) ([raw file](https://github.com/xapi-project/xen-api/blob/fcf85fde6b86799ba02ad2c3b256fce7f66efaff/ocaml/xapi/xapi_pif_helpers.ml#L130)):*
> ```OCaml
>     then raise (Api_errors.Server_error (Api_errors.pif_already_bonded, [ Ref.string_of self ]))
>   | VLAN_untagged _ :: _ ->
>     raise (Api_errors.Server_error (Api_errors.pif_vlan_exists, [ Db.PIF.get_device_name ~__context ~self] ))
> ```

`pif_rec.API.pIF_device_name`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/xapi-project/xen-api/3431)*

**Comment by robhoes** [comment]
To me this is almost good to go now. Just a few small tweaks to improve it.

---

Review status: all files reviewed at latest revision, 15 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-:-L4_nsH758TriiWWA-I6:b-fqoabh)*

**Comment by krizex** [comment]
Will update the change per comments and commit message accordingly.

---

Review status: all files reviewed at latest revision, 15 unresolved discussions.

---

*[ocaml/idl/datamodel.ml, line 611 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-L4_WZs3ELFTJEzS0BU7:-L4_pdHDs7sshUFKFCbI:b-896fix) ([raw file](https://github.com/xapi-project/xen-api/blob/fcf85fde6b86799ba02ad2c3b256fce7f66efaff/ocaml/idl/datamodel.ml#L611)):*
<details><summary><i>Previously, robhoes (Rob Hoes) wrote…</i></summary><blockquote>

This condition would imply a bug in our software. It should therefore be an internal error, and we don't need a new Api_error.
</blockquote></details>

Done.

---

*[ocaml/xapi/nm.ml, line 26 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-L4_mY1LNLuHGnjxz2fI:-L4_pt0G-lRh_bfZ27vH:b-896fix) ([raw file](https://github.com/xapi-project/xen-api/blob/fcf85fde6b86799ba02ad2c3b256fce7f66efaff/ocaml/xapi/nm.ml#L26)):*
<details><summary><i>Previously, mseri (Marcello Seri) wrote…</i></summary><blockquote>

I'd avoid doing this and mention the module where needed
</blockquote></details>

Done.

---

*[ocaml/xapi/nm.ml, line 234 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-L4_ZVST7qgabafpnGjz:-L4_qHy-HTAFbIRe2nov:b-896fix) ([raw file](https://github.com/xapi-project/xen-api/blob/fcf85fde6b86799ba02ad2c3b256fce7f66efaff/ocaml/xapi/nm.ml#L234)):*
<details><summary><i>Previously, robhoes (Rob Hoes) wrote…</i></summary><blockquote>

Looks like this ref isn't actually used now.
</blockquote></details>

Done.

---

*[ocaml/xapi/nm.ml, line 265 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-L4_mObZsVe7kAVIpbUZ:-L4a-6wfH0mXmGJlXbYy:b2nhswy) ([raw file](https://github.com/xapi-project/xen-api/blob/fcf85fde6b86799ba02ad2c3b256fce7f66efaff/ocaml/xapi/nm.ml#L265)):*
<details><summary><i>Previously, mseri (Marcello Seri) wrote…</i></summary><blockquote>

Is it worth to be more explicit here and make sure that there were no issues and we are on one of the physical interfaces and terminating?
</blockquote></details>

Yes

---

*[ocaml/xapi/nm.ml, line 295 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-L4_m67DLWVW57TEge6r:-L4a-AD5QW64ddeKJ2mH:b-896fix) ([raw file](https://github.com/xapi-project/xen-api/blob/fcf85fde6b86799ba02ad2c3b256fce7f66efaff/ocaml/xapi/nm.ml#L295)):*
<details><summary><i>Previously, mseri (Marcello Seri) wrote…</i></summary><blockquote>

See above
</blockquote></details>

Done.

---

*[ocaml/xapi/test_vlan.ml, line 104 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-L4_ltTZnkes8dJmEhqa:-L4_q_t3KEvzHGz4Kh_V:b-kya9ju) ([raw file](https://github.com/xapi-project/xen-api/blob/fcf85fde6b86799ba02ad2c3b256fce7f66efaff/ocaml/xapi/test_vlan.ml#L104)):*
<details><summary><i>Previously, mseri (Marcello Seri) wrote…</i></summary><blockquote>

was the old test invalid? Shouldn't we keep both the old and the new one?
</blockquote></details>

The old one is not comprehensive, it just set vlan tag, but not create vlan object, so the data model is incomplete.

---

*[ocaml/xapi/xapi_pif.ml, line 27 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-L4__b7vv1rndIaBlFd9:-L4_r4V-y8xlea0pwVR-:b-896fix) ([raw file](https://github.com/xapi-project/xen-api/blob/fcf85fde6b86799ba02ad2c3b256fce7f66efaff/ocaml/xapi/xapi_pif.ml#L27)):*
<details><summary><i>Previously, robhoes (Rob Hoes) wrote…</i></summary><blockquote>

Oh, the assert was moved. But better just prefix it with `Xapi_pif_helpers` where it is used. It is preferred to not routinely open modules, because it makes it harder to see where things come from.
</blockquote></details>

Done.

---

*[ocaml/xapi/xapi_pif_helpers.ml, line 55 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-L4_isILHwYb00HNfEmE:-L4a0ws02Lo92YyIwjMT:b-896fix) ([raw file](https://github.com/xapi-project/xen-api/blob/fcf85fde6b86799ba02ad2c3b256fce7f66efaff/ocaml/xapi/xapi_pif_helpers.ml#L55)):*
<details><summary><i>Previously, mseri (Marcello Seri) wrote…</i></summary><blockquote>

This looks much better than the original FSM.
Please add an extensive comment explaining what the topology returned looks like and how things are ordered
</blockquote></details>

Done.

---

*[ocaml/xapi/xapi_pif_helpers.ml, line 61 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-L4_h4VWedDsY3_GXoZF:-L4_rRpdLfd4c2jXTJ7o:b-896fix) ([raw file](https://github.com/xapi-project/xen-api/blob/fcf85fde6b86799ba02ad2c3b256fce7f66efaff/ocaml/xapi/xapi_pif_helpers.ml#L61)):*
<details><summary><i>Previously, robhoes (Rob Hoes) wrote…</i></summary><blockquote>

Maybe put this on the top level, so that Nm can use it directly (it doesn't need the whole chain).
</blockquote></details>

Done.

---

*[ocaml/xapi/xapi_pif_helpers.ml, line 70 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-L4_gZX-Fo6JuQx7VtKk:-L4_ul9gJ5nSujzzWTyY:b-896fix) ([raw file](https://github.com/xapi-project/xen-api/blob/fcf85fde6b86799ba02ad2c3b256fce7f66efaff/ocaml/xapi/xapi_pif_helpers.ml#L70)):*
<details><summary><i>Previously, robhoes (Rob Hoes) wrote…</i></summary><blockquote>

This should be `Api_errors.internal_error`.
</blockquote></details>

Done.

---

*[ocaml/xapi/xapi_pif_helpers.ml, line 71 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-L4_j0s22SGJKlv0is78:-L4a27tX3jmYCoQCKx-Z:b-896fix) ([raw file](https://github.com/xapi-project/xen-api/blob/fcf85fde6b86799ba02ad2c3b256fce7f66efaff/ocaml/xapi/xapi_pif_helpers.ml#L71)):*
<details><summary><i>Previously, mseri (Marcello Seri) wrote…</i></summary><blockquote>

Nice!
</blockquote></details>

Done.

---

*[ocaml/xapi/xapi_pif_helpers.ml, line 124 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-L4_impaDgWw47igSWEW:-L4a-rBKRBIGJtzPE4L0:b-dqkvwz) ([raw file](https://github.com/xapi-project/xen-api/blob/fcf85fde6b86799ba02ad2c3b256fce7f66efaff/ocaml/xapi/xapi_pif_helpers.ml#L124)):*
<details><summary><i>Previously, mseri (Marcello Seri) wrote…</i></summary><blockquote>

At first I thought that if it is `Physical`, it should be terminal and that we should have enforced it as `Physical pif_rec :: []` here in the pattern match and fail with an internal error if we have `Physical pif_rec :: tail when tail <> []`. Given that the terminality is guaranteed by construction, I would probably just mention the fact in the documentation comment for `get_pif_topo` requested above
</blockquote></details>

Yes, will doc the implementation.

---

*[ocaml/xapi/xapi_pif_helpers.ml, line 130 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-L4_kxoN2YnStKkD3RJr:-L4_vHU9wY1hyZtSAPWU:bs1cvsf) ([raw file](https://github.com/xapi-project/xen-api/blob/fcf85fde6b86799ba02ad2c3b256fce7f66efaff/ocaml/xapi/xapi_pif_helpers.ml#L130)):*
<details><summary><i>Previously, robhoes (Rob Hoes) wrote…</i></summary><blockquote>

`pif_rec.API.pIF_device_name`
</blockquote></details>

It is an internal only field, so cannot access by field name as you said.

---

*[ocaml/xapi/xapi_vlan.ml, line 67 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-L4__zCOAy4sl7W2MySU:-L4_xrJiOBRg_NXgCGbl:b-896fix) ([raw file](https://github.com/xapi-project/xen-api/blob/fcf85fde6b86799ba02ad2c3b256fce7f66efaff/ocaml/xapi/xapi_vlan.ml#L67)):*
<details><summary><i>Previously, robhoes (Rob Hoes) wrote…</i></summary><blockquote>

Again? I think that we should leave the `let device = ...` where it was, so that we can reuse it.
</blockquote></details>

Done.

---

*[ocaml/xapi-consts/api_errors.ml, line 123 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-L4_aEUzCOz_uBsfRaJN:-L4_vhvvbZq7ZY8Vo64i:b-896fix) ([raw file](https://github.com/xapi-project/xen-api/blob/fcf85fde6b86799ba02ad2c3b256fce7f66efaff/ocaml/xapi-consts/api_errors.ml#L123)):*
<details><summary><i>Previously, robhoes (Rob Hoes) wrote…</i></summary><blockquote>

See comment above on datamodel.ml.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-:-L4a2X9fPehA07110DIE:bz3qrr6)*

**Comment by krizex** [comment]
Updated per comment. Please have a look again @robhoes @mseri

**Comment by robhoes** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-:-L4a72uoMdn6VWJvf8cQ:bnfp4nl)*

**Comment by mseri** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[ocaml/xapi/xapi_pif_helpers.ml, line 124 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-L4_impaDgWw47igSWEW:-L4aK4zsHcY4dQYY0EhS:bx30c2u) ([raw file](https://github.com/xapi-project/xen-api/blob/fcf85fde6b86799ba02ad2c3b256fce7f66efaff/ocaml/xapi/xapi_pif_helpers.ml#L124)):*
<details><summary><i>Previously, krizex (Yang Qian) wrote…</i></summary><blockquote>

Yes, will doc the implementation.
</blockquote></details>

Note that with this change, an incorrect `Phisical _ :: tail when tail <> []` would be caught by the catch-all `_` below and incorrectly succeed, I think that (if we go with this change) we need to modify the code as 

```ocaml
| Physical pif_rec :: tail  when pif_rec.API.pIF_bond_slave_of <> Ref.null -> 
    if tail <> [] then
        raise Api_errors.(internal_erros, ["... a proper error here ..."])
    else ....
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/xapi-project/xen-api/3431)*

**Comment by krizex** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[ocaml/xapi/xapi_pif_helpers.ml, line 124 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-L4_impaDgWw47igSWEW:-L4aMLXeHw2AoYnp4vBP:b-y4kvyg) ([raw file](https://github.com/xapi-project/xen-api/blob/fcf85fde6b86799ba02ad2c3b256fce7f66efaff/ocaml/xapi/xapi_pif_helpers.ml#L124)):*
<details><summary><i>Previously, mseri (Marcello Seri) wrote…</i></summary><blockquote>

Note that with this change, an incorrect `Phisical _ :: tail when tail <> []` would be caught by the catch-all `_` below and incorrectly succeed, I think that (if we go with this change) we need to modify the code as 

```ocaml
| Physical pif_rec :: tail  when pif_rec.API.pIF_bond_slave_of <> Ref.null -> 
    if tail <> [] then
        raise Api_errors.(internal_erros, ["... a proper error here ..."])
    else ....
```

</blockquote></details>

Then I'd rather match the pattern as 
```
| Physical pif_rec :: _
```
because for now we don't care what tail is and actually as `Physical` is a terminate symbol, tail should always be `[]`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/xapi-project/xen-api/3431)*

**Comment by mseri** [comment]
*[ocaml/xapi/xapi_pif_helpers.ml, line 124 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-L4_impaDgWw47igSWEW:-L4aSvjcz5FInYUrNRvo:bk4l2vs) ([raw file](https://github.com/xapi-project/xen-api/blob/fcf85fde6b86799ba02ad2c3b256fce7f66efaff/ocaml/xapi/xapi_pif_helpers.ml#L124)):*
<details><summary><i>Previously, krizex (Yang Qian) wrote…</i></summary><blockquote>

Then I'd rather match the pattern as 
```
| Physical pif_rec :: _
```
because for now we don't care what tail is and actually as `Physical` is a terminate symbol, tail should always be `[]`.
</blockquote></details>

Fine with me but please add a comment saying `(* Here we rely on the implementation to guarantee that `Phisycal` is a terminating case *)` even if it is redundant

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/xapi-project/xen-api/3431)*

**Comment by mseri** [comment]
Reviewed 3 of 6 files at r2.
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/xapi-project/xen-api/3431)*

**Comment by krizex** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[ocaml/xapi/xapi_pif_helpers.ml, line 124 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-L4_impaDgWw47igSWEW:-L4aVAQPtjeo1qArKwLM:bghg5z3) ([raw file](https://github.com/xapi-project/xen-api/blob/fcf85fde6b86799ba02ad2c3b256fce7f66efaff/ocaml/xapi/xapi_pif_helpers.ml#L124)):*
<details><summary><i>Previously, mseri (Marcello Seri) wrote…</i></summary><blockquote>

Fine with me but please add a comment saying `(* Here we rely on the implementation to guarantee that `Phisycal` is a terminating case *)` even if it is redundant
</blockquote></details>

Sure. One day if someone introduce a new PIF type, the guy should go through all the pattern match and should not omit this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/xapi-project/xen-api/3431)*

**Comment by mseri** [comment]
:lgtm:

---

Reviewed 2 of 6 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-:-L4aZg4kYM-IWTHUBBkU:bnfp4nl)*

**Comment by robhoes** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[ocaml/xapi/xapi_pif_helpers.ml, line 124 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-L4_impaDgWw47igSWEW:-L4a_UQtYLEdbevJ-IYp:b77gzml) ([raw file](https://github.com/xapi-project/xen-api/blob/fcf85fde6b86799ba02ad2c3b256fce7f66efaff/ocaml/xapi/xapi_pif_helpers.ml#L124)):*
<details><summary><i>Previously, krizex (Yang Qian) wrote…</i></summary><blockquote>

Sure. One day if someone introduce a new PIF type, the guy should go through all the pattern match and should not omit this.
</blockquote></details>

Pity to have miss-spelled the word "Physical" three times now, but fine... ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/xapi-project/xen-api/3431)*

**Comment by mseri** [comment]
*[ocaml/xapi/xapi_pif_helpers.ml, line 124 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-L4_impaDgWw47igSWEW:-L4ad4Bqng932Ylg-X_1:bcr5tf1) ([raw file](https://github.com/xapi-project/xen-api/blob/fcf85fde6b86799ba02ad2c3b256fce7f66efaff/ocaml/xapi/xapi_pif_helpers.ml#L124)):*
<details><summary><i>Previously, robhoes (Rob Hoes) wrote…</i></summary><blockquote>

Pity to have miss-spelled the word "Physical" three times now, but fine... ;)
</blockquote></details>

Ops, my bad. I terrible with catching misspells. It can be fixed in a new micro PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/xapi-project/xen-api/3431)*

**Comment by krizex** [comment]
*[ocaml/xapi/xapi_pif_helpers.ml, line 124 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3431#-L4_impaDgWw47igSWEW:-L4ckm-XR5jI9nn-0fz7:bop5tfl) ([raw file](https://github.com/xapi-project/xen-api/blob/fcf85fde6b86799ba02ad2c3b256fce7f66efaff/ocaml/xapi/xapi_pif_helpers.ml#L124)):*
<details><summary><i>Previously, mseri (Marcello Seri) wrote…</i></summary><blockquote>

Ops, my bad. I terrible with catching misspells. It can be fixed in a new micro PR.
</blockquote></details>

I will cover the fix of the typo in next PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/xapi-project/xen-api/3431)*

**Pull request merged**
