### PR TITLE
Update merlin file

### PR DESCRIPTION
**Pull request by jonludlam**
Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>

### CODE REVIEW

**Comment by jonludlam** [comment]
Doesn't make it any worse - xapi-libs-transitional has never existed as a valid ocamlfind name

**Comment by gaborigloi** [comment]
Should we also add `cdrom netdev oUnit stdext stunnel systemd xenstore-compat xapi-test-utils`? These are referenced as `BuildDepends` in the `_oasis` file, but aren't internal libraries.

**Comment by mseri** [comment]
`xenstore-compat` is going to disappear

**Comment by jonludlam** [comment]
Fixed now, and rebase on master.

**Comment by lindig** [comment]
Travis fails:

```
Error: No Package found for xenopsd-devel
```

This is required by Xapi and was recently added to xenopsd.


```
xapi.spec:BuildRequires: xenopsd-devel
```

```
%changelog
* Fri Mar 24 2017 Jon Ludlam <jonathan.ludlam@citrix.com> - 0.23.0-2
- Add xenopsd-devel package
```

I suspect that the package is not yet publicly available.

**Pull request merged**
