### PR TITLE
CP-15892: Add SR.is_tools_sr field

### PR DESCRIPTION
**Pull request by robhoes**

### CODE REVIEW

**Comment by johnelse** [comment]
Code looks good. How about adding a test of the upgrade rule to https://github.com/xapi-project/xen-api/blob/master/ocaml/test/test_xapi_db_upgrade.ml ? :)

**Comment by robhoes** [comment]
@johnelse Interesting idea!

**Comment by robhoes** [comment]
@johnelse Done.

**Comment by johnelse** [comment]
Cool! :shipit:

**Pull request merged**
