### PR TITLE
CP-11865: Handle membership of hosts for xenvm

### PR DESCRIPTION
**Pull request by simonjbeaumont**

### CODE REVIEW

**Comment by simonjbeaumont** [comment]
@xen-git: test this please

**Comment by simonjbeaumont** [comment]
Just tested this with xapi-project/testarossa and does the right thing. The travis build is broken because trunk-thin-lvhd-2 is behind trunk and opam is using newer versions of things. The xen-git job works.

**Comment by johnelse** [comment]
Looks good to go in once the code freeze is over.

**Comment by simonjbeaumont** [comment]
Note: Do not merge... waiting for destination branch to stabilise first.

**Pull request merged**
