### PR TITLE
Test CA226886: test import.vdi when SR is unavailable for any host.

### PR DESCRIPTION
**Pull request by minli1**
This is a unit test for CA226886 code change. Test import_raw_vdi.import when the sr is unavailable for any host.It should raise exn and set the task to fail.
I factor the existing code to make it more suitable for unit testing. Since it's easier than writing socket server end /client end codes to create a real socket in unit-test.

### CODE REVIEW

**Comment by minli1** [comment]
Hi, @gaborigloi  and @robhoes  
Could you please help to review? 
Since I had factored the existing code in import_raw_vdi.ml to make it more suitable for unit testing.
But when I writing a unit test, it enters `fail_task_in_request` to make the task failed, it's also needed a socket which I can't bypass. SO I had to assert_raises for `Unix.Unix_error(Unix.ENOTCONN, "write", "")`.
I am wondering if there is a better way in Ounit to compare the results.
Any comments will be great and thankful.

**Comment by jonludlam** [comment]
I'm not sure I quite understand this. You're changing the external behaviour of one of the HTTP handlers  - why are you dong that and what is the effect? That change needs to be in a separate commit from any test, so we also need to split this PR into at least 2 commits.

**Comment by minli1** [comment]
Hi, Jon. @jonludlam Thanks for you reply.
1. I change this `import` function by removing the `Xapi_http.assert_credentials_ok` to the `handler`. This is because I don't put a real connected socket into the params, the `Xapi_http.assert_credentials_ok` will fail if the socket is not connected.
2. So I factor the existing code just like this test which was told by @robhoes. 
https://github.com/xapi-project/xen-api/commit/0c62b77695874f777e1195b7dc52b6b7a9092132.
3. It's not quite a better way to write socket server/client code to create a real socket, right? Since unit test does not a place for testing inter-process communication.
4.Yes,I can spilt this PR into 2 commits.

Thanks a lot. 
BR.

**Comment by gaborigloi** [comment]
Hmm, this function seems to be quite hard to unit test sadly :/
To test the new behaviour, we should test

* That the task passed in the query is set to failed
* That an HTTP error is returned to the client

I think we can only test the first thing here, maybe we could set up the socket somehow to receive the HTTP response, but that might be too complicated for a unit test.

**Comment by minli1** [comment]
Thanks, @gaborigloi.
You mean we still need somehow set up the socket to receive the HTTP response, right?
But it seems to need to set up socket server end and client end. We may create it in a more common place and use it, so next time someone else will use them.
Please correct if I misunderstanding.

**Comment by gaborigloi** [comment]
Hi @minli1 , I think setting up the socket might be impossible or very complicated :(. So I think we can maybe only unit test item 1), that the task is set to failed. Sorry, my comment was misleading when I said that we could a unit test for this - I expected it to be much easier to unit test this function. Maybe we'll just have to write a XenRT test in the end, if we cannot unit test 1) either.

**Comment by gaborigloi** [comment]
So I think what we could still try is to pass a task in the `req` parameter, and ignore any exceptions that happen (including `Unix.Unix_error(Unix.ENOTCONN, "write", "")`), and observer the status of that task when the function returned, it should be "failed".

**Comment by minli1** [comment]
Thanks @gaborigloi 
I will update the PR then.

**Comment by minli1** [comment]
Hi, @gaborigloi  
I finally passed the task in the `request` and using `Ounit.assert_equal` to verify the task is set failed when the function returned. It worked in unit test.
For this, I also refactor some existing code which suggested by @robhoes to make them more suitable for unit test.
I split the commit into two, one for refactor and one for unit test only.
Please help to review, thanks in advance.

**Comment by jonludlam** [comment]
I wonder if it would make more sense to test this from quicktest?

**Comment by gaborigloi** [comment]
Agreed, this seems to be hard to unit test sadly, it's so connected to other things.

**Comment by minli1** [comment]
Hi, @gaborigloi  
I am wondering is this possible to test from quicktest? I will have a look. It may also need to refactor even in quicktest.
By the way, how to verify the result in quicktest, I use `make` to run the quicktest. Is this right?
Thanks.

**Comment by gaborigloi** [comment]
@minli1 Run `/opt/xensource/debug/quicktest` on a XenServer host.

**Comment by minli1** [comment]
HI, Jon and Gabor. @jonludlam @gaborigloi 
I raised a new PR for a quicktest for this. See: https://github.com/xapi-project/xen-api/pull/3152
Please help to review. Thanks!

**Comment by stephen-turner** [comment]
Does the quicktest PR replace this one? If so, let's close this one. Thank you.

**Comment by mseri** [comment]
Looks like a duplicate. Closing for now. Please reopen if I am wrong

**Pull request closed without merging**
