### PR TITLE
Remove the no longer used legacy baseline SMAPIv3 scripts and tests (api.v5 is the current SMAPIv3 version)

### PR DESCRIPTION
**Pull request by bernhardkaindl**
Remove the no longer used legacy baseline SMAPIv3 scripts and tests:
- api.v5 is the current SMAPIv3 version:
  - Recently, we updated our last API consumer to v5.
  - It should now have no consumers left.
- Coordinated with @MarkSymsCtx and @psafont 
- Obsoletes these PRs (and possibly a lot more for cleaning up this obsolete generated API code):
  - #5850
  - #5857
  - #5858
  - #5859

### CODE REVIEW

**Comment by psafont** [comment]
Nothing here is converting python 2 to python3, can this be merged to master instead?

**Comment by bernhardkaindl** [comment]
Yes, it can be merged into master.

The context why I opened it for `feature/py3` is:
1. As part of the main task to *move* of the Python scripts to the `python3/` directory, other deletions of Python2 code have been applied to `feature/py3` already.

2. Through @ashwin9390, we asked @stephenchengCloud if he can include this PR into the QA test run of the `feature/py3` branch, that @stephenchengCloud scheduled for this week.

**Comment by psafont** [comment]
That's fine as well, thanks

**Review by psafont — APPROVED** [review]

**Review by MarkSymsCtx — APPROVED** [review]

**Comment by bernhardkaindl** [comment]
Thanks for the reviews and approvals!

We asked @stephenchengCloud if he can include this PR into the planned QA test run of the feature/py3 branch.

@stephenchengCloud asked me in https://github.com/xapi-project/xen-api/pull/5828#issuecomment-2232288779 to hold off on merges for a while, so I would plan to let him make the decision on if he likes to include this PR into his planned regression test.

If he likes to include it, he can ask us or Lin Liu can merge it.

Or also, he could clone the branch into a branch of this repo and test the branch itself without merging it already.

**Comment by stephenchengCloud** [comment]
@bernhardkaindl @liulinC
We can include this PR and also https://github.com/xapi-project/xen-api/pull/5867 into the test.
Could you merge these two PRs today?

**Comment by bernhardkaindl** [comment]
@stephenchengCloud 
> We can include this PR and also #5867 into the test.
> Could you merge these two PRs today?

Merged this PR now!

#5867 would need a 2nd approver, but it only updates configurations but not code.
I'd say that it is lower priority because of that.

Rationale:

Because #5867 does not change code, it would not change the `xapi` `rpms`.
Therefore, this PR should not influence the regression test.

It means you do not have to wait for #5867 to be merged for your build.

**Pull request merged**
