### PR TITLE
RBAC fix for Host.reset_server_certificate

### PR DESCRIPTION
**Pull request by lippirk**

### CODE REVIEW

**Review by psafont — APPROVED** [review]
the local_session was previously used because it was copied from the emergency call. This correctly changed to a normal No_fd

**Review by robhoes — APPROVED** [review]

**Comment by robhoes** [comment]
Good catch.

**Comment by robhoes** [comment]
Mr Format Checker is strict :)

**Comment by lippirk** [comment]
> Mr Format Checker is strict :)

he is a stroppy madam

**Pull request merged**
