### PR TITLE
Bring feature/perf up-to-date with master

### PR DESCRIPTION
**Pull request by edwintorok**
Fixed some conflicts in the Makefile, C bindings gen, and a build issue with pgpu_dom0_access_to_string

### CODE REVIEW

**Comment by edwintorok** [comment]
xe-xentrace was changed recently, will look into fixing it so it passes the CI.

**Comment by edwintorok** [comment]
Once I fixed some of the warnings shellcheck did actually find this one that points to an actual bug:
```
echo ...
if [ $? -ne 0 -o -z "${vdi_uuid}" ]; then
     ^-- SC2320 (warning): This $? refers to echo/printf, not a previous command. Assign to variable to avoid it being overwritten.
```

**Review by psafont — APPROVED** [review]

**Review by psafont — CHANGES_REQUESTED** [review]
This is merging perf to master (!)

**Comment by edwintorok** [comment]
> This is merging perf to master (!)

Good spot, fixed

**Review by Vincent-lau — APPROVED** [review]

**Review by Vincent-lau — COMMENTED** [review]
hmm, are you now merging perf in your private fork to the perf in upstream, is this right? I thought it would be something like into `xapi-project:master` from `xapi-project:feature/perf`?

**Comment by edwintorok** [comment]
"[edwintorok](https://github.com/edwintorok) wants to merge 80 commits into [xapi-project:feature/perf](https://github.com/xapi-project/xen-api/tree/feature/perf) from [edwintorok:feature/perf](https://github.com/edwintorok/xen-api/tree/feature/perf)"

I think it merged into the correct place into xapi-project

**Pull request merged**
