### PR TITLE
Add Command to enable and disable PCI device for Windows PV auto update

### PR DESCRIPTION
**Pull request by cheng--zhang**
This pull request mainly do 2 things:
1. Add command to enable and disable PCI device for windows PV auto update
2. Remove the usage of pic_pv in VM.platfrom and add VM.auto_update drivers to indicate if the windows auto update is enable or disable.

### CODE REVIEW

**Comment by robhoes** [comment]
@cheng--zhang I've finished the review of this now. There are a few things to fix as mentioned above, but nothing too complicated, and it should be good to go after you've addressed those.

**Comment by cheng--zhang** [comment]
Hi @robhoes 
I have complete the comments rework, and have a basic test based on the new commit.
Please help to review the commit.
Thanks.

**Comment by robhoes** [comment]
This looks good. Just one more thing that I missed yesterday: the assert function should have the same arguments as the set function. Right now, the `value` arg is missing. It is not used, but good to add in case we may need it.

**Comment by robhoes** [comment]
Thanks for the updates Cheng. This is ready to go in now (I noticed some cli_operations changes that are now dead code, but will remove them while merging).

**Comment by robhoes** [comment]
It's all merged now into trunk-car1755. I'll do a bit of squashing when we put this into master.

**Pull request merged**
