### PR TITLE
CA-180495: Run update-issue service on management_interface re-configure

### PR DESCRIPTION
**Pull request by sharady**
File /etc/issue needs to be updated with latest management ip
on performing management_interface re-configure.
This can be achived by running update-issue service.

Signed-off-by: Sharad Yadav <sharad.yadav@citrix.com>

### CODE REVIEW

**Comment by robhoes** [comment]
I think this code is in the right place, but would request a few enhancements:
- Catch any errors from executing the script. Calling it is done on a "best effort" basis.
- Add the path to the script to the xapi.conf config file (via xapi_globs.ml).
- Ross recommended restarting the terminals after calling update-issue by ``/usr/bin/killall -q -HUP mingetty agetty``.

**Comment by robhoes** [comment]
I think that the paths still need to be added to the `nonessential_executables` list in xapi_globs.ml for the config file magic to work.

**Comment by sharady** [comment]
Thanks @robhoes for the review, please have a look once more :smile: 
I have updated the required changes.

**Comment by robhoes** [comment]
Looks good now, thanks.

**Pull request merged**
