### PR TITLE
CA-380389: Version of deprecation/removal for repository.up_to_date n…

### PR DESCRIPTION
**Pull request by gangj**
…ot documented correctly

### CODE REVIEW

**Comment by gangj** [comment]
Sorry for the build failure, updated~

**Review by lindig — APPROVED** [review]

**Comment by psafont** [comment]
Shouldn't the version be 23.13.0?

**Comment by gangj** [comment]
> Shouldn't the version be 23.13.0?

@psafont  Sorry, I didn't explained clearly.
The filed "repository.up_to_date" was first removed in the "CDN on-prem update" epic in the feature branch, and then the feature branch was merged into master till version "23.18.0". So I think the version here should be: "23.18.0"

**Review by psafont — APPROVED** [review]
I don't see any other versions ending with `-next` that need to be fixed

**Comment by gangj** [comment]
> I don't see any other versions ending with `-next` that need to be fixed

I also checked that. Thank you!

**Pull request merged**
