### PR TITLE
CP-18172 fix: catch exception when parsing last booted record

### PR DESCRIPTION
**Pull request by lindig**
To obtain the last-booted record, this commit now uses
Helpers.get_boot_record_of_record instead of Helpers.parse_boot_record
This fixes the problem that VM.resume was failing because of an
exception that was escaping from parse_boot_record when no last boot
record exists but that is caught by get_boot_record_of_record. The
semantics of get_boot_record_of_record seems dubious as it in that case
returns the current record.

Signed-off-by: Christian Lindig <christian.lindig@citrix.com>

### CODE REVIEW

**Comment by robhoes** [comment]
> The semantics of get_boot_record_of_record seems dubious as it in that case returns the current record.

Should I not be worried about this implications of this statement?

**Comment by lindig** [comment]
How would you describe this?

		(** Fetch the configuration the VM was booted with *)
		let get_boot_record_of_record ~__context ~string:lbr ~uuid:current_vm_uuid =
			try
				parse_boot_record lbr
			with e ->
			(* warn "Warning: exception '%s' parsing last booted record (%s) - returning current record instead" lbr (ExnHelper.string_of_exn e); *)
				Db.VM.get_record ~__context ~self:(Db.VM.get_by_uuid ~__context ~uuid:current_vm_uuid)

**Comment by robhoes** [comment]
I mean, you are fixing a bug by using a function that you do not seem to trust. That worries me :)

**Comment by robhoes** [comment]
Closing this, as it turns out that the original patch was not right.

**Pull request closed without merging**
