### PR TITLE
CP-22202: Add unit tests for VLANs

### PR DESCRIPTION
**Pull request by sharady**
Signed-off-by: Sharad Yadav <sharad.yadav@citrix.com>

### CODE REVIEW

**Comment by mseri** [comment]
I don't understand why the test is failing

**Comment by sharady** [comment]
Fixing it.

**Comment by robhoes** [comment]
```
Error: No implementations provided for the following modules:
         Test_vlan referenced from suite.cmx
```

**Comment by robhoes** [comment]
I suppose Travis is failing because it needs an `oasis setup` to recognise the new file...

**Pull request merged**
