### PR TITLE
CA-184513: Fix deadlock with PBD.plug and stats VDI creation

### PR DESCRIPTION
**Pull request by simonjbeaumont**

### CODE REVIEW

**Comment by simonjbeaumont** [comment]
Don't merge yet... moar to come.

**Comment by jonludlam** [comment]
Looks good so far though

**Comment by simonjbeaumont** [comment]
@jonludlam says:
> Can we do away with the `~archive` option to `copy_sr_rrds` and just do it always?

**Comment by simonjbeaumont** [comment]
@jonludlam additional commit c7428ff addresses your comment: https://github.com/xapi-project/xen-api/pull/2427#issuecomment-145065086

**Pull request merged**
