### PR TITLE
CA-141580: Fix dom0 console handler

### PR DESCRIPTION
**Pull request by simonjbeaumont**
Xenopsd no longer manages dom0 and so Xapi cannot ask it for the address of
dom0's console. Instead it should use the information it has in the database.

Incidentally, this information was no longer correct. Dom0 has had its console
on 5901 for a while it seems but the database used to get updated correctly
when Xenopsd managed dom0.

Signed-off-by: Si Beaumont <simon.beaumont@citrix.com>

### CODE REVIEW

**Comment by johnelse** [comment]
All looks good, but I wonder if we need to upgrade all dom0 ports in the database from 5900 to 5901 to make sure this works after an upgrade. Or is this handled somewhere else?

**Comment by simonjbeaumont** [comment]
Good point. Or we could work out why it got changed from 5900 and put it back?

**Comment by johnelse** [comment]
Yeah that would be ideal :)

**Comment by johnelse** [comment]
Woohoo! Let's merge it.

**Pull request merged**
