### PR TITLE
CP-13492: Add sr_rrd http handler for SR-level RRDs

### PR DESCRIPTION
**Pull request by sharady**
Signed-off-by: Sharad Yadav <sharad.yadav@citrix.com>

### CODE REVIEW

**Comment by sharady** [comment]
This PR should go along with https://github.com/xapi-project/xcp-rrdd/pull/50

**Comment by johnelse** [comment]
Looks good. This is ready to merge once https://github.com/xapi-project/xcp-rrdd/pull/50 is fixed up.

**Comment by sharady** [comment]
@johnelse we need to merge this one as well. As https://github.com/xapi-project/xcp-rrdd/pull/50 it's in now.

**Comment by johnelse** [comment]
Thanks for reminding me :)

**Pull request merged**
