### PR TITLE
CP-34439 merge rrd2csv into xapi

### PR DESCRIPTION
**Pull request by lippirk**
:eyeglasses:

### CODE REVIEW

**Comment by lippirk** [comment]
Sibling PR of https://github.com/xapi-project/xs-opam/pull/494

**Comment by psafont** [comment]
Is the DCO bot going to give us a hard time?

**Comment by robhoes** [comment]
This looks good, but I think we should delete a few more files from `ocaml/rrd2csv`. The readme doesn't make sense anymore, and also the LICENSE and MAINTAINERS files are redundant. There are also several dot files.

**Comment by robhoes** [comment]
I've switched off the DCO requirement for now. It's not suitable for this kind of PRs.

**Pull request merged**
