### PR TITLE
CP-10770: Don't duplicate read_caching key in sm_config

### PR DESCRIPTION
**Pull request by simonjbeaumont**
Signed-off-by: Si Beaumont <simon.beaumont@citrix.com>

### CODE REVIEW

**Comment by simonjbeaumont** [comment]
I have added this extra commit to https://github.com/xapi-project/xen-api/pull/2125

**Comment by johnelse** [comment]
Looks good to me.

**Comment by djs55** [comment]
I can never remember whether 'remove_from' raises an exception if the key is already missing. Could you confirm that it doesn't? After that this looks fine to me since this code is already in a critical section.

**Comment by johnelse** [comment]
@djs55 remove_from was safe last I tested it, I remember checking it for [this thing](https://github.com/xapi-project/xen-api/blob/6cb62ea4ae295bccc933aca5e615182363528284/ocaml/xapi/xapi_vm_migrate.ml#L214).

**Comment by simonjbeaumont** [comment]
It seems safe from a test of this use, and I think these are the functions which are invoked:

https://github.com/xapi-project/xen-api/blob/master/ocaml/database/db_cache_types.ml#L352-L360

You can see the `add_to...` gives an exception on duplicates but the `remove_from...` seems to not be as fascist.

**Pull request merged**
