### PR TITLE
Get Travis to update the XenAPI docs on xapi-project.github.io

### PR DESCRIPTION
**Pull request by robhoes**

### CODE REVIEW

**Comment by robhoes** [comment]
Needs xapi-project/xenserver-build-env#61.

**Comment by robhoes** [comment]
Travis is happy now, but hasn't actually built the docs yet; it needs the xenserver-build-env change first.

**Comment by robhoes** [comment]
Hmmm...
```
19:06:05 error: Failed build dependencies:
19:06:05 	texlive-scheme-basic is needed by xapi-1.9.57-8554.x86_64
```
Adding that to the spec file did not make xen-git happy.

**Comment by robhoes** [comment]
I'll remove the spec-file change for now... It wasn't necessary for the JSON-based docs.

**Comment by robhoes** [comment]
Needs xenserver/xenserver-build-env#63

**Comment by johnelse** [comment]
Looks good!

**Pull request merged**
