### PR TITLE
CP-36827: Backport XSI-989

### PR DESCRIPTION
**Pull request by liulinC**
Signed-off-by: Lin Liu <lin.liu@citrix.com>

### CODE REVIEW

**Comment by liulinC** [comment]
Build failed as `ocaml-xen-api-libs-transitional` is not updated as library.

**Comment by psafont** [comment]
> Build failed as ocaml-xen-api-libs-transitional is not updated as library.

The xs-opam branch needs to be updated as well with the bumped xapi-libs-transitional version: https://github.com/xapi-project/xs-opam/tree/6.35.1-lcm/packages/xs-extra/xapi-libs-transitional.2.25.0

**Comment by liulinC** [comment]
> > Build failed as ocaml-xen-api-libs-transitional is not updated as library.
> 
> The xs-opam branch needs to be updated as well with the bumped xapi-libs-transitional version: https://github.com/xapi-project/xs-opam/tree/6.35.1-lcm/packages/xs-extra/xapi-libs-transitional.2.25.0

Thanks @psafont for help,  Does this means I need to tag `xapi-libs-transitional` like `2.25.2` and update the link in https://github.com/xapi-project/xs-opam/blob/6.35.1-lcm/packages/xs-extra/xapi-libs-transitional.2.25.0/opam#L27 ?
If yes, should I rename the whole folder to `xapi-libs-transitional.2.25.2` or just keep it as `xapi-libs-transitional.2.25.0` ?

**Comment by psafont** [comment]
That's correct, the version should be updated and that needs the name of the directory to change as well

**Review by lippirk — APPROVED** [review]

**Review by lindig — APPROVED** [review]

**Pull request merged**
