### PR TITLE
Formatting

### PR DESCRIPTION
**Pull request by jonludlam**

### CODE REVIEW

**Comment by johnelse** [comment]
😮 🎉

**Comment by robhoes** [comment]
😱

**Comment by robhoes** [comment]
Pity that there are no Jumbomojis on github...

**Comment by robhoes** [comment]
Let's do this now, before anyone notices...

**Comment by robhoes** [comment]
@djs55 You'll never believe that I just pressed the green button on this...

**Comment by jonludlam** [comment]
woot :-)

**Comment by robhoes** [comment]
@jonludlam Clever to do this on your college day, at a safe distance.

**Comment by jonludlam** [comment]
nobody can hit me from here!

**Comment by olivierlambert** [comment]
holy cow, you almost killed GitHub while trying to display the full diff!

**Comment by johnelse** [comment]
Lines added = Lines removed, so it must be legit :+1:

**Comment by thomassa** [comment]
@jonludlam wrote:
> nobody can hit me from here!

*AAS (not that we'd want to).

**Comment by stephen-turner** [comment]
@robhoes I hope you code-reviewed the diff line-by-line before accepting it.

**Comment by robhoes** [comment]
@stephen-turner Of course, there were no changes, right?

- https://github.com/xapi-project/xen-api/pull/2759/commits/5a003f446391ca05ec791c38c69e93fb1e718e78?w=0
- https://github.com/xapi-project/xen-api/pull/2759/commits/f43c221ad556bc85870faebc3ce3c9d6e9c2efd8?w=0

**Pull request merged**
