### PR TITLE
CA-182595 VM.hard_shutdown: use subtask for cancelling

### PR DESCRIPTION
**Pull request by thomassa**
Also same for VM.hard_reboot.

When Message_forwarding.VM.hard_shutdown cancels other tasks such as
clean_shutdown, now it uses a fresh subtask for each cancellation,
instead of doing the cancellation more directly.

This fixes a bug: if a clean_shutdown task was in progress on a VM on
a slave, then VM.hard_shutdown invoked via "xe vm-shutdown --force"
would fail after cancelling the clean_shutdown. This was because when
the call to the slave (to cancel the clean_shutdown) completes, it
marks the task running it as completed successfully. Since this task
was the main task for the hard_shutdown, the waiter in cli_operations
noticed and destroyed the task, logging out the corresponding xapi
session and telling xe that the command had succeeded. Therefore when
Message_forwarding.VM.hard_shutdown went on to its next step and
tried to tell the slave to shut down the VM, it was using an expired
xapi session so it failed.

Therefore using a new subtask for the cancellation fixes the bug.

The same problem was not observed for "xe vm-reboot --force" because
in Cli_operations.vm_reboot makes a straightforward synchronous call,
whereas vm_shutdown makes an async call and passes the task to the
waiter function.  Nonetheless, the task was still being marked
prematurely as completed, so this commit makes the same change in
Message_forwarding.VM.hard_reboot as in the corresponding shutdown.

Also in this pull-request:
Make call_slave_with_session simpler and safer

Message_forwarding.call_slave_with_session

Overall the effect is the same, but we save creating and destroying a
task, the code is easier to understand, and as soon as the new session
exists, everything else is done with "finally destroy the session".

### CODE REVIEW

**Comment by djs55** [comment]
Interesting -- I suspect the Task/Context machinery is a bit confused (since a Context contains a Task inside it). Could you point me at the bit where `Task.cancel` kills the task from the context rather than the task arg? I'm trying to (re)gain a picture of how this is all supposed to work :)

**Comment by simonjbeaumont** [comment]
Do we have an understanding of why this isn't an issue when the force operation is a force_reboot? Or is the failure mode just masked?

**Comment by thomassa** [comment]
@djs55 No, `Task.cancel` does kill (cancel) the correct task as intended. But once this has been done, the running task is marked as complete (success). I don't think this is anything special about `Task.cancel`, and if the action had been something else then we'd have avoided a red herring.

@simonjbeaumont I don't know at present; I've not looked at that.

**Comment by jonludlam** [comment]
reboot issued via the CLI doesn't suffer from this as the CLI uses the synchronous VM.reboot calls rather than the async ones. The problem occurs because the task is prematurely marked as completed, at which point the CLI notices the task is complete, assumes that everything is finished and logs out the session, causing the rest of the operation to fail.

**Comment by jonludlam** [comment]
I wonder if the title could be a bit better? There's no premature logout in "VM.hard_shutdown" being fixed here...? (either 'vm-shutdown --force' or something mentioning the task being prematurely completed?)

**Comment by thomassa** [comment]
I've made the same code-change for hard_reboot now, and removed the extra logging, and improved the commit message.

Good now?

**Comment by thomassa** [comment]
@xen-git Retest this please

**Pull request merged**
