### PR TITLE
SR-level RRD fixes

### PR DESCRIPTION
**Pull request by simonjbeaumont**

### CODE REVIEW

**Comment by simonjbeaumont** [comment]
@xen-git retest this please.

**Comment by simonjbeaumont** [comment]
@xen-git retest this please.

**Comment by johnelse** [comment]
Other than that :arrow_heading_up: this looks good to me.

**Comment by johnelse** [comment]
Oh, how about some unit tests for `check_plugged_on_master_constraint` and `check_unplugged_on_slaves_constraint`? :wink:

**Comment by johnelse** [comment]
Yep looks good :+1: :shipit:

**Pull request merged**
