### PR TITLE
VDI.revert pull request + extra bits

### PR DESCRIPTION
**Pull request by djs55**
This is @johnelse's #1963 plus

- `xe vdi-revert`
- SMAPIv1 plumbing: `VDI_REVERT` and `vdi_revert`, using the `VDI.clone` code as a fallback

### CODE REVIEW

**Comment by jonludlam** [comment]
@xen-git retest this please

**Comment by jonludlam** [comment]
I believe that this currently requires 'snapshot_of' to be set correctly. However, we know that reverting a VM causes the snapshot_of field to be broken in all currently released XenServers. We must be able to cope with this having happened in the past so what is the solution? @johnelse, any ideas?

**Comment by johnelse** [comment]
Also I believe importing doesn't set the snapshot_of fields correctly, which is why we had to revert this fix before.

I'm not sure what the solution is once the snapshot_of links are already broken - is there anyway we could reliably link the disks together again? Using the vbd device position might not work if the leaf VM has had disks added and removed (but then would storage migrate work anyway?).

**Comment by jonludlam** [comment]
No, I think there's no way to fix the links.

**Comment by euanh** [comment]
At our morning meeting, we decided to move all the open snapshot-related changes onto a branch where they can be tested more thoroughly.

**Comment by euanh** [comment]
Seems to be stuck, closing as agreed in our meeting today.

**Pull request closed without merging**
