### PR TITLE
Licence restrictions for Windows Update

### PR DESCRIPTION
**Pull request by thomassa**

### CODE REVIEW

**Comment by thomassa** [comment]
(More commits still to be added, but I want the automatic test builds to run.)

**Comment by jonludlam** [comment]
I don't think we want to merge the commit titled 'foo'

**Comment by thomassa** [comment]
Oops, that commit was always meant to be squashed into the previous one. Done now.

Now the biggest part of reviewing this pull-request is not reviewing the changed code (though obviously that needs doing), but considering whether anything else needs to be done.
Possibly the trickiest decisions were for:
* Calls to `VM.revert` when the specified snapshot refers to a non-existent VM, so we make a call to the internal function `Xapi_vm_snapshot.create_vm_from_snapshot`
* `VM.recover` and `VM_appliance.recover`

**Comment by thomassa** [comment]
Closing this for the time being, pending testing.

**Pull request closed without merging**
