### PR TITLE
Fix for the VM lifecycle diagram

### PR DESCRIPTION
**Pull request by lindig**
I verified this diagram with some experiments and added an explicit new
state `destroyed` to make clear that `VM.destroy` can only be called from
the halted state.

vm_lifecycle

Signed-off-by: Christian Lindig <christian.lindig@citrix.com>

### CODE REVIEW

**Comment by robhoes** [comment]
Nice! Could you also update `vm_lifecycle.eps` please? That's what actually gets included in the XenAPI Reference PDF (try `make doc-pdf`).

**Comment by robhoes** [comment]
And also here please (.png and .dot): https://github.com/xapi-project/xapi-project.github.io/tree/master/xen-api.

**Comment by lindig** [comment]
Will do it.

**Comment by thomassa** [comment]
I feel that generated eps and png files aren't source and shouldn't be in the repository (but let's leave fixing that for another day and another pull-request).

**Comment by robhoes** [comment]
@thomassa I agree, but doing that would introduce new build dependencies, and this image isn't something that would need to be regenerated often (I think that this was the first time in 10 years).

**Comment by robhoes** [comment]
:shipit:

**Comment by thomassa** [comment]
Checks have passed, so merging.

**Pull request merged**
