### PR TITLE
Merge `master` into `feature/py3` to fix OCaml CI failures using #5726

### PR DESCRIPTION
**Pull request by bernhardkaindl**
In https://github.com/xapi-project/xen-api/pull/5731#issuecomment-2189273929, @psafont wrote:
> The ocaml failure is fixed with https://github.com/xapi-project/xen-api/pull/5726 Longer term a merge from master is needed

That's great!

This PR is:
- A simple `git merge master` into `feature/py3`.
- No conflicts occurred, it was just the merge command (and update of the branches before).

I repeated it a 2nd (and a 3rd) time and compared those to the PR/merge branch (see comments).

@stephenchengCloud

PS: Initially, I forgot to select feature/py3 in the GUI when opening the PR: Is corrected.
The list of commits was always correct and GitHub is displaying the correct commits now.
A reference PR in my test repo that shows the same commits is here: https://github.com/xenserver-next/xen-api/pull/25

### CODE REVIEW

**Comment by Vincent-lau** [comment]
emm, am I confused, why is this merging into master?

**Comment by bernhardkaindl** [comment]
Thanks! Fixed the target branch to `feature/py3`.

**Review by Vincent-lau — APPROVED** [review]

**Comment by bernhardkaindl** [comment]
In order to be sure that the merge should be correct, I repeated the merge a 2nd time, commands:
```py
# fetch latest git:
git remote -v|grep origin
origin  git@github.com:xapi-project/xen-api.git (fetch)
origin  git@github.com:xapi-project/xen-api.git (push)
git fetch origin
git checkout feature/py3
git pull
Already up to date.

# merge:
git checkout -b merge-master-to-py3-to-fix-ci-using-5726-$USER feature/py3
git merge origin/master

# Compare to pushed PR:
git remote add xenserver-next git@github.com:xenserver-next/xen-api.git
git fetch xenserver-next
git diff xenserver-next/merge-master-to-py3-to-fix-ocaml-ci-pr-5726
(no diff)
```

**Review by stephenchengCloud — APPROVED** [review]

**Review by liulinC — APPROVED** [review]

**Comment by psafont** [comment]
The latest master has another fix in the tests, it's worth dropping this merge and creating a new one

**Review by edwintorok — APPROVED** [review]
target branch looks fine, probably best to cherry pick the latest bugfix from master (or recreate the merge)

**Comment by bernhardkaindl** [comment]
Edwin wrote:
> might need to merge another CI fix from master

Thanks, will merge this fix in a new PR.

**Pull request merged**
