### PR TITLE
 CP-23788: VM guest metrics can read SR-IOV VF IPs 

### PR DESCRIPTION
**Pull request by xiewei20082008**
This change is [Reviewable](https://reviewable.io/reviews/xapi-project/xen-api/3498)

### CODE REVIEW

**Comment by xiewei20082008** [comment]
Local build passed. Travis failed is because PPX changes has not been merged in.

**Comment by mseri** [comment]
Looks good, I just have a minor stylistic commet

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[ocaml/xapi/xapi_guest_agent.ml, line 225 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3498#-L74tcydtOFOzkcRg2nK:-L74tcyfI8VKOWnarTPZ:b-mgh6h0) ([raw file](https://github.com/xapi-project/xen-api/blob/a82a04f1faf0d9320a3acd443913db0da468023e/ocaml/xapi/xapi_guest_agent.ml#L225)):*
> ```OCaml
>   and os_version = to_map os_version
>   and device_id = to_map device_id
>   and networks = to_map (networks "attr" "vif" list) @ to_map (networks "xenserver/attr" "net-sriov-vf" list)
> ```

I think you can concat the list and call `to_map`once. I think the multiline concat version remains more readable
```ocaml
and networks = to_map (List.concat [
    networks "attr" "vif" list
  ; networks "xenserver/attr" "net-sriov-vf" list
])`
```


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/xapi-project/xen-api/3498#-:-L74u6ojfSR59Ln02u0n:blenec2)*

**Comment by mseri** [comment]
After you make the change suggested above (if you decide to do it), if everything builds fine and `make test` is succesful, feel free to merge the PR

---

Reviewed 1 of 1 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/xapi-project/xen-api/3498#-:-L75EFU81DL6UTuTCVz6:b-n20nag)*

**Comment by mseri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/xapi-project/xen-api/3498)*

**Comment by xiewei20082008** [comment]
Done. `make test` is successful. Thank you.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[ocaml/xapi/xapi_guest_agent.ml, line 225 at r1](https://reviewable.io:443/reviews/xapi-project/xen-api/3498#-L74tcydtOFOzkcRg2nK:-L77gDrxcuzOrlxX4tq5:b-896fix) ([raw file](https://github.com/xapi-project/xen-api/blob/a82a04f1faf0d9320a3acd443913db0da468023e/ocaml/xapi/xapi_guest_agent.ml#L225)):*
<details><summary><i>Previously, mseri (Marcello Seri) wrote…</i></summary><blockquote>

I think you can concat the list and call `to_map`once. I think the multiline concat version remains more readable
```ocaml
and networks = to_map (List.concat [
    networks "attr" "vif" list
  ; networks "xenserver/attr" "net-sriov-vf" list
])`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/xapi-project/xen-api/3498#-:-L77g1HF1v6nbCZnVhIX:b-w9vh7a)*
<!-- Sent from Reviewable.io -->

**Comment by cheng-z** [comment]
Merge the code as all test passed and comments reworked.

**Pull request merged**
