### PR TITLE
Eliminate unnecessarily scary log lines

### PR DESCRIPTION
**Pull request by robhoes**

### CODE REVIEW

**Comment by robhoes** [comment]
Draft: still running tests.

**Review by lindig — APPROVED** [review]

**Review by psafont — APPROVED** [review]
The logic to watch event looks quite complex, but I cannot spot any obvious issue with the change.

(previously exceptions were used to interrupt a while loop, not a guard is used)

**Comment by robhoes** [comment]
Test failure looks like something else, so this change is clear.

**Comment by psafont** [comment]
shoutout to make @rwdrich feel vindicated :)

**Pull request merged**
