### PR TITLE
Fix coverage Travis build and update to OCaml 4.04.2

### PR DESCRIPTION
**Pull request by gaborigloi**
Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>

### CODE REVIEW

**Comment by gaborigloi** [comment]
Coverage build worked: https://travis-ci.org/xapi-project/xen-api/builds/274186587?utm_source=github_status&utm_medium=notification :smile: 
Will remove the workaround once https://github.com/simonjbeaumont/ocaml-travis-coveralls/pull/14 is merged.

**Comment by gaborigloi** [comment]
@mseri my version of `sed` returns a 0 exit code regardless of whether it found a match or not. It returns a non-zero code for invalid expressions.

**Comment by mseri** [comment]
Let's wait and see if the patch is merged tomorrow, if not we merge this with the workaround

**Comment by gaborigloi** [comment]
The PR has been merged, I've removed the workaround.

**Pull request merged**
