### PR TITLE
CP-45006: Define volume.compose API for SMAPIv3.

### PR DESCRIPTION
**Pull request by KevinLCtx**
Description was adapted from SMAPIv2.

### CODE REVIEW

**Comment by lindig** [comment]
This looks ok but it would be good to provide more context in the commit message.

**Review by lindig — APPROVED** [review]

**Comment by KevinLCtx** [comment]
Updated commit message.

**Comment by lindig** [comment]
We have all kinds of CI issues here that need to be addressed

**Comment by robhoes** [comment]
Looks fine, but you may need to define the new function in xapi-storage-script, as it may otherwise complain about a missing implementation when starting up. I'll try it out and will let you know.

**Review by robhoes — APPROVED** [review]

**Pull request merged**
