### PR TITLE
CP-9795: Split xenservices initscript

### PR DESCRIPTION
**Pull request by rosslagerwall**
Run one service per init script, splitting xenservices into xenstored
and xenconsoled since this is handled better by systemd.

Signed-off-by: Ross Lagerwall <ross.lagerwall@citrix.com>

### CODE REVIEW

**Comment by johnelse** [comment]
@xen-git test this please

**Comment by djs55** [comment]
In xen-4.5 xenstored has direct support for systemd (of some kind). Will
that help?

On Thu, Jan 8, 2015 at 2:10 PM, John Else <notifications@github.com> wrote:

> @xen-git <https://github.com/xen-git> test this please
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xapi-project/xen-api/pull/2043#issuecomment-69183368>.
>



-- 
Dave Scott

**Comment by rosslagerwall** [comment]
Yes it should, but until such time as Xen 4.5 is merged into trunk and the systemd stuff is turned on, this change reduces the delta between trunk and trunk-c7.

**Comment by rosslagerwall** [comment]
Can this be merged? I'd like to pull through as much stuff through trunk as possible...

**Comment by djs55** [comment]
Let's do it

**Pull request merged**
