### PR TITLE
Determine IP address type from inventory when creating a PIF

### PR DESCRIPTION
**Pull request by benjamreis**
Do not assume IPv4 instead see what's in the inventory's
`MANAGEMENT_ADDRESS_TYPE`.

### CODE REVIEW

**Review by robhoes — CHANGES_REQUESTED** [review]
I think the actual problem is that the PIF scan, which re-introduces all PIFs for a host after a network reset, does not set the primary address type based on the inventory, but hardcodes it to IPv4. See `introduce_internal` in xapi_pif.ml. You can fix it there instead by reading the inventory and creating the PIF with the correct value right away.

**Comment by benjamreis** [comment]
> I think the actual problem is that the PIF scan, which re-introduces all PIFs for a host after a network reset, does not set the primary address type based on the inventory, but hardcodes it to IPv4. See `introduce_internal` in xapi_pif.ml. You can fix it there instead by reading the inventory and creating the PIF with the correct value right away.

It'd mean that all PIFs are assumed to have the same addrss type as the management interface by default whn doin a scan.
It's not ideal but It's a little better than IPv4 everywhere indeed.
I'll try what you suggested. Thanks

**Comment by benjamreis** [comment]
Tested with @robhoes and works as expected: The PIF is recreated with the correct addtress type specified in the inventory.

**Review by robhoes — APPROVED** [review]
It looks good now, but please update the commit message to reflect that the new patch does.

**Comment by benjamreis** [comment]
Done!

**Review by psafont — APPROVED** [review]

**Pull request merged**
