### PR TITLE
CP-22274: Replace string_trim with built-in String.trim

### PR DESCRIPTION
**Pull request by fillzero**
Signed-off-by: Liang Dai <liang.dai1@citrix.com>

Move `string_trim` outside for unit test according to @jonludlam ’s advice.

### CODE REVIEW

**Comment by jonludlam** [comment]
Good start...

**Comment by fillzero** [comment]
@jonludlam I will add the unit test file and update this PR later.

**Comment by mseri** [comment]
Why don't we directly use `Stdext.(strip isspace)` (https://github.com/xapi-project/stdext/blob/master/lib/xstringext.ml#L73) ?

**Comment by mseri** [comment]
Why we don't move it to Stdext next to https://github.com/xapi-project/stdext/blob/master/lib/xstringext.ml#L73 ?

**Comment by gaborigloi** [comment]
Could we use the built-in [`String.trim` function](http://caml.inria.fr/pub/docs/manual-ocaml-4.02/libref/String.html#VALtrim) instead?

**Comment by mseri** [comment]
Even better

**Comment by fillzero** [comment]
@mseri @gaborigloi 
Thanks for your comments. 
I've updated accordingly.

**Comment by mseri** [comment]
Thanks, this is a good update. Will the unit tests be part of an other PR you plan to add them here?

**Comment by fillzero** [comment]
@mseri 
I have also updated the PR title.
Given we use the built-in function now, I think there is no need for `String.trim` unit test.
Thanks.

**Comment by mseri** [comment]
Oh, the tests were for the trim function only. I missed that. Good!

**Comment by thomassa** [comment]
No, the unit tests that @jonludlam said are necessary before merging #3031 are for "at least the function being changed (and the functions it in turn calls" where the function being changed is `AuthADlw.pbis_get_group_sids_byname`

So we do still need some unit test(s), either in this pull-request or a subsequent pull-request.
I'm happy for this pull-request to be merged now if there will be another one with the unit tests.

**Comment by thomassa** [comment]
@fillzero, please would you do one of these two options?
* tell us that the unit tests will be in another pull-request (and we'll merge this one), or
* add the unit tests to this pull-request

**Comment by fillzero** [comment]
@thomassa  @mseri 
I will add the unit tests and update this PR later.

**Comment by fillzero** [comment]
Close this PR  as #3031 supersedes this.

**Pull request closed without merging**
