### PR TITLE
Fix total order in Ref.compare

### PR DESCRIPTION
**Pull request by edwintorok**
Explanation in commit messages. Draft, because I only unit tested it.

### CODE REVIEW

**Review by psafont — APPROVED** [review]

**Comment by edwintorok** [comment]
I think Ref.compare is completely unused at the moment (my code on vtpm branch would be its first user?)

**Comment by psafont** [comment]
I believe that's true, I added with the intention to use it for the database GC, but we ended up not needing it

**Comment by edwintorok** [comment]
forgot to rerun formatting, CI should pass now, lets see.

**Review by lindig — APPROVED** [review]
I think the comments in the code should be updated.

**Comment by lindig** [comment]
I believe this should be back ported

**Comment by psafont** [comment]
This code is not present in 8.2.1, there's no need to backport

**Pull request merged**
