### PR TITLE
Merge stdext and reverse deps into XAPI

### PR DESCRIPTION
**Pull request by edwintorok**
Merges as git subtree:
* xapi-inventory
* xapi-rrd
* xapi-stdext*

Opening PR to see whether the CI works.

### CODE REVIEW

**Comment by edwintorok** [comment]
https://github.com/xapi-project/xen-api/pull/5383 and https://github.com/xapi-project/xen-api/pull/5382 as separate draft PRs if you want to see how xapi-inventory and xapi-rrd got merged.
I tried to keep the merge commits buildable by using 'git commit -a --amend' when I did build fixes like moving opam files around or updating Makefiles/quality gates.

**Comment by edwintorok** [comment]
> Is it worth it, wouldn't it be easier to drop the dune definiton of the packages of the stdext libs?

I found another way of doing it (by using .opam.template files). In general I'd like to move to generating files from dune-project, because then we can also use tools like 'opam dune lint' that checks the consistency of dependencies between opam files and dune files, and we can also share some metadata (e.g. consistent homepage, build rules and bugreport urls). And it'll also encourage us to have fewer opam files, we have way too many now....

**Comment by psafont** [comment]
>  And it'll also encourage us to have fewer opam files, we have way too many now....

I agree, also at some point dune should support stashing them away in the opam subdir

**Comment by edwintorok** [comment]
Tests are passing now, and I've also done a successful koji build.
(Haven't tried a chainbuild after removing the packages from xs-opam yet).

**Comment by psafont** [comment]
Can the unneeded files in `ocaml/libs/xapi-stdext/`, `ocaml/libs/xapi-inventory/` and `ocaml/libs/xapi-rrd/`? (like the github workflows or gitignore) be removed

**Comment by edwintorok** [comment]
I've cleaned up the merged subprojects, I've kept .gitignore/ChangeLog/LICENSE/README:
```
ocaml/libs/xapi-inventory/:
.  ..  .gitignore  ChangeLog  LICENSE  README.md  lib

ocaml/libs/xapi-rrd:
.  ..  .gitignore  ChangeLog  LICENSE  README.md  lib  lib_test  unix

ocaml/libs/xapi-stdext:
.  ..  .gitignore  CHANGES.md  LICENSE  README.md  lib
```

**Review by psafont — APPROVED** [review]

**Comment by psafont** [comment]
I'd like to push this forward, but after the fixed release is done.

**Review by lindig — APPROVED** [review]

**Comment by psafont** [comment]
Overrriding the DCO check, all commits are from Xenserver / Citrix employees at the time of committing

**Comment by psafont** [comment]
I've checked that the tests in the new packages have been run

**Pull request merged**
